### ISSUE TITLE
Restore tab in same place it was closed after `action.reopenTab`

### ISSUE THREAD

**Issue by InconsolableCellist** [Jelmerro/Vieb#103]
Steps to reproduce:
1. Open two tabs
2. Go to tab 1
3. Hit 'd' to execute "action.closeTab"
4. Hit 'u' to execute "action.reopenTab"

Observed behavior: 
Restored tab goes into position 2, not position 1

Expected Behavior:
Restored tab goes into position 1, which is where it was when it was closed

This can be repeated for tabs in any position

The expected behavior is like that in at least Pentadactyl and Vimperator

**Comment by Jelmerro** [comment]
I don't see how this is a bug. At most this is unexpected, but restoring tabs works and currently always opens to the right of the current one. Regardless of what you want to call it, we could add a setting to determine on which side restored tabs should open, if that is more in line with what you expect. Is that a workable solution? Or do you propose something else?

**Comment by InconsolableCellist** [comment]
It's not really about left or right, it's about its previous location. My versions of Firefox and Chromium both seem to do this, so I figured it's a bug.

If you have 8 tabs, and close tab #3, then no matter what tab you're on when you restore it, it'll return to the #3 position.

**Comment by Jelmerro** [comment]
I seems that we both expect different positions when restoring tabs. I have always found it odd that I couldn't control the tab position when restoring, and that it would remember that kind of info even when tabs are closed. For me that was more of an annoyance than a feature. So in Vieb I made it consistently open and reopen tabs to the right of the current one.

As such, I won't work on this myself in the near future, but feel free to implement a setting for the tab restore position via a PR, with the possible values: "left", "previous" and "right" (default).

**Comment by Jelmerro** [comment]
Implemented in https://github.com/Jelmerro/Vieb/commit/6ac7db9f0c72ae850529de1375a7c1d544a1e927, try running and building from the V4 branch to check it out, or wait for the next stable (first week of march hopefully).
