### ISSUE TITLE
Middle mouse click in Linux needs to paste text

### ISSUE THREAD

**Issue by InconsolableCellist** [Jelmerro/Vieb#104]
Steps to reproduce:
1. In Xorg, select text in Veib or another application. This puts it in the PRIMARY clipboard
2. In Veib, type `:set mouse`
3. Hit 'e' to enter Explore mode, hover the mouse cursor over the text input area, and hit middle mouse button
3 alternate. Go to duckduckgo.com, hover the mouse cursor over the DDG search bar, hit middle mouse button

Observed behavior: 
Nothing is pasted

Expected behavior:
The contents of the PRIMARY clipboard are pasted into the text field

Veib AppImage on Devuan in X

**Comment by gebner** [comment]
I have a commit in my fork that addresses the clipboard issue (partially): https://github.com/gebner/Vieb/commit/d6b4ca905c65f76c1fd02718ca59449e3227fb55

Middle-button paste works fine.  But what doesn't work yet is selecting text in the webview (and automatically copying it to primary).  I should probably make a PR for the url bar part, and then look into the selection issue separately.

**Comment by Jelmerro** [comment]
Based on Gebner's commit, I have made a commit that includes this functionality. I made some small changes to the code, to better adapt to the mouse setting.

Code is on master, so you can run/build that to test it, or wait for the next stable release.

**Comment by InconsolableCellist** [comment]
Thanks, I can confirm this works. It seems to work too with selecting text when in `Normal` mode
