### ISSUE TITLE
Implement an action to copy the current URL to the clipboard

### ISSUE THREAD

**Issue by InconsolableCellist** [Jelmerro/Vieb#105]
Hitting `y` or similar should yank the current URL to the clipboard.

Implement an action to visit the contents of the clipboard as a new URL

Hitting `p` or similar should visit the current contents of the clipboard as a URL. Hitting `P` or similar should visit it in a new tab.

**Comment by Jelmerro** [comment]
This seems like a nice addition, though it's probably already possible with a custom mapping.

**Comment by InconsolableCellist** [comment]
Do you know what action I could bind to to do this?

**Comment by Jelmerro** [comment]
Actually, upon trying to come up with the mapping, it seems that there is a missing link to make this work. Adding these actions seems like a nice and much cleaner way to make this possible.

**Comment by Jelmerro** [comment]
These actions have been implemented in the latest commit on master. Feel free to reopen if there is something that is missing.
