### ISSUE TITLE
Text input is lost when editing a text input area with an external editor and then changing tabs

### ISSUE THREAD

**Issue by InconsolableCellist** [Jelmerro/Vieb#108]
This results in a lot of lost effort if you've been typing something for a while (which is a good reason to open an external editor in the first place).

Steps to reproduce: 
1. Browse to a site with a text input field. E.g., "New Issue" on github
2. Set focus to the text input field and hit `<Ctrl-i>` to open an external editor
3. Insert text in the editor
4. Change tabs in Vieb
5. Save and close the editor
6. Return to the previous tab where you were entering text

Observed Results: 
None of the text you wrote in the external editor is in the text input field, and is lost

Expected Results
The text shows up in the text input field regardless of what tab you're on, and/or the text is recoverable in some way

**Comment by InconsolableCellist** [comment]
(BTW, I'm adding so many bugs because I really like this project and I'm trying to use it as a daily browser. Pentadactyl is ancient at this point.)

**Comment by Jelmerro** [comment]
No worries, more issues in the issue tracker doesn't mean that Vieb has a lot of new problems, it just means they are made visible. Even if some of them are trivial or if they require breaking changes, it's good to have a them visible here regardless. I'll tag them accordingly and sometimes rename them so people know what it's about, and everything with "help wanted" is up to the community to fix (as I won't work on that myself). As always PRs are welcome regardless.

With regards to this ticket, I think I know the issue actually. It searches for the "document.activeElement" when you save the file and it should update the input field. This will only work if you are just editing a single field at the time, and don't remove focus from it, which is exactly what you are doing by switching tabs. I personally just use the external editor for single field edits. So I didn't encounter this issue. It's definitely something I plan to fix, as this will greatly improve the usability of this option. It will probably just come down to keeping an object of elements in the action preload file that binds the timestamp/filename to an input field.

**Comment by Jelmerro** [comment]
Should be fixed on master now. Let me know your observations.

**Comment by InconsolableCellist** [comment]
Thanks, that was quick! It works now for me
