### ISSUE TITLE
howto enable darkreader

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#117]
Linux arch with DWM tiling windows manager.
vieb-bin from AUR Version         : 3.0.0-1

I have several problems.
1. darkreader is in the .config/Vieb/viebrc set darkreader but doesn't work.
2. I fail to understand how to set a custom startpage that I designed for qutebrowser.
3. the install is in /opt/ but did not start from there. I had to link vieb to my .local/bin which is in the path. Not sure if that couses the problems.

**Comment by Jelmerro** [comment]
Most Linux installers do store the files in `/opt/`, but also make an executable at `/usr/bin/vieb`. On most systems this is in the path, so you should just be able to start with `vieb` from your terminal, or from any kind of start menu you might have. If not, you might want to get in touch with the distributor of the vieb-bin package in the AUR, as that is beyond my control (I don't use arch). You could try the pacman file, but I have no idea how this is supposed to be installed on arch, just that I can build it with electron-builder.

Regarding the darkreader issue, just entering the `set darkreader` command in your viebrc should work. So here are a few questions I want to ask:

- Is this also a problem when running a newer version of Vieb?
- Does the command work when you run it later as a command?
- Can you run just `:set` to see if it actually gets set?
- Did you refresh the pages after setting this option?

**Comment by BachoSeven** [comment]
2. is easily solved by using `set startuppages="file:///home/fra/.config/browser/startpage/index.html"
`

3. is a packaging problem which I reported [downstream](https://aur.archlinux.org/packages/vieb-bin/#comment-785421), if you prefer you can install the official Arch release provided at https://vieb.dev/download (`sudo pacman -U sudo pacman -U vieb-3.2.0.pacman`)

**Comment by Jelmerro** [comment]
Good to know that it's a packaging issue that has already been reported. Just let me know where specifically you get stuck with enabling darkreader.

You can add pages to  `startuppages` to open them at startup. Keep in mind that by default your previous session is also restored (see `:h restoretabs`).

**Comment by se7en-x230** [comment]
Thanks for the fast answer.

There is only this version in AUR and vieb did not get copied into the path /usr/bin/ as it should.
But i fixed the problem and you are correct that is something I will report to the maintainer of the package.

I checked the viebrc file and the entry is written
I tried to set it again and the result is the same.
Github and all sites are white.
Yes refreshed restarted..nothing.
The viebrc file gets loaded as I changes tabbar to autohide and that works fine.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by se7en-x230** [comment]
arch package flaged out of date ... and symlink is reported.

I tried the 3.2.0.0 version off your site and that works like a charm. 

Thanks for your help and keep up the great work. I love the browser and
coming from qutebrowser I LOVE THE SPEED !!! 
Python is such a pain for a browser.

Exellent work. Thank you 

Sven

**Comment by Jelmerro** [comment]
Glad to hear it works in the new version.

**Comment by BachoSeven** [comment]
About the AUR package, I've created a [`vieb`](https://aur.archlinux.org/packages/vieb) package which correctly installs the `.pacman` releases, and have sent a merge request to `vieb-bin`.

Leaving this here so Arch users can install this package until the maintainer responds.

**Comment by se7en-x230** [comment]
Nice thanks. Does this build include the new input.js changes? 
Asking because it stil adds my url to the existing...

**Comment by Jelmerro** [comment]
No, this release seems to be based on `3.2.0`, which was made before I fixed the url selection issue. The first release to include the fix will be `3.3.0`.

**Comment by se7en-x230** [comment]
Nice work. 
I hope you find a way to redirect follow to an external applicatation like youtube-dl or mpv as well :)

the package complains about folder permission...but works fine

warning: directory permissions differ on /opt/Vieb/
filesystem: 775  package: 755

**Comment by BachoSeven** [comment]
@se7en-x230 That's odd. Can you try uninstalling any previous version of `vieb` and then reinstalling? 

The permission should be fixed in my package.

**Comment by se7en-x230** [comment]
@BachoSeven that fixed that :+1:
