### ISSUE TITLE
Run custom external commands for links on the page

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#120]
is there a way to run an external application with the follow comand?

example
nmap M <action.open-with-mpv

**Comment by Jelmerro** [comment]
This isn't possible as of yet, but you can copy the link if you combine follow mode with the pointer copy action.

**Comment by BachoSeven** [comment]
@Jelmerro If I understand correctly the way to copy a link through follow mode is: `v` to enter pointer mode, `f` to start following, then pressing the appropriate letters to move the pointer there, and finally pressing `y` to copy the link.

I would like to shorten this a little bit because it's a useful combination, and have  `yf` enter "follow-and-copyq" mode, so I tried with:
```
nmap yf <pointer.start><action.startFollowCurrentTab><pointer.copyAndStop>
```
But this of course does not wait for the user to press the necessary follow letters. Do you think there is a way to achieve this, waiting for a selected link to copy it?

**Comment by Jelmerro** [comment]
I'm sure it's possible to do if we consider changing the code, but I think a binding to just enter follow mode after entering pointer mode will work just as well. For example: `nmap x <pointer.start><action.startFollowCurrentTab>` and then just pressing the right key and `y` will copy any link on the page. That's just 3 keys (max 4 if there are 26+ links on the page), which I don't consider much for performing such an action. Though if you think we need this, feel free to open a separate issue or implement it via PR as long as it doesn't conflict with existing follow mode workflows.

Regarding the edit you made, I would just recommend to increase the guihidetimeout if you don't press these keys fast enough. Or you could add a binding to scroll down a bit and then copy if you really wanted to, but increasing the hidetimeout seems like a nicer solution.

**Comment by Jelmerro** [comment]
I implemented an action and a setting for this on the V4 branch [here](https://github.com/Jelmerro/Vieb/commit/0dee1a86583f223521ffa205c0da0bd754af090b). You can test it by checking out that branch and running it from source, or making your own builds. Alternatively you can wait for the next stable release (begin march) which will include this new feature. Feel free to ask any questions if you still have them.

**Comment by se7en-x230** [comment]
I build 3.5.0-dev istalled it via pacman -U <package> added 
set externalcommand="mpv"
map m <action.openLinkExtenal>

but if I start both commands are not found.
Is there a way inside the browser to check the version number?

**Comment by Jelmerro** [comment]
You need to checkout the `feature/v4` branch, it's not on the master branch yet. There is a version page that can be opened with `:version`, or you can do `vieb --version`.

**Comment by se7en-x230** [comment]
This is version 3.5.0-dev of Vieb.

**Comment by Jelmerro** [comment]
You need the latest version from [this branch](https://github.com/Jelmerro/Vieb/tree/feature/v4) and download that source. If you have cloned the repo with git you also run this command to switch to the V4 branch: `git checkout feature/v4`

**Comment by se7en-x230** [comment]
okey that did the trick.
Do I understand that the command is run on the main page only?

So in youtube on the main video. I tied to go in pointer mode and choose with f   url (in a playlist) and then run my openLinkExternal keybinding. In my case "m" but that does nothing.

How would I set it up like a custom f? Getting all the link hints, meaning I press "m" followed by the hint combination and that openLinkExternal with my choosen application.

Thanks by the way ... love Vieb

**Comment by Jelmerro** [comment]
You should be able to get answers for these questions in the help page (`:h action.openLinkExternal` and `:h externalcommand`). It will use the highlighted url (either via mouse or pointer) that is shown at the bottom to open externally. If no url is hovered, it will fallback to the current page url.

I just want to mention that the command you listed: `map m <action.openLinkExtenal>` has two problems:
- It contains a typo, so it will show a notification that the action couldn't be found (it's `openLinkExternal` not `openLinkExtenal`)
- This will also add the mapping to modes that are usually used to type text, meaning you won't be able to type the `m` anymore, so I recommend just adding the mapping for the right modes: `nmap m <action.openLinkExternal>` and `pmap m <action.openLinkExternal>` or if you want to use the global map, make sure to pick a binding that doesn't conflict in any mode.

So could you double check with `:nmap` that the mapping has actually been added? And even without adding any kind of custom mapping, this should work:
- Just pressing `x` without doing anything should open the current url externally (unless you hovered something with the mouse)
- Hovering a url with pointer mode and then pressing `x` should open the hovered url externally

**Comment by se7en-x230** [comment]
Exellent with the right version I also have the right :h search.
Works like a charm.
