### ISSUE TITLE
set costom theme as default

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#121]
How can I set my colors/custom.css be loaded by default. 
I can enable it but I fail to understand how to load it by default.

**Comment by Jelmerro** [comment]
You can make a viebrc file and type `colorscheme custom` as a command in it. Vieb will first parse the folders and then apply the commands from your viebrc, so you don't need to type the full path. You should be able to use the same commands in your viebrc as compared to command mode.

**Comment by Jelmerro** [comment]
Feel free to reopen if you still encounter this in the new issue. You could also open a new issue or ask questions on [r/vieb](https://reddit.com/r/vieb).
