### ISSUE TITLE
proxychains vieb

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#126]
is it possible to run vieb through proxychains/tor? 
starting it with --proxy-server= is not possible

**Comment by Jelmerro** [comment]
I'm don't think it works, and I wouldn't recommend it. The [Tor FAQ warns against it](http://tor.void.gr/docs/faq.html.en#TBBOtherBrowser), so this won't be actively supported by Vieb, even if it would work. If you really want this, you'll have to figure this out yourself, but be warned that it won't offer the same protection as using the Tor Browser. Even the slightest deviation in the API, window size, useragent, you name it, will make using tor irrelevant, as you will be the in the minority of tor users that isn't using the tor browser, and thus you can probably be tracked as: "that user on the tor network who isn't using the tor browser". Hopefully you understand that it's unsafe to use something besides the tor browser to connect to tor if you don't precisely know what you are doing.
