### ISSUE TITLE
Right click menu appears when entering normal mode

### ISSUE THREAD

**Issue by Philipp0205** [Jelmerro/Vieb#127]
**Describe the bug**
Every time I follow a hint and vieb goes back to normal mode the right click menu appears where the hint was before. 
The right click menu does not disappear when the new page gets loaded. I need to press esc to hide it. 

**To Reproduce**
Follow links or exit hint mode. 

**Specs**
 - OS: Windows 10
 - Version: 3.4.0

**Comment by Jelmerro** [comment]
Can you share your current settings? I'm not able to reproduce it with my own settings or the defaults. Do you have other systems to try it on as well?

**Comment by Philipp0205** [comment]
Thanks for your anwer! 
I applied the default settings. No change. I should have mentioned that I am using the portable version. 
I will test it on linux and another win machine this evening.

**Comment by Jelmerro** [comment]
Using the portable version shouldn't matter, but it's odd that it happens when using the default settings. Maybe it only happens on Windows? I will try it on other machines here as well to see if I can reproduce on one of them.

**Comment by Jelmerro** [comment]
Okay, so this happens fairly reliable on Windows, I suspect that if you were to test it on Linux that you won't have this issue. Would be great if you could confirm that.

**Comment by Jelmerro** [comment]
I have updated the code to fix this issue, at least on the Windows machine I tested this solves the issue. If you know a bit about how to handle repositories with github, you could check out the `feature/v4` branch and check if it's also solved for you. Let me know if you have any questions about this.

**Comment by Philipp0205** [comment]
I can confirm that on the feature/v4 branch the issue is fixed. Thanks :)

**Comment by Jelmerro** [comment]
Good to hear. I plan to release V4 once electron version 12 becomes stable, which should be [begin march](https://www.electronjs.org/docs/tutorial/electron-timelines). Until then you can run it from source or make your own build (see `npm run` and the project readme for details).
