### ISSUE TITLE
Support for spellcheck of multiple languages simultaneously

### ISSUE THREAD

**Issue by TaPO4eg3D** [Jelmerro/Vieb#128]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Currently, `set spelllang` works differently from its Vim counterpart. Vim supports passing multiple languages as well as Electron.
I expect it to work like that: `set spelllang=ru,en_US`

**Comment by Jelmerro** [comment]
Totally agree, for some reason I missed this when implementing this setting. I see that you have already opened a PR for it, I'll leave my feedback on the code there. This feature should definitely be added to Vieb.

**Comment by Jelmerro** [comment]
This is implemented in https://github.com/Jelmerro/Vieb/commit/7b0e8adad86cc939680752d543389c717d1cd224 and will be released this week as part of the V4 release. Great to increase compatibility with Vim by improving the `spelllang` setting, so thanks for this suggestion.
