### ISSUE TITLE
Scoop package

### ISSUE THREAD

**Issue by run2cmd** [Jelmerro/Vieb#132]
**Addition or change**
Zip package that can be used by Scoop tool to install Vieb with checksum that can be used on each release.

I can create Pull Request to add that package to scoop extras bucket. Would it be stirght forward installation like unapck -> run?

**Comment by Jelmerro** [comment]
Sure, more installation options are always welcome. You can open a PR, but if you just need a portable zip for Windows I can add that to the builder config as well. Can I compare Scoop to Chocolately? Is a portable zip for Windows all you need to make it into a scoop package?

And to answer your question: it depends on the release type what steps are needed, but Vieb has two exe files for x64 Windows: one is a NSIS setup, the other one is a portable exe that can be ran immediately after downloading, no need to unpack/unzip anything for that. The Windows ARM release is just a zip indeed, so you would need to unpack that, but after that it's portable. I can add that same type of release for x64, but I figured we wouldn't need to (at least previously) as there are the two exe files already.

**Comment by run2cmd** [comment]
Yes Scoop in few ways is very simmilar to Chocolatey. I think that exe file would be enought if it contains everything what is needed. I'll work on that and update this thread

**Comment by run2cmd** [comment]
I've put [PR-5791](https://github.com/lukesampson/scoop-extras/pull/5791) to scoop-extras. However they recommend we do not put version in shortcuts. The recommendation is that there is `vieb.exe` file that would be linked to it. That file would allow also to add Vieb to PATH. @Jelmerro do you think this is possible. It could be zip with version number containing vieb.exe without version in it's name.

**Comment by Jelmerro** [comment]
That's kind of a weird limitation to be able to make a scoop package, but for adding it to the PATH I can see why it would be easier. Does [this](https://github.com/Jelmerro/Vieb/releases/download/4.0.0/Vieb-4.0.0-arm64-win.zip) suit your needs? Because this is the arm64 zip target of electron-builder, I can make a similarly structured zip for x64 for the next release.

**Comment by Jelmerro** [comment]
I also noticed that you listed Vieb as GPL3 only, but it's actually GPL3 and any later version. I'll update the docs to be more clear on this.

**Comment by run2cmd** [comment]
Yes. As long as it behaves as standalone for Win x64 then it would be perfect.

**Comment by Jelmerro** [comment]
Great, you can expect the next release to have a similar zip for x64 Windows. I'll probably make a new release before the end of this week, as there have also been a couple of bugs fixed recently that I want to get into a stable release.

**Comment by Jelmerro** [comment]
@run2cmd I think I got what you need right here:
https://github.com/Jelmerro/Vieb/releases/download/4.1.0/Vieb-4.1.0-win.zip

**Comment by Jelmerro** [comment]
Apparently they just want you to rename the downloaded file with `<url>#/vieb.exe` for example. I looked up an example for [Ferdi, another Electron app](https://github.com/lukesampson/scoop-extras/blob/a8bcb1b43b0230a9348a422017be31fe625cea70/bucket/ferdi.json). Seems like they also use this trick to conform to this weird scoop package format. Though for me that doesn't actually rename the download, but maybe scoop does some magic with it.

**Comment by run2cmd** [comment]
After testing it was better to use the zip package. With Vieb.exe file I had issues with links under Windows. The PR is already approved I hope it will be soon merged.

**Comment by Jelmerro** [comment]
The portable exe is just that indeed: a portable exe. I doesn't create links or anything, unlike the setup exe. So I think the zip is best suited for custom installations and packaging such as scoop. Glad that your PR was accepted in scoop-extras, hopefully they will merge it soon.

**Comment by Jelmerro** [comment]
It seems the PR was merged, so this should be available to scoop users soon.
