### ISSUE TITLE
[Feature] Make using native borders/window manager frames configurable

### ISSUE THREAD

**Issue by BachoSeven** [Jelmerro/Vieb#133]
If I understand correctly, `Vieb` is a "[frameless](https://www.electronjs.org/docs/api/frameless-window)" Electron app, which is achieved by hardcoding `frame=false` in [this](https://github.com/Jelmerro/Vieb/blob/52ada3d173629fa15b29dc45ed3bbb0f89f25092/app/index.js#L336) line.

While this gives the browser a somewhat minimalistic look, I would like to have native window borders as all the other windows in my window manager, since that way I can always see what window is focused by looking at the border color(I use `dwm`). This gets especially confusing since I also use `teams`, which halso hardcodes the same Electron option, and thus has the [same issue](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39231850-native-window-borders-and-header-in-linux-app).

Would it be possible to make this configurable?

**Comment by Jelmerro** [comment]
It's not possible to change the appearance of the window at runtime, once a browserWindow is shown, it either has or doesn't have a frame. Would a startup argument suffice to enable the frame (as in: `vieb --frame` or something)? Because then this could be as simple as adding a startup argument and toggling the frame option based on that.

**Comment by BachoSeven** [comment]
A startup argument is tricky since the browser could be started by another application through `xdg-open` and `.desktop` files. Do you think that an Environmental Variable could be used for this instead(so that it can be set for the whole session)?

**Comment by Jelmerro** [comment]
Yeah, that could work as well, though I wonder where to document such a feature. Currently Vieb doesn't make use of envvars. How about a startup argument that mentions that it can also be set by an envvar? Maybe this is also nice for (some) other startup options actually and it would be like an extra section at the end of the `--help` docs.

**Comment by BachoSeven** [comment]
That sounds very reasonable; and having both environmental variables and startup arguments is also often useful to override the former with the latter(although that's perhaps not the main point here).

**Comment by Jelmerro** [comment]
Overriding is not the main point indeed, but it could be supported. Though most current arguments are only toggles to deviate from the default behavior and they don't accept values to set something to false/true. Maybe this could be changed to allow for the override, but I think that's beyond the scope of this feature.

I would say that for now, if either the envvar OR the option is passed to Vieb, it will enable the feature/flag (i.e. frame, software-only etc). Would that work for your use case?

**Comment by BachoSeven** [comment]
Yes, having an environmental variable for the frame would work for me.

**Comment by Jelmerro** [comment]
Let me know if [this](https://github.com/Jelmerro/Vieb/commit/fac4085505b701ec3da320c060b66288358cdd3d) is what you had in mind. If so, feel free to close the issue again :wink:

**Comment by BachoSeven** [comment]
I just built from master and it works as expected. Thank you! :)

**Comment by Jelmerro** [comment]
You're welcome, glad that it works.
