### ISSUE TITLE
Cannot access insecure web sites 

### ISSUE THREAD

**Issue by run2cmd** [Jelmerro/Vieb#134]
**Describe the bug**
Cannot enter site with invalid/expired SSL certificate and no HTTP. With `redirecttohttp` enabled I get redirected to HTTP but there is only HTTPS available. With `redirecttohttp` disabled I get error about invalid certificate and cannot get to site anyway.

**To Reproduce**
I used following method on Windows 10 WSL

1. Generate self signed certificate. Plenty information on internet. I've used [this method](https://docs.bitnami.com/installer/infrastructure/wamp/administration/create-ssl-certificate-apache/)
2. Configure Web Server(Apache) to use those certificate files
3. Start local Web Service (like Apache) on both port 80 and 443
4. Open Vieb and navigate to https://localhost

**Expected behavior**
There should be warning that page is insecure and have possibility to access anyway. This should apply for both options with and without `redirecttohttp` set.

**Specs**
 - OS: Windows 10
 - Version: 10.0.18363

**Comment by Jelmerro** [comment]
As you found out, this is not what the `redirecttohttp` option is for. That can be used to redirect to http when https fails, but that's not what you want it to do in this case. The failed site is not something that Vieb causes, but is an Electron event that Vieb acts on to show this page. Specifically, [this](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-did-fail-load) event is used to check for pages that couldn't be loaded. This is the default behavior of Electron and Vieb. These links might be of help to understand possible solutions/workarounds:

- https://github.com/electron/electron/issues/6222#issuecomment-228273878
- https://github.com/electron/electron/blob/master/docs/api/app.md#event-certificate-error
- https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-certificate-error
- https://github.com/electron/electron/blob/master/docs/api/app.md#appimportcertificateoptions-callback-linux

Just to be clear, Vieb will continue to block insecure websites like these, but maybe we could listen for certificate errors (see the 3rd link) and allow this check to be overwritten by the user. The addition of custom certificates is only supported on Linux it seems (see the 4th link).

**Comment by Jelmerro** [comment]
You can now choose to connect to insecure sites using the permissioncertificateerror permission, for which you can find help using `:help permissioncertificateerror` in the new 6.0.0 release. As with other permissions, it's also possible to add automatic rules for allowing or blocking them using `:h permissionsallowed` and `:h permissionsblocked`.
