### ISSUE TITLE
Some html5 player related feature requests

### ISSUE THREAD

**Issue by ByJumperX4** [Jelmerro/Vieb#137]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
There is some problems in vieb while playing videos using the default HTML5 player that we can't have using, for example, firefox:

-We can't set default volume of it, or at least I couldn't find a way to do it. It would be even better if the player was able to remember the last volume used. Firefox haves a setting in about:config.

-It's impossible to enable replay for html5 videos, it shows the regular right click menu of Vieb instead

**Comment by Jelmerro** [comment]
I am not sure of it's possible to automatically set the volume of audio and video tags when loading them. We might have to add more listeners to the page to set it when the `onload` event fires. We could add a setting for `videovolume` and `audiovolume`, which accept a number (0-100) or can be set to `s:remember`.

As for the right-click menu, there should be options added to interact with the video and audio tags, similar to images. Keyboard bindings should also be added to download/copy/open video/audio sources in the form of actions. I think the video controls could also be part of this addition.

**Comment by Jelmerro** [comment]
Support for default volume and interaction with the media elements will probably be added in the future, but it's now possible to navigate or download video and audio sources from the context menu.

**Comment by Jelmerro** [comment]
Actions and menu options for interacting with video and audio elements have been implemented, all that's left to completely solve this issue is to implement a system to control the volume of media better.

**Comment by Jelmerro** [comment]
Is this still a concern now that media does not autoplay by default?

**Comment by Jelmerro** [comment]
As a last addition I have just added "p.mediaUp" and "p.mediaDown", so you can control the volume with the pointer or the menu. You can now control the media volume/sounds by: controlling autoplay (which is disabled by default), muting with pointer actions, muting with the context menu, changing the volume with these actions, the context menu options, the audio/video element on the page, the vieb application volume and the operating system volume mixer. This seems like enough options to me to change the volume level to something comfortable, so this has convinced me to close this issue as done. Feel free to open a new issue with more details as to what use case the options above are not enough for.
