### ISSUE TITLE
Can't sign into Google

### ISSUE THREAD

**Issue by python-clojure** [Jelmerro/Vieb#138]
I couldn't sign into Google. It says that the browser may be *insecure*. 
![image](https://user-images.githubusercontent.com/49131888/113320525-38777c00-9330-11eb-91f9-c3f77a6ac8e9.png)

This is what is said in the `Learn More` link

> Sign in with a supported browser
> To help protect your account, Google doesn’t let you sign in from some browsers. Google might stop sign-ins from browsers that:
> 
> Don’t support JavaScript or have JavaScript turned off
> Have unsecure or unsupported extensions added
> Are being controlled through software automation rather than a human
> Are embedded in a different application

**Comment by Jelmerro** [comment]
There is an entry in the FAQ that addresses this, clearly you didn't read it as you wiped the issue template. Please read it along with search existing documentation before opening duplicate issues. In short, enable `firefoxmode` to fix this.

**Comment by python-clojure** [comment]
Oh, I apologize for that

**Comment by Jelmerro** [comment]
It's okay, just make sure to take it in account next time :wink:
