### ISSUE TITLE
Some elements can't be clicked by follow mode in the latest release

### ISSUE THREAD

**Issue by python-clojure** [Jelmerro/Vieb#139]
YouTube full-screen option is available and the video plays in full mode only if the full-screen option is "clicked". It says the following when the following is done
`f` and `<key(s) to be pressed for full-screen>`
![image](https://user-images.githubusercontent.com/49131888/113325440-0ff28080-9336-11eb-8222-6e3abc69661a.png)

In Google Apps, I can't trigger the Apps (that 9-squares) to get a dropdown using follow hint `f`

**Comment by Jelmerro** [comment]
I have noticed similar related issues in follow mode when using the latest release. I made a bunch of changes to improve the input element focus, but those are a downgrade in functionality for other type of elements, such as buttons or JS listeners. The next release is going to fix this.

As for the dot menu, some of those require constant mouse hover to work. This is bad for accessibility, and is mentioned in the help documentation of Vieb as something that can be fixed. In short, try pointer mode or if all else fails use the mouse. Sites like that have many more things that are broken for non-mouse users that are up to the site to fix, which most of the time they won't sadly.

**Comment by python-clojure** [comment]
Of course this is related to the same problem as above. Just mentioning it. I can't use the follow mode for social authentication i.e. they must be clicked. The website I was in : [Scotch](scotch.io) -> Tried to login using GitHub and it didn't work.

Just now noticed your comment. Thanks a lot for that. I will wait for the next release.

**Comment by Jelmerro** [comment]
Should be fixed in the latest 4.3.0 release.
