### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by python-clojure** [Jelmerro/Vieb#140]
Scrolling using `j` and `k` are not smooth in some webpages for example

[Deno Land](https://deno.land/x/opine@1.2.0)

Pressing `j` without release is not as smooth as the same key pressed without release in this webpage [Deno Scotch](https://scotch.io/tutorials/build-your-first-deno-app-with-authentication)

**Comment by Jelmerro** [comment]
See `:h scrolling`. Pointer mode scrolling is smooth, while regular scrolling isn't. There is not much that can be done to change this, as it's related to how the scrolling is executed.
