### ISSUE TITLE
Close multiple tabs

### ISSUE THREAD

**Issue by ByJumperX4** [Jelmerro/Vieb#142]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
it would be great if Vieb was able to close multiple tabs at once, like we can do in Firefox/Chrom{e,ium} with right click > close others tabs, tabs on right (would also be nice to be able to close tabs on left).

Some commands like `rclose` to close on right, `lclose` for left, `closeothers` would also be nice

**Comment by Jelmerro** [comment]
You can combine all actions that are marked as "countable" with a number. For example, `5d` will execute "closeTab" 5 times. I you switch to the right tab before doing this, you suggestion can already be done. Or do you have something else in mind?

**Comment by ByJumperX4** [comment]
I mean, close all tabs that are on the right of the current tab, like right clicking on a tab in any popular browser

**Comment by ByJumperX4** [comment]
![image](https://user-images.githubusercontent.com/48773926/113421920-2519ee80-93cc-11eb-9de6-1fb90f58487a.png)
This in firefox

**Comment by ByJumperX4** [comment]
![image](https://user-images.githubusercontent.com/48773926/113422263-a8d3db00-93cc-11eb-998d-211eab0f6786.png)
On this picture, I'd like a way to close every tab I underlined in gree, another one for the red ones, and one that does both

**Comment by Jelmerro** [comment]
This seems like a nice addition. I will work on adding `:rclose` and `:lclose` this weekend. Though the `closeothers` command is just a combination of the two, so you can simply do `command closeothers <:rclose><:lclose>` when rclose and lclose are available, or the more Vim-like version, which only works if you keep the default mappings a bit intact:
`command closeothers <Esc>:rclose<CR>:lclose<CR>`

**Comment by ByJumperX4** [comment]
Nice ! :D

**Comment by Jelmerro** [comment]
Added and released in 4.3.0
