### ISSUE TITLE
Bookmarks bar

### ISSUE THREAD

**Issue by ByJumperX4** [Jelmerro/Vieb#145]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
I'd like to see a traditional bookmarks bar like you can find in others browsers, because having your favorites on the new tab page takes a lot of space and you have to scroll to go to the one you want. it would be a bar that is toggleable, containings favorites with webiste icon + custom name. Every bookmark would be clickable but also possible to open with a command, for example, `:openbookmark 1` would open the first bookmark.

**Comment by Jelmerro** [comment]
While it's not a direct duplicate, I would like to merge this with the [existing bookmark issue](https://github.com/Jelmerro/Vieb/issues/100). I was planning on writing a comment there with a list of expected features for a potential PR related to bookmarks. I'll make sure the bookmark bar is one of the features listed there :+1:
