### ISSUE TITLE
Custom bookmarklet

### ISSUE THREAD

**Issue by romariorobby** [Jelmerro/Vieb#149]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [X] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

is there an equivalent of qutebrowser config `config.bind("<Ctrl-r>", "open javascript:location.href='org-protocol://roam-ref?template=r&ref='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)")
` in vieb or isn't supported ? . i tried to use this for [org-roam](https://www.orgroam.com/manual.html#The-roam_002dref-protocol)

**Comment by Jelmerro** [comment]
So these are actually several questions, I'll try to answer them one at a time.

## Mappings/Keybindings

Vieb's mappings are mostly identical to Vim, as we use map commands to change the keybindings. While in Vieb, you can do `:h mappings` to see the full list of `:map` commands and the differences between Vim and Vieb.

## Bookmarks

Vieb does not have bookmarks at this moment. There is an [overview ticket](https://github.com/Jelmerro/Vieb/issues/100) which contains discussions about how the bookmark feature should work in Vieb. I summarized my current view on this in the most recent comment in that thread, but there is no such feature currently in Vieb. The closest we have now are `favoritepages`.

## Org-roam

I haven't heard about this, but a quick look suggests that it's some kind of custom protocol to edit local files based on page title and url. This is not implemented in Vieb, but I think you can achieve something similar using `externalcommand`. With this, you can open the url of a page with an external program, this could be set to one the org-roam tools, but any program that accepts arguments can be connected like this.


While it isn't currently implemented to connect or integrate with this org-roam stuff, you can hook up any external program to Vieb using the `externalcommand` setting, so I would recommend to first check if that is sufficient. Meanwhile I want to redirect all bookmark-related discussion to #100. Though feel free to ask any questions here if you still have them.

**Comment by Jelmerro** [comment]
I hope to have answered your question properly, but without a response this is not a ticket that can be worked on or implemented. Let me know if the existing solutions work for you or if this should have been a feature request instead. I'll close it for now, feel free to ask additional questions or even reopen the issue if there is something that Vieb needs work on.
