### ISSUE TITLE
Option to close Vieb when last tab is closed

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#154]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
An option to make Vieb exit the application when the last open tab is closed (something like "tabcloselast"). "closing" the last tab and getting a new tab can be confusing. I understand that this is good for preventing users from accidentally quitting the browser, but as long as they know the risk, this could be an option that makes closing the browser a bit more convenient.

**Alternatives considered**
Just using `:q`: This works fine, but tapping `d` just seems more intuitive to me. I'm not saying this option should be the default, but it would be a nice option.

**Comment by Jelmerro** [comment]
I like this option, I will probably work on this soon.

**Comment by Jelmerro** [comment]
This was a lot easier than expected and I have implemented it in [this commit](https://github.com/Jelmerro/Vieb/commit/7a311bf04a9ba63ba86f73d92a23988f6e365101). You can test it if you build from source, or wait for the next stable release.
