### ISSUE TITLE
Exposing Vieb variables to external scripts

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#155]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
It would be nice to use variables from Vieb in scripts when it is running. Right now the only thing I could find that external scripts could access is the `windowtitle`. It would be nice if you could run scripts that relate elements of the browser to the computer.
For example, Qutebrowser can run scripts from within the browser that read and write to the browser using [environment variables](https://qutebrowser.org/doc/userscripts.html#_getting_information). This allows you to, for example, make a script that enters follow mode and writes the selected link to an external file.

**Alternatives considered**
The closest thing I could find to this is Greasemonkey, but it seems like this only makes changes within the browser and cannot make changes on the rest of the computer.

**Comment by Jelmerro** [comment]
This could be added, but it's not possible to use environment variables for it, as you can have multiple windows of Vieb if you use the datafolder argument. This means it's not clear which instance of Vieb should read/write the env vars. An alternative would be to add new startup arguments for this type of basic interaction with Vieb. Does that sound like a possible solution or do we need something else?

**Comment by ottopiramuthu** [comment]
Qutebrowser runs these scripts with a `:spawn --userscript {scriptname.sh}` command. This way, when you run the script in one instance it will only use the environment variables from that instance. Maybe this could be a way to use environment variables in Vieb when multiple instances are open. What kind of startup arguments did you have in mind? I'm just a bit confused how arguments could help with interaction via scripts.

**Comment by Jelmerro** [comment]
If you supply the datafolder argument together with this new way of interacting with Vieb it can know which instance to target, for example for getting a value/setting:
`vieb --datafolder /tmp/example/datafolder --get-val 'CURRENT_URL'` or something like that (with better names).
But I think that I misunderstood how the environment variables are used in qutebrowser, because it's actually running a script and passing the values to the script using them, so that is something entirely different from what I initially understood. I thought this was just a completely separated script or program that could read and potentially write things to the currently running Vieb/qutebrowser instance by reading and writing env vars that are always kept up to date for the scripts to read and modify. I'll think about how qutebrowser does it and if this would work for Vieb, or if we sould just allow the CLI to interact with these values like I suggested. What do you think?

**Comment by ottopiramuthu** [comment]
I see what you mean by the startup arguments. That is a nice solution if you only want to run these scripts from outside the browser. I especially like that it seems like these scripts could be run even when Vieb isn't open (e.g. `CURRENT_URL` would be stored somewhere in the datafolder, so a simple script like `notify-send $CURRENT_URL` would just use the last url that was set. The only thing that I would miss from this approach is the ability to run a script like this from within Vieb, so I a can make it a mapping.

**Comment by Jelmerro** [comment]
Maybe for that we could add Vim's ! prefix for commands to run shell commands (see `:h :!` in Vim). That also makes it possible to run a wide range of other things directly from Vieb. Though this would probably need variables inside Vieb as well to be really useful, but that might warrant a separate ticket if we decide to go with this implementation.

**Comment by ottopiramuthu** [comment]
The `:!` syntax sounds good to me. Nice and short. I don't see much use for variables inside Vieb right now, but that doesn't mean they won't become useful in the future :)

**Comment by Jelmerro** [comment]
Partially implemented in the new release, the `:!` syntax is there, but no startup arguments to read the values yet. This will be added in the future, but not soon. Feel free to pick this up in the meantime if you wan to.

**Comment by Jelmerro** [comment]
Please see #517 for the future of this ticket. It is not dropped, far from it: it has finally had some proper thought as to how this could be best implemented, and soon will be, in the form of a new CLI flag as described in #517. This just means this old tracking ticket will be closed as the new one has more up to date info.
