### ISSUE TITLE
<action.clickOnSearch> not working on some Windows systems

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#156]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
The action "clickOnSearch" seems to not be working on Windows.
After searching for something and landing on a link , pressing Enter doesn't go to that link.
I tried adding a mapping ` nmap a <action.clickOnSearch>` to my viebrc and pressing `a` to click a searched link, but this doesn't work either. 

**To Reproduce**
- add `nmap <CR> <action.clickOnSearch>` to your viebrc
- go to the help page with `:h`
- `/clickOnSearch` and press enter
- `n` until you find the first link to that section of the page
- Press Enter - nothing happens

**Expected behavior**
I expect to go to the link I have searched for when I press Enter since I have `nmap <CR> <action.clickOnSearch>` in my viebrc.
In this case it would jump to the "action.clickOnSearch" section of the help page.

**Specs**
 - OS: Windows 10
 - Version: Vieb 4.4.0

**Comment by Jelmerro** [comment]
I can't reproduce this, for me these exact steps work on Linux also on version 4.4.0, so maybe this really is a Windows only issue. I'll check again on Windows in a bit an let you know. Do you have the option of checking it on other systems as well?

**Comment by Jelmerro** [comment]
I also can't reproduce this on the Windows system here, so I don't actually have a way to reproduce this. Could you try the 4.1.0 release on your Windows system to see if this action does work in that version? I changed the code a bit in 4.2.0 so if it works in 4.1.0 and not in any release after I can at least pinpoint the change where this breaks it for your machine.

**Comment by ottopiramuthu** [comment]
It doesn't work for me with 4.1.0. It must be an issue with my Windows then. I used the .exe releases for both 4.4.0 and 4.1.0 versions. Let me know if you need any more info.

**Comment by Jelmerro** [comment]
At least we know it's not related to the improvements I made since that release, so it must be something more specific to your system I think, but it's hard to track down if we don't know what's causing it. Is there anything in the page devtools (`:devtools`) or the internal devtools of Vieb (`:internaldevtools`) that could explain this issue?

**Comment by Jelmerro** [comment]
Also, a thing to note, the default mapping for this action is `<CR>`, so you don't need to add it yourself. Although that isn't related to the problem you are experiencing, but I wanted to let you know. Unlike Vim, you can list default mappings with the map command by appending a `!` to the map command: `:map! <CR>` for example. I'm very interested to know if there is anything in the developer console I mentioned in my previous comment.

**Comment by ottopiramuthu** [comment]
I haven't used `:devtools` or `:internaldevtools` to debug anything before. Is there something specific I should be looking for? I  found what seems to be some functions from the source code in Elements->Event Listeners but don't know where to go from here.

**Comment by Jelmerro** [comment]
There should be a `console` tab in the developer tools, you can first check for errors there (if any). The `:devtools` is what happens inside the webpage, and is also where the click is actually executed. The `:internaldevools` is for inspecting everything that happens on the Vieb application layer, so for example sending the signal to the page to execute the click when you press `<CR>`. For normal use you probably don't need either of these developer options, but I'm interested if there are any errors in the console tab, which lists all uncaught errors in red.

**Comment by ottopiramuthu** [comment]
I have an interesting development. This bug might have something to do with how pages are rendered.
On [this site](https://www.vitalyparnas.com):
 - search `/The`, 
 - `n` until focusing "The Springtime Sonnet"
 - Press Enter
 - Opens https://vitalyparnas.com/books/divine-comedy/, which is a link below the selected link.
 - When click "The Springtime Sonnet", it goes to the correct page (https://vitalyparnas.com/posts/springtime-sonnet/)
Maybe Vieb is "clicking" incorrectly a bit below the selected link, so of course it misses the link location and doesn't work.

**Comment by Jelmerro** [comment]
Some kind of scroll issue is very much possible, as for some reason Electron (the base framework of Vieb) returns the position of the link before the page is scrolled, so I manually update the position to match the scrolled position of the page. I improved the system for this in the 4.2.0 release, which is why I wanted you tot test 4.1.0 earlier. Sadly you also have this issue with the previous version, so it's not related to the changes I made, but has been an issue on that system for much longer. The weird thing is that I can't reproduce it anywhere and neither can @theolice apparently. Even for the new example you listed I get the correct link clicked on when I press `<CR>`. Do you have any other setting enabled, perhaps the window frame? It's interesting how it's only slightly out of sync with the actual position, I would expect it to either error out or be completely wrong and not find a link at all.

While I'm not concerned about potentially recursive mappings (like @theolice), I am curious what kind of settings you have applied when running on that machine. Is it the same config file as when you tested on Ubuntu?

**Comment by ottopiramuthu** [comment]
My viebrc is [here](https://gist.github.com/ottopiramuthu/78af3125d41abab142c1a6dc6fef057e) and my custom CSS is [here](https://gist.github.com/ottopiramuthu/0215aeacc174887fb178595b67b979fb). Those are all the custom settings I have.
I tried on Ubuntu again with my viebrc and it still works fine there.
What setting do you mean by the window frame? On Windows I have window decorations for other programs, but Vieb seems to not have any (no minimize, restore, close buttons). On Ubuntu I am using AwesomeWM with only a 5px window frame for all programs.

**Comment by Jelmerro** [comment]
There is a `--window-frame` startup option, I was curious if you have that enabled on Windows, but if you don't know about it I don't think that's it. I don't see anything odd in your configuration that could cause this at all. Was there anything in the developer console, or was it empty? If not, I don't know what else to try :slightly_frowning_face:

**Comment by ottopiramuthu** [comment]
I've looked at `:devtools` and `internaldevtools` and found no errors in the console (both were empty).
I never ran Vieb from a terminal (clicked the desktop shortcut instead), so I don't think I changed anything with `--window-frame`. Is there a way to check the option from within the browser?

**Comment by ottopiramuthu** [comment]
Resetting the zoom didn't help, but that's a big issue. Glad that was found. 
I tried running Vieb with `--window-frame`, but I get the exact same issue. Same offsets for where the links are and what is clicked.

**Comment by theolice** [comment]
@ottopiramuthu I just tried running Vieb with your viebrc and colorscheme, but I couldn't reproduce the issue with the `action.clickOnSearch`

**Comment by ottopiramuthu** [comment]
@theolice I see now `z0` doesn't work on my system either. Vieb is probably interpreting `0` as a count as I have tried the mapping `z2` and that doesn't work either. 
With a new working mapping and a reset zoom I am still getting identical results from when I tried the site [earlier](https://github.com/Jelmerro/Vieb/issues/156#issuecomment-822809753)

**Comment by Jelmerro** [comment]
I'll work on a fix for the mapping issue as well, that one seems like an easy fix. But I have no other things to try for you to make this action work. I'll fix the zoom and mappings issues and make a build for you to try it with, which hopefully fixes this weird alignment issue as well.

**Comment by Jelmerro** [comment]
Can you check again if you have this problem based on the latest source code or [this build](http://jirafeau.net/f.php?h=0-n7QTpI)? I pushed a bunch of commits that should fix all issues we discussed above.

**Comment by ottopiramuthu** [comment]
Thank you, this build works! :)

**Comment by Jelmerro** [comment]
Great to hear, the next release will obviously also include these fixes.
