### ISSUE TITLE
Copy and paste on macOS?

### ISSUE THREAD

**Issue by bromanko** [Jelmerro/Vieb#158]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
I am attempting to use Cmd+C to copy selected text. It does not work. I can't seem to find any way to yank selected text to the OS clipboard. Am I missing something?

**Steps that have been attempted**
* Highlight text in Normal/Insert mode. Press Cmd+C. Nothing is copied.

**Comment by theolice** [comment]
You have to be in Insert/Pointer/Visual mode to be able to copy text.

When in Normal mode, I'm unable to copy selected text as well.
But when I'm in Insert I'm able to use `CTRL`+`C` on selected text.
In Pointer/Visual mode I'm able to use `nmap y <action.pageToClipboard>` to yank selected text.

Are you sure you're in the correct mode when trying to copy your selected text?

**Comment by Jelmerro** [comment]
For selected text on the page to be copied you need to be either in visual or insert mode. From visual mode you can copy with `y` and from insert the regular keyboard bindings from you operating system should work if you don't add a mapping to replace them.

**Comment by bromanko** [comment]
Ahh! My mental model was off on this. That explains it. I didn't properly explore visual mode. Thanks!
