### ISSUE TITLE
Quit actions from the operating system don't work

### ISSUE THREAD

**Issue by bromanko** [Jelmerro/Vieb#159]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
I am running Vieb 4.4.0 on macOS (Big Sur 11.2.3) on an M1 Macbook. Using the Quit item in the menu bar has no effect.

**To Reproduce**
* Launch Vieb
* Click Quit in the menubar (or press Cmd-Q)

**Expected behavior**
Vieb should quit

**Specs**
 - OS: Big Sur 11.2.3
 - Version: 4.4.0

**Comment by Jelmerro** [comment]
Currently it's not possible to differentiate between close requests from the OS and user requested close actions, and as such they are mapped to `<M-q>` on mac and to `<A-F4>` on other platforms. By default these combinations aren't mapped, but you can add a mapping for `<M-q>` to make this work using `:nmap <M-q> :qa<cr>` or the Vieb specific: `:nmap <M-q> <:qa>`.

Given the flood of issues about this topic recently I'll leave this open till I find a solution to distinguish between close actions from the OS and just pressing `<A-F4>` or `<M-q>`.

**Comment by Jelmerro** [comment]
Implemented in [V5](https://github.com/Jelmerro/Vieb/releases/tag/5.0.0). Vieb can now by default be closed by system actions, because `<A-F4>` is now mapped. You can unmap it to get back the old behavior, but system close actions won't work if you unmap it.
