### ISSUE TITLE
Special characters in commands should do the same thing they would do when typed in the navbar.

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#160]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Make special characters like `<Home>`, `<End>`, and `<Right>` do the same thing they would do in the navbar when they are run as a command.
For example, with the mapping `:map ge <action.toExploreMode><End>`, if "ge" is pressed, explore mode should be entered and the cursor in the navbar should move to the far right, deselecting the url. 

A list of special characters to implement:
- `<Home>`, `<End>`
- `<Left>`, `<Right>`
- `<Ctrl-Left/Right>` (moves by words instead)
- `<Ctrl-x>`(cut), `<Ctrl-c>`(copy), `<Ctrl-v>`(paste)
- `<Insert>`
- `<Del>`, `<BS>`

**Alternatives considered**
Splitting commands and typing the special characters manually works, but it is tedious.

**Comment by Jelmerro** [comment]
I would the the "etc." in you comment to be a bit more concrete. Which keys should we add? Cut, copy, paste, home, end, left and right, but are there others? Let me know, I'll probably pick this up tomorrow.

**Comment by Jelmerro** [comment]
It seems that `<Insert>` isn't actually working even used regularly, I doubt that input fields actually support insert at all. I couldn't find much info about it, but it seems like this isn't actually part of any web standard (at least not anymore):
- https://github.com/w3c/editing/commit/89a2a4621509b77f5032a0b3e562b3e7db3adfcd

**Comment by ottopiramuthu** [comment]
If `<Insert>` isn't possible to me it's not a problem. I'm not sure `<Ctrl-Left/Right>` is possible with you implementation, but it saves a lot of time when I need to use arrow keys.

On another note, would it be possible to add some of the [readline](https://en.wikipedia.org/wiki/GNU_Readline) equivalents to these actions in the navbar, like `<C-a>`, `<C-e>`, `<C-f>`, `<C-b>`, `<A-f>`, `<A-b>`, `<C-h>`?

**Comment by Jelmerro** [comment]
It will be possible once this issue is solved. Movement in the navbar will probably end up being implemented as regular actions that are by default mapped in a similar way to regular text boxes, so that by default you won't notice much difference (hopefully none). Though it will take a while to implement all the different movements and quirks of regular typing as actions.

**Comment by Jelmerro** [comment]
You can check my [latest commit](https://github.com/Jelmerro/Vieb/commit/5067ec765c8287efea7fd127868c383c0d50b283) for some progress on this issue, it's still lacking some basic shortcuts, but most functionality mentioned here should work already.

**Comment by Jelmerro** [comment]
This has been fully implemented now. I might rework the keys into actions eventually, but they can now be mapped to the existing keys and be used inside other mappings. Ideally, you won't notice a difference besides the support for using the keys inside mappings.
