### ISSUE TITLE
`o` command in visual mode

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#161]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add a command like `v_o` in vim to swap the pointer to the other side of a selection in visual mode.
**Alternatives considered**
Redrawing the selection takes too much time.

**Comment by Jelmerro** [comment]
Implemented in [V5](https://github.com/Jelmerro/Vieb/releases/tag/5.0.0).
