### ISSUE TITLE
Vieb continues scrolling if a scroll by mouse is interrupted with a scroll command

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#164]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When scrolling with a mouse, typing a scroll command like `gg` or `G` does not reset the scroll speed. 
The page keeps on scrolling after the scroll command is executed.

**To Reproduce**
- Go to the help page (`:h`).
- Start scrolling quickly down using the mouse.
- While the page is scrolling, press `gg` and stop scrolling with the mouse.
- You go to the top of the page, but the page is still scrolling downwards, so it doesn't stay at the top.

**Expected behavior**
After you press `gg` the page should go to the top and _stay_ on top.

**Specs**
 - OS: Windows
 - Version: Vieb 4.5.0-dev

**Comment by Jelmerro** [comment]
I can't reproduce this, do you perhaps have one of those resistance-free scrollwheels that keep going for a while? If not, I don't think Vieb can actually override or even stop mouse actions when they are already being executed, but I'll search for it.

**Comment by ottopiramuthu** [comment]
I am using a trackpad and swiping up/down with two fingers. With this the page still scrolls a bit after I swipe and that "momentum" doesn't stop when I press `gg`. If this is not fixable it's not big deal. I'm just bringing this to your attention.

**Comment by Jelmerro** [comment]
I just tested with a trackpad, but it's also not reproducible here. My guess would be that it's actually still scrolling a bit when you execute `gg`. Maybe you could check your trackpad settings for smooth scrolling or something and check if that changes the behavior? Also, do you have the same issue when scrolling and pressing `Home` in regular browsers like Firefox, or do they not have this issue?

**Comment by ottopiramuthu** [comment]
On Vieb, Chrome, and Firefox, I get the same "momentum" when I scroll in the opposite direction of the scroll command (e.g. scroll down with trackpad and press `Home`). This must be an issue on my end then. I'll close this issue for now.
