### ISSUE TITLE
Spelling suggestions in insert mode

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#165]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Some browsers give spelling suggestions when you right click text boxes with misspelled text. 
![image](https://user-images.githubusercontent.com/49997309/115973665-ca843600-a524-11eb-9865-176ec454d099.png)

It would be nice to have a similar feature with Vieb's text boxes. To make this more vim-like, `<C-x><C-k>` could be used instead of right click.

**Alternatives considered**
Just spelling correctly. I make too many typos.

**Comment by Jelmerro** [comment]
This only recently became possible, but will definitely be added in the future! (see [here](https://github.com/electron/electron/pull/25060))

**Comment by Jelmerro** [comment]
This has been added in the latest commit, please try it out if you want to. It's part of the contextmenu, for which I made a new action and default mapping to open it. It's now also possible to combine the repeat counter (prefixed number to do an action more than once) with the context menu. So you can for example do `5<C-n>` to move 5 entries down in the context menu. I also added a new action to open the menu for the currently active element while in insert mode.

Please check the latest code or wait for the next stable release which will include this new functionality.
