### ISSUE TITLE
Bring pointer to previous selection location for visual-mode

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#174]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
 I would like a command to bring the pointer to the end of the current selection (one that was previously made with the mouse). This would make the following kind of workflow a bit less annoying:
- select text before entering visual mode with the mouse
- try to go into visual mode to edit the selection
- oops! the pointer is somewhere else and restarts the selection

Say I have selected this text with my mouse, going from right to left (`o` to `t`):
![image](https://user-images.githubusercontent.com/49997309/116639015-84204400-a935-11eb-96a8-9e4772dd8345.png)
When I enter visual-mode, I want a command that brings the pointer to the place where I left the selection with the mouse (the `t`), so I can resume editing the selection in visual-mode:
![image](https://user-images.githubusercontent.com/49997309/116639167-dd887300-a935-11eb-8d4b-675dea2559a0.png)
I'm open to any other suggestions for improving the transition from selecting with mouse to editing that selection in visual-mode.

**Alternatives considered**
Selections work fine when you start moving in pointer mode and select in visual mode, but when the thing you're copying isn't near a link, selecting with the mouse is just faster. I want the transition from mouse selection to visual selection to be smoother, and a command to "resume" a selection made with the mouse in visual mode would solve this.

**Comment by Jelmerro** [comment]
I have implemented a setting for this, let me know if this solves your issue.

**Comment by ottopiramuthu** [comment]
Thank you, this works!
