### ISSUE TITLE
Adding "copy image (to clipboard)" and "copy image link (to clipboard)" functionality for images to context (right click) menu

### ISSUE THREAD

**Issue by theolice** [Jelmerro/Vieb#177]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Currently the [context menu](https://i.imgur.com/kQLPAv4.png) gives the following 3 options for images: `Navigate`, `In new tab`, and `Download`.  It is not possible to store an image (and/or its URL) to the clipboard like how it possible in other browsers (i.e. [Firefox](https://i.imgur.com/peQfYnL.png)).

There are some actions in which one would prefer to be able to copy the image (and/or its URL) to the clipboard and be able to paste it rather than downloading it and having said image locally. An example of this usage is sharing images within other applications like Telegram, Slack, or Discord either as images buffered in the clipboard or their direct links (e.g.: `https://i.imgur.com/peQfYnL.png`)

Adding the extra actions `Copy image` and `Copy image link` in the context menu would be helpful in reducing the amount of actions needed to be carried out for sharing images and the like.
Perhaps these actions could also be added as actions so they are usable in `Pointer`/`Visual` mode.

**Alternatives considered**
It may be possible to make a recursive mapping in the `Normal`, `Input` and `Pointer` modes in which the image gets downloaded or the URL gets put into the clipboard, however I doublechecked the [Help Page](vieb://help) and found nothing that could let me do anything with image links apart from immediately downloading the image.

**Comment by Jelmerro** [comment]
This should definitely be added. I'll add the "copy image url"  option myself on the V5 branch. The copy image link is easy enough, but I couldn't figure out how to copy the image buffer to the clipboard. PRs are welcome for that, hence the "help wanted" tag.

**Comment by Jelmerro** [comment]
I figured out how to do it at least for static images, gifs will just copy the current frame, but that's better than nothing.

**Comment by Jelmerro** [comment]
Implemented in [V5](https://github.com/Jelmerro/Vieb/releases/tag/5.0.0).
