### ISSUE TITLE
No autoplay of media when opening link in new tab

### ISSUE THREAD

**Issue by theolice** [Jelmerro/Vieb#181]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
When opening a link (a Youtube video for example) in a new tab with the MMB or via the follow mode it automatically starts loading the page and plays the video. This means you have to go through all newly opened tabs and mute/pause them manually if you plan on opening multiple links. Preferrably it would only start playing when you navigate to the page.

Example of current situation:
- Go to a [Youtube video](https://www.youtube.com/watch?v=_QKLr-JP26c)
- Click middle mouse button on 3 suggested videos
- They all start playing when loaded

Example of preferable situation:
- Go to a [Youtube video](https://www.youtube.com/watch?v=_QKLr-JP26c)
- Click middle mouse button on 3 suggested videos
- No videos/media starts playing until the tab is active by moving to it.

**Alternatives considered**
Manually pausing them, but that seems like more of a workaround than alternative.

**Comment by Jelmerro** [comment]
Would be nice, but not possible for now: https://github.com/electron/electron/issues/29064

**Comment by Jelmerro** [comment]
This has been implemented in the source as a startup argument (and has been set as the default), let me know if this solves your issue of annoying autoplaying videos.

**Comment by Jelmerro** [comment]
After using this for a few weeks when working on the new release I have yet to have a video play automatically, so I suppose this works. It has just been released in Vieb 6.0.0.
