### ISSUE TITLE
Customize characters used for follow mode hints

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#182]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
A setting to change the characters follow mode uses to select links.
For example, the following could be used to make follow mode only use some characters from the left side of the keyboard:
`set followchars=w,a,s,d`

**Alternatives considered**
I could not find an alternative.

**Comment by Jelmerro** [comment]
I'm going to close this one in favor of the other follow mode ticket, I believe the two are close enough to be bundled in one setting.
