### ISSUE TITLE
Arrow keys in insert mode

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#186]
**Checklist**
- [ ] I searched the `:help` documentation using `/` for helpful information
- [ ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**  Addition or change**
Is there a way to add arrow key or even better something like ctl+h l j k to navigate in insert mode?
many time I go back to my search to adjust the search term and find it annoying to search for my mouse to navigate in between two words to change or add it.

**Alternatives considered**
[TODO A description of alternative solutions or features you've considered, and why they don't suffice.]

**Comment by ottopiramuthu** [comment]
> I can't place it between "the | best" to enter WORLD.

You can use Ctrl+right/left arrow keys to move by word once you select the search box

> Arrow down moves the page down but I can't choose a suggestion without mouse

You can select search results with the up/down arrow keys and select them with `<Enter>`

**Comment by se7en-x230** [comment]
Okey ctrl arrow keys works thanks.

More vim natural would be h j k l w b $ 0 ...and easier on the workflow.

**Comment by ottopiramuthu** [comment]
If you want vim movement keys you can press Ctrl+i to open the text box in Vim. Check out `:h vimcommand` to change your editor.

**Comment by se7en-x230** [comment]
Yes I have set up editWithVim to write longer messages like that. 
But for plainly adjusting the search phrase invoking an external program is a bit of an overkill.

As ctl+arrrow keys are already set to navigate in a text field the question is now can I remap them.

**Comment by Jelmerro** [comment]
It's not possible with Electron to send "real" keyboard events to the page that aren't actually pressed. So while you would think it's possible to add mappings for this, they won't work on native elements such as input fields. This is also the reason that the latest releases have a completely custom navbar that isn't actually using the OS to move or type keys. So while these mappings DO work for the navbar, they can't work for input fields on the page. I normally would leave these open in the hope of an upstream fix, but the Electron team expressed that they don't think this is their responsibility. Your best option is using the vimcommand as mentioned.
