### ISSUE TITLE
`.` to repeat last action

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#187]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
A command that repeats the last action that works like `.` from Vim.
For example, I could press `d` to close a tab and then press `.` to close a tab again.

**Alternatives considered**
You can just press the same keys again, but `.` from Vim would be nice.

**Comment by Jelmerro** [comment]
Which modes should this action be present for? I was thinking just for normal mode, but maybe visual and pointer as well, just like the count?

**Comment by ottopiramuthu** [comment]
That sounds good to me. For command/explore mode there could be something like Vim's `@:`.

**Comment by Jelmerro** [comment]
I was thinking the same thing actually. The one for command mode seems actually possible without any new action, I'll try to add it using existing ones and make a new one if needed.

**Comment by Jelmerro** [comment]
Let me know if this current implementation is working as expected.

**Comment by ottopiramuthu** [comment]
It works as expected... Would it hurt to have a version for explore mode using `exploreHistoryPrevious`? Maybe it could be mapped to `g@:`?

**Comment by ottopiramuthu** [comment]
Just so you know, all of the examples so far that have a way to repeat actions use `.`. Pentadactyl is the only one that repeats commands, and it also uses `@:`. The examples won't need to be updated with the currently-planned mappings :)

**Comment by Jelmerro** [comment]
I think that if people want that, they can define that themselves in a similar way as the command version with a keybinding they find reasonable. They have the example of how to do it for commands. `g@:` would be a nice one, but it's also a bit too obscure for people to expect it to be there by default I think.

Good to hear that the functionality is the same for all examples. I'll close this issue since this works as expected for both of us.
