### ISSUE TITLE
Vim-like macros

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#188]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add commands to create macros (sequences of keystrokes) and execute them.
For example, I would be able to reload all tabs like this:
- `:buffer 0` to go to the first tab
- `qa` to start recording macro `a`
- `rJ` to reload the tab and go to the next
- `q` to stop recording
- `999@a` to reload the remaining tabs

**Alternatives considered**
Making a temporary mapping works, but macros are nicer.

**Comment by Jelmerro** [comment]
For what it's worth, I gave the `:call` command an upgrade in [this commit](https://github.com/Jelmerro/Vieb/commit/592b4a667206c703d5c1d0a187f5ae768ed0b685). It now accepts any action, command or basically just any mapstring and it will execute it immediately. It's not a replacement, but the next best thing until proper macros are implemented.

**Comment by Jelmerro** [comment]
Implemented in 9.7.0, see `:h record` for details.
