### ISSUE TITLE
action.BackInHistory

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#190]
The H key brings me back to the previous Webseite but not to the point where I left.

Is there a way to jump back the the previous page to the place where I left the page?

**Comment by Jelmerro** [comment]
The chromium engine already attempts to do this whenever possible. If it doesn't work on some of the sites, there is not much that Vieb can do to change this. It just calls the Electron API for going back in the browsing history. So If you can make it reproducible you might want to open an Electron issue. There is a feature request in Vieb that would make this less of a problem: https://github.com/Jelmerro/Vieb/issues/166
