### ISSUE TITLE
File sourcing

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#195]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add a command to source another file like Vim's `:source`.
This could be used in a viebrc to split the configuration into several more manageable files.
For example (first comment is the file name, and all files are in the same directory):
```
" viebrc
source settings
source mappings
source searchwords
colorscheme flipped
```

```
" settings
set adblocker=update
" ...
```

```
" mappings
nmap o <action.toExploreMode>
" ...
```

```
" searchwords
set searchwords=
set searchwords+=dd~https://duckduckgo.com/?q=%s
set searchwords+=i~https://duckduckgo.com/?q=%s&iax=images&ia=images
set searchwords+=gh~https://github.com/search?q=%s
" ...
```

**Alternatives considered**
As far as I can tell there is no alternative.

**Comment by Jelmerro** [comment]
I have implemented the `scriptnames` and `source` commands recently, be sure to check them out.

**Comment by ottopiramuthu** [comment]
This works as intended on Windows.
