### ISSUE TITLE
Opening a split is delayed and as such can't be used in mappings properly

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#198]
How do I set a follow action to open in a vsplit
I have tried 
`<:vsplit><openFromClipboard> `
but that pastes the URL into the original side and not the split.

**Comment by ottopiramuthu** [comment]
I tried this:
`nmap * <action.pageToClipboard><:vsplit><action.openFromClipboard><action.startFollowCurrentTab>`, but apparently `<action.openFromClipboard>` doesn't work with splits.

**Comment by se7en-x230** [comment]
I set it as pmap as nmap doesn't let me choose the link I want to open in the split.
But yes if I am not doing something wrong than the paste is not working.

**Comment by Jelmerro** [comment]
Please check the latest source code to see if this is resolved, or wait for the next stable release.

**Comment by se7en-x230** [comment]
Thanks for the fast response. 
It would be a nice feature to have opening links in split if you want to compare things...

I tried to build and get the following error.
Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment

System:    Host: pureArch Kernel: 5.12.7-zen1-1-zen x86_64 bits: 64 Desktop: dwm 6.2 Distro: Arch Linux

**Comment by Jelmerro** [comment]
That looks like an electron builder issue that happens when using node 16: https://github.com/electron-userland/electron-builder/issues/5862. It seems to be fixed when using the beta version of electron builder from what I read. I'll update it for the next release as well.

**Comment by Jelmerro** [comment]
As tested in #199, this works. The next release will include this fix, or you can build it from source.
