### ISSUE TITLE
Previous gray out if tab at the end of history

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#199]
Would it be possible to gray out the previous button in the menu if you reached the end of the history on the tab?
Also maybe a warning or notification if you use the keybindings.

Thanks

**Comment by Jelmerro** [comment]
I definitely understand graying out the button in the menu, but do we really need a notification for the action? You can see that the page doesn't start loading a different one easy enough from the tabbar, or even if you have that disabled, the fact that nothing happens should be clear enough that there isn't a previous page. Could you explain in a bit more detail why you think the notification would have additional information?

**Comment by se7en-x230** [comment]
Context menu gray out is something that sounds easy and sane to implement as "normal" browser have that clearly visible in the menu bar.

With hidden url and tab bar for maximum screen estate an indicator that this is the last history entry IF an easy to implement solution springs to mind.
Maybe even via the theme file just like I use the indicator which mode I am in that you provided for another user.

**Comment by Jelmerro** [comment]
I made a bunch of changes to which menu items appear in the context menu, let me know if this is better or not. I'm also curious to know if the build issue is fixed when you run the latest code, as I updated electron-builder to the beta version as well.

**Comment by se7en-x230** [comment]
Build just fine now 
and "previous" is not an option if reached the end of the tabs history. 

Nice

**Comment by se7en-x230** [comment]
Open link in split works also perfect 
[](url)https://www.dropbox.com/s/n94tq76hu2zd5dm/vieb-open-link-in-split.mp4?dl=0

Thanks a lot.

**Comment by Jelmerro** [comment]
Glad to hear that everything works now!
