### ISSUE TITLE
Github dropdown navigation

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#200]
![image](https://user-images.githubusercontent.com/69777713/120137420-7abd1c80-c1fe-11eb-99a9-f4933ebe2dd5.png)

Is there a way to navigate the Github search bar? 
I can't figure out how to select "All GitHub"  without mouse.

**Comment by Jelmerro** [comment]
This is not entirely Vieb related, but it seems that Github made the arrow keys navigate up and down the suggestions. I don't think there is much that Vieb can improve for these kind of menus that disappear when they lose focus, because it's not possible to map to system shortcuts in Electron.
