### ISSUE TITLE
Make `G` behave like in Vim when it has a count

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#204]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
In Vim, `5G` doesn't go to the end of the document 5 times, it goes to the fifth line. It would be nice to make `[number]G` scroll to the `[number]%` point in a page. 

P.S. `gg` works the same way in Vim. Maybe it should also be included.

**Alternatives considered**
I can't find any alternatives.

**Comment by Jelmerro** [comment]
The main reasons for this not currently being implemented, are as follows:

- I didn't know how I would translate the lines of Vim to the browser context. I like your suggestion of making this a percentage, that seems like a nice way to do it.
- The mapping system doesn't support switching to a different action if there is a action compared to when there isn't. We just reapply the same action x times to repeat for as many times as possible. Logically it doesn't actually make much sense that an action would change behavior just by repeating it, but I'm also aware that this isn't actually how Vim handles things, and I actually use `[number]G` a lot when editing in Vim. It's just that I'm not sure how to translate this concept to Vieb in a simple manner.

If you have any thoughs on this let me know, I don't really know what's best for this feature request.

**Comment by ottopiramuthu** [comment]
I got the percentage idea from Qutebrowser's `G`: [scroll-to-perc](https://qutebrowser.org/doc/help/commands.html#scroll-to-perc). I was learning a bit of emacs a while ago and it sometimes has different behavior for arguments when they are prefixed by numbers (see [this](https://www.gnu.org/software/emacs/manual/html_node/emacs/Arguments.html) for more detail). I don't know how emacs implements this, but their code might be of use to you.

**Comment by Jelmerro** [comment]
Implemented in https://github.com/Jelmerro/Vieb/commit/504f63400ef2b8057406bd797b14f46ad7680cb8, will be a while until the next release, but if you can run from source you can test it already.

**Comment by Jelmerro** [comment]
Released in 9.4.0! :tada:
