### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#205]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
It would be nice to have instructions for building Vieb from source in a convenient location. This would be helpful for people with less experience with Node.js/Electron. This could be an addendum to `FAQ.md` or maybe a separate file like `CONTRIBUTING.md`. I'm open to other suggestions.

**Alternatives considered**
New contributors can try to learn this themselves, but the learning process can be sped up with a set of instructions.

**Comment by Jelmerro** [comment]
I suppose you found the instructions in the readme by now :sweat_smile:? Let me know if this needs improvement.

**Comment by ottopiramuthu** [comment]
Yeah my brain just disappeared for a moment there XD
