### ISSUE TITLE
Increment/decrement the last number in a URL

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#209]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
A lot of sites have collections of pages that are numbered in the URL. It would be nice to have a command that goes to the next/previous page in such collections based on the last number in the URL.
For example:

```
:open xkcd.com/31
<incrementURL>
" now on xkcd.com/32
<decrementURL>
" now on xkcd.com/31
```

**Alternatives considered**
You can manually edit the URL but the suggested command would be quicker.

**Comment by Jelmerro** [comment]
Do you think that `action.increasePageNumber` does what you describe? Or is it different from that?

**Comment by ottopiramuthu** [comment]
I'm closing this as [this issue](https://github.com/Jelmerro/Vieb/issues/211) covers it.
