### ISSUE TITLE
Traverse the URL Hierarchy

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#210]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add a command to go up the URL hierarchy and a command to go to the root.
For example:

```
:open https://github.com/Jelmerro/Vieb/blob/master/app/pages/newtab.html
<goUpURL>
" now at https://github.com/Jelmerro/Vieb/blob/master/app/pages
<goUpURL>
" now at https://github.com/Jelmerro/Vieb/blob/master/app
<goRootURL>
" now at https://github.com
```

**Alternatives considered**
Manually editing the URL works, but this is quicker.

**Comment by Jelmerro** [comment]
I'm not sure if this is really needed, most websites should provide links for you to do this. Is it just added convenience to be able to navigate directly to the upper/top level of a website? Especially the root url should be easy to find on most websites. Besides, url edits can also be automated to a certain degree with recursive mappings and custom commands:
`command! goUpURL <action.toExploreMode><End><BS><C-BS><CR>`
`command! goRootURL <action.toExploreMode><Home><C-Right><C-Right><C-Right><C-Right><C-Right><C-Right><S-End><Delete><CR>`
Though in all honesty, these are site specific, fragile and really cumbersome to write and use, so maybe dedicated actions for it would actually be nice to add. I'll think about, but probably won't pick this up any time soon.

**Comment by ottopiramuthu** [comment]
command! goRootURL <action.toExploreMode><Home><C-Right><C-Right><C-Right><C-Right><C-Right><C-Right><S-End><Delete><CR>

It's mappings like this that make me think dedicated actions would be useful. I honestly wouldn't use these actions often, but most vim-based browsers/plugins have them bound to `gu`/`gU`.. and I'm just trying to fill in the gaps :)

**Comment by Jelmerro** [comment]
I agree, the more I look at these mappings and think about it, the more it makes sense for actions like this to exist.

**Comment by Jelmerro** [comment]
I also would like to add to the list of actions suggested above: an action for removing subdomains.

**Comment by Jelmerro** [comment]
I implemented these actions in [this commit](https://github.com/Jelmerro/Vieb/commit/8822516f2d33e09b64622ba88dde2995163b730c), let me know if they work as expected.

**Comment by ottopiramuthu** [comment]
They work as expected. I will check if any examples need changes to mappings.

**Comment by Jelmerro** [comment]
Good to hear, I'll close the issue since this is implemented, next release will include this.
