### ISSUE TITLE
Navigate to Next/Previous pages by pattern

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#211]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Many pages have next/previous links for browsing collections of pages.
I would like to navigate between these pages by using a binding that finds these links and follows them.

Tridactyl, for example, has a command `followpage` which accepts arguments `next` and `prev`.
There is also a `followpagepatterns` setting which allows users to customize the patterns the plugin looks for in pages.
This makes it easy to adjust the command to different languages:
```
set followpagepatterns.next ^(next|newer|prochain)\b|»|>>
set followpagepatterns.prev ^(prev(ious)?|older|précédent)\b|«|<<
```
Regex support for a `followpagepatterns`-like setting would also be nice

**Alternatives considered**
Clicking on these links works, but it is slower.

**Comment by Jelmerro** [comment]
In a way, `action.increasePageNumber` attempts to do this, but based on the page structure instead of custom selectors. Is this sufficient for the feature you describe, or do we need to improve this action? I do think we need more selectors by default to make the page increment work for more pages, but my question is more about whether we need new actions or need to fix the existing ones.

**Comment by ottopiramuthu** [comment]
It looks like `action.increasePageNumber` is enough for my common use-case..
I don't know enough about how you use the page structure to comment on whether custom selectors would be a significant improvement on what you already have.

I would want to "fix" the existing one by allowing some parts of the selection process to be customized.
Like I said, a common use-case for custom selectors is supporting different languages. 

It might be nice to have separate commands for naively increasing numbers in the URL and for querying the actual page. I know some other Vim-based browsers do it this way.

**Comment by Jelmerro** [comment]
From the help page:
```Call this action to increase the page number in the url. It will check for pagination indicators in the webpage to use, then try to increase the port number and finally a fallback to 'p' and 'page' query arguments. If none of these are present, it will increase the first number in the url.```
There is a fairly standard way to indicate pagination in an accessibility-friendly way, which Vieb will try to find. If it doesn't, it will check the port number, `p` and `page` arguments and finally the first number of the url. None of these depend on the page language, and I would like to keep it that way.

Having said that, it will definitely help to have more ways to modify the url with actions, though I feel that those are better suited to be done with custom variables and functions (possibly with #192).

**Comment by ottopiramuthu** [comment]
> None of these depend on the page language, and I would like to keep it that way.

I see what you mean and feel the same way. 
> Having said that, it will definitely help to have more ways to modify the url with actions, though I feel that those are better suited to be done with custom variables and functions (possibly with #192).

I agree and I think this will be much cleaner if users have more access to Vieb's internal API. I will close this for now as my needs are more or less met with `action.increasePageNumber`.

**Comment by Jelmerro** [comment]
That's great to hear, so feel free to open issue for sites where this doesn't work, so we can improve the detection even more.

**Comment by ottopiramuthu** [comment]
List of sites that don't work (will update when I find more):
- https://webtripcomics.wordpress.com/2016/09/01/la-bas/ you can see links at the bottom with arrows to previous/next posts (BESTIAIRE, MON PLAN B), but because the pages are sorted by date, increasing the page number doesn't work
- http://bd.boumerie.com/comic/fin/ there are first/prev/random(PEU IMPORTE!)/next/last arrows below each comic, but increasing the page doesn't do anything

**Comment by Jelmerro** [comment]
I have updated the pagination selector to work on these sites and probably a whole lot of other sites that use the same selectors.
