### ISSUE TITLE
`smartcase` for search-mode

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#212]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add a setting that allows search-mode to use `smartcase` like in Vim, which acts like `ignorecase` until a capital letter is typed, at which point it matches casing.

**Alternatives considered**
As far as I know there aren't any.

**Comment by Jelmerro** [comment]
I have been wanted to implement a better search for a while, but there are very few ways to customize the search in Electron currently. I already have an issue for allow regular expressions, but so far there has been little activity. Having said that, I think that smartcase is actually one of the things we can actually implement without requiring any changes in Electron, as we can detect uppercase letters and set the case sensitive flag based on that. I'll see if this is possible.

**Comment by Jelmerro** [comment]
Please check the latest version for the new smartcase setting.

**Comment by ottopiramuthu** [comment]
This works. Thank you!
