### ISSUE TITLE
`increasePageNumber` and `decreasePageNumber` should be countable

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#213]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Typing `[num]<C-a>` or `[num]<C-x>` does not increment/decrement the pageNumber `[num]` times. A new user might expect this coming from Vim.
**To Reproduce**
1. Open `xkcd.com/2473`
2. `2<C-x>`
3. `2<C-a>`
4. Instead of going back 2 pages and forward 2 pages, it goes back 1 page and forward 1 page

**Expected behavior**
Start at `xkcd.com/2473`. Visit `xkcd.com/2471` and go back to `xkcd.com/2473`.

**Specs**
 - OS: Windows 10
 - Version: Vieb 5.0.0

**Comment by Jelmerro** [comment]
This might seem simple, and for numbers in the url it really is, but it's not for other types of pagination. If a page has a next page button, such as the sites you linked earlier, or github for example, you can't really predict the next pages. This means that it's hard to make that part of the action countable. Maybe it's a good idea after all to split this action into different ones. I can see the following ones being useful:

- Page number in the url (such as `?p=4` or `?page=3`)
- Port number (such as `localhost:8080`)
- Last number of url
- First number of url (possibly the port number or some part of the url)
- Use pagination of the page (This is the only one that won't be countable, as we need to inspect the page for it)

My biggest concern is that we can't bind them all to `<C-a>`, but will have to choose which one is the most useful to be mapped there by default. And where do we map the others?

**Comment by ottopiramuthu** [comment]
I see the problem. All of the suggested sub-actions look good to me, but maybe that would be too much to make mappings for. I would suggest mapping the most useful one of the four countable actions you mentioned (in my opinion "last number of the url") to `<C-a>` and mapping the pagination action to something like `g<C-a>` (In Vim it's unrelated to `<C-a>` and does something that's pretty useless in the browser context).

**Comment by ottopiramuthu** [comment]
Looking at what other Vim browsers use, a very common solution is:
- `<C-a>/ <C-x>` for increment/decrement the last number in the url
- `[[ / ]]` for using pagination
- `{{ / }}` for using pagination in a new tab

**Comment by Jelmerro** [comment]
That seems like a decent way to do it, we can put the one of the other actions at `g<C-a>` and just leave the rest unmapped by default. If people need them, they will be able to find them in the help right next to these other actions.

**Comment by Jelmerro** [comment]
Let me know if this [this commit](https://github.com/Jelmerro/Vieb/commit/8822516f2d33e09b64622ba88dde2995163b730c) solves all things we discussed here.

**Comment by ottopiramuthu** [comment]
This works as expected. I will check if any examples need mapping changes and get back to you with a PR.

**Comment by Jelmerro** [comment]
Great, I'll close the issue since this is implemented, next release will include this.
