### ISSUE TITLE
Allow `<editWithVim>` in command, search and explore mode

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#219]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
`<editWithVim>` only works in insert mode at the moment. It would be nice to be able to use our favorite editor to edit commands and URLs in command mode and explore mode.

**Alternatives considered**
You can copy the text from the navbar and paste it into your editor, but just using `<editWithVim>` would be more straightforward.

**Comment by Jelmerro** [comment]
Let me know if this works as expected, it's been implemented [here](https://github.com/Jelmerro/Vieb/commit/7645144f6571bd8997e07138fdcfeda85fd809b0).

**Comment by Jelmerro** [comment]
Thanks, I'll close this and include it in the next stable release.
