### ISSUE TITLE
Add digraphs to Vieb

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#225]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Digraphs can pretty easily be made with mappings:
- `imap <C-k>a: ä`

It would be nice to have Vim's default digraphs (see Vim's `:dig`) in Vieb. I know it's a ridiculously long list, so maybe it shouldn't be in Vieb by default (or maybe it could, got to put the `mapsuggest` scrollbar to good use ;) ). If so, I could make a separate viebrc with all of these mappings that can be included in Vieb for those who want it.

**Alternatives considered**
Adding your most-used digraphs to your personal viebrc works for most people. I think the separate viebrc would be a nice. People could take the parts they need in their personal configs and leave the rest for reference.

**Comment by Jelmerro** [comment]
I personally have never used or needed this, but a separate config for it doesn't influence the default behavior, so that can be added. I'm just not sure if it's right to list it as an "example" config or if we need a separate location to share these kind of things. Maybe you could consider making a github discussion or a reddit post for it? Although I wouldn't mind this being added to Vieb as long as it's optional.

**Comment by ottopiramuthu** [comment]
I have made a digraphs viebrc and will make a PR if you let me know where you want me to put it.

**Comment by Jelmerro** [comment]
Would be nice to add a separate paragraph right below the examples that are slightly different in function, like this one. I thought we could name it snippets, but that name is probably fairly confusing, so how about config fragments?

**Comment by ottopiramuthu** [comment]
Sure I can try to make that. Would you want a separate folder for those (e.g. `/app/examples/fragrments/digraphs`)?

**Comment by Jelmerro** [comment]
A great PR was made for this, but we can't actually use this until an Electron bug is fixed. See [here](https://github.com/Jelmerro/Vieb/pull/226) for details.

**Comment by Jelmerro** [comment]
Though I would really like this feature, electron has closed this as a "won't fix", so sadly we need to do so as well.
