### ISSUE TITLE
Searching based on selected text

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#228]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Currently Vim's `*` mapping can be made in visual mode using `<p.copyText>`:
```
vmap * <p.copyText><toSearchMode><C-v><CR>
```
It would be nice if Vieb had a dedicated action for this that does not pollute the clipboard.

**Alternatives considered**
The above mapping can be used to search based on selected text, but this pollutes the clipboard, which is not ideal.

**Comment by Jelmerro** [comment]
This has been implemented [here](https://github.com/Jelmerro/Vieb/commit/c55bda6ae88ca33a5ea6aafa29f79011faa933bb), let me know if this also works as expected for you and if we need any updates to the examples or the cheatsheet.

**Comment by ottopiramuthu** [comment]
I've made a PR for the cheatsheet and will check the examples and make a PR later.

**Comment by Jelmerro** [comment]
I have added `*` as an additional mapping for it, so Vim extensions using that don't need any changes.

**Comment by ottopiramuthu** [comment]
In that case only chromium and firefox need updating. I've made a PR for those.

**Comment by Jelmerro** [comment]
I have merged that, did the action work as expected as well?

**Comment by ottopiramuthu** [comment]
Yes, it works well.

**Comment by Jelmerro** [comment]
Great, next release will include this as usual, I might do one today actually.
