### ISSUE TITLE
`gv` to restore the last visual selection

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#236]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Vim has `gv` to restore the last made visual selection (including the cursor position). I would like a similar action in Vieb that goes to the location of the last visual selection and restores it. If the tab where the last selection was made has been closed, you can either reopen it and restore the selection or do nothing. Either behavior is fine with me.

**Alternatives considered**
You can manually redraw it, but `gv` would be faster.

**Comment by Jelmerro** [comment]
Is [this](https://github.com/Jelmerro/Vieb/commit/e9e36bdd042fddee6092b92517bb9e46943455df) working as expected?

**Comment by ottopiramuthu** [comment]
Yes, this works!
