### ISSUE TITLE
`:earlier` and `:later`

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#238]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add commands `:earlier` and `:later` from Vim to travel back/forward in the state of the browser in second/minute/hour/day increments. I would be fine with this only working in single sessions (no need to record state after the browser is closed).
For example:
```
" I set a suggestorder
:set suggestorder=file

" (~2 hours of doing things)

" I want to remember what suggestorder I had before I changed it
:earlier 130m
:set suggestorder?

:notifications
" I copy suggestorder from the notification

:later 130m
:set suggestorder=(paste it here)
" continue working, but with the older suggestorder
```

**Alternatives considered**
Undoing sort of does this for tabs/splits, but having a more global undo/redo command with `:earlier/:later` would be helpful.

**Comment by Jelmerro** [comment]
I don't really use the later and earlier commands in Vim, is that for managing the undo tree? I personally use a Vim plugin to visualize that, so I don't use these commands directly. How exactly would that concept translate to Vieb, is it only for settings? Or also for mappings, or for the list of tabs/pages, for splits perhaps? I understand wanting to integrate Vim's features into Vieb wherever possible, but because a traditional buffer with undo and redo isn't present in Vieb, this will need more refinement before it can be worked on.

**Comment by ottopiramuthu** [comment]
>  is that for managing the undo tree?

In Vim the commands  use the `:undolist`, which means it only keeps track of changes in files.

>  How exactly would that concept translate to Vieb

I was thinking the "undolist" could track any changes made with commands and mappings. This way `:earlier/:later` could be used to "time travel" through any changes made to tabs and settings. 

I understand that this is a pretty big task, and I'm open to any suggestions for how this could be:
- broken up into smaller steps
- limited a bit so it is easier to implement
- anything else I've missed

**Comment by Jelmerro** [comment]
I think what we need is a clear list of what is affected by "earlier" and "later" commands and what isn't, because to me it's really vague currently. I also agree that this is a LOT of work to implement, for a kind of niche use case, but if somebody thinks this is worth it, feel free to make a PR.

**Comment by ottopiramuthu** [comment]
Here is a list of things that should be tracked by `:earlier/:later` if possible:

- all settings and mappings
- all tabs/splits (positions, pinned/muted status, which one is focused)
- any currently-pressed keys (e.g. if `g` from `gg` is pressed)
- the current mode
- navbar text, position in the navbar list
- text, cursor position, and selected text in any text boxes in insert mode
- pointer position and any selections for pointer/visual mode
- cookies
- notifications
- extensions

I'm guessing most of these things are stored in variables already, there just needs to be a system that stores the state of the variables whenever one of them is changed with a timestamp. `:earlier/:later` will then step through this list of changes to go backward/forward in time.

**Comment by Jelmerro** [comment]
I personally think that tracking all that and making sense of what will change when running `:earlier` or `:later` is more confusing than helpful. I'll keep this ticket open for further contributions or suggestions that could make this simpler to implement and use. I also wouldn't underestimate the amount of work for such a feature, you will need to build a complete runtime history of all features and be able to store and restore them at will, based on nothing but a vague timestamp. Especially being able to go back with `:later` means that this isn't a linear line, but an entire tree of changes that you would to track and be able to navigate.

**Comment by Jelmerro** [comment]
I have thought about this for a while recently and it seems beyond the scope of Vieb to implement this for reasons mentioned above. If anyone feels differently please let me know, but I'll close this as a won't fix for the foreseeable future.
