### ISSUE TITLE
Select menu items by letter

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#252]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Some Firefox menu items can be pressed by typing a letter that is underlined. For example:

![image](https://user-images.githubusercontent.com/49997309/123420580-b80c9400-d589-11eb-9353-abf1056a1e9e.png)

Here, pressing `t` will open the link in a new tab, `l` will copy the link, etc. 
It would be nice to have a similar feature in Vieb.

**Alternatives considered**
~~I tried making mappings like `mmap a <openNewTab>`, but this just exits the menu.~~ 
Menu mappings work fine as long as there aren't normal mode mappings that override them, but they are global, whereas Firefox has different mappings depending on the type of element that is right-clicked.

**Comment by Jelmerro** [comment]
I do see what you mean, but this would need a significant rework of the mapping system, that would also make it less consistent with the rest of the system. I consider the existing solution to this, that ALL of the menu (besides spellchecking) actions are already available as regular actions, so the menu is mostly aimed at mouse users who don't know the shortcuts of those actions. In other words, you don't need to even open the menu to execute the functionality that it provides. The actions are covered in `:h link-related`. How would you make sure to keep the existing mapping system in place and still improve the experience to something you are suggesting?

**Comment by ottopiramuthu** [comment]
I had a feeling this wouldn't fit in well with the current mapping system.. I'll have to think for a bit what specifically my use-case for right-click menus is before I can find a good solution for this. 

A good first step for improving the experience would be making sure normal mode mappings don't interfere with menu mode mappings. Mappings like `mmap j <menuDown>` work, but as soon as you make a menu mapping that has a normal mapping with multiple keys the `mmap` is ignored. For example, `mmap g 999<menuUp>`: as soon as I press `g` with the menu open I get the mapping suggestion for `gg` and I'm back to normal mode. And if I do `<right-click>g<right-click>g`, Vieb goes to the top of the page as if I had never right-clicked.

**Comment by Jelmerro** [comment]
I should have fixed the mapping issue, let me know if you still need other changes regarding this issue.

**Comment by ottopiramuthu** [comment]
The mapping issue is fixed. With this, I think I'm fine with menu shortcuts being global. The worst that can happen is the action fails and you get an extra notification. 

It would be nice if some of the mappings mentioned in `:h link-related` that work in pointer or visual mode also would work in context menus by default. I understand if this is adding too much for default mappings, but to me menus are a bit clunky to work with completely mouseless at the moment and I think adding single-key mappings for downloading, copying, and the other things that pointer mode can do already would make using menus a lot smoother.

**Comment by ottopiramuthu** [comment]
Actually there is still a small problem: the mapping suggestions for normal mode still flash up when a menu mapping like `mmap g <menuUp>` is pressed.

https://user-images.githubusercontent.com/49997309/123522912-8b8e7000-d68e-11eb-81af-03b062988fda.mp4

**Comment by Jelmerro** [comment]
I'll see if it's possible to fix this, but at least it does the right thing now.

**Comment by Jelmerro** [comment]
I have made some small changes again, let me know if this is enough to close this ticket.

**Comment by ottopiramuthu** [comment]
Single-key mappings like `mmap g <menuUp>` now work without opening the mapping suggestions, but keys with multiple mappings like `mmap gg <menuUp>` still trigger normal mode. For another example, `mmap l <menuUp>` works, but `mmap ll <menuUp>` triggers normal mode `<scrollRight>`.

**Comment by Jelmerro** [comment]
I don't think we really need multi-key mappings for the menu, the reasons being that it will require much more work to implement, and that there are not that many actions that you would want to do specifically in the menu instead of the parent mode.

**Comment by ottopiramuthu** [comment]
That's fine with me until menus get enough actions to warrant multi-key mappings. My issues with menus have been solved for now.
