### ISSUE TITLE
File explorer should have a scrollbar

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#253]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When opening a system directory with many files, the later ones are cut off in the view and there is no way to scroll down.

**To Reproduce**
- Open a directory on your system containing many files/directories: `e file:///C:/Program Files (x86)/ <CR>`
- Notice that the file's contents are cut off in the viewer:

![image](https://user-images.githubusercontent.com/49997309/123510295-99210700-d648-11eb-9939-38beb6e67aa1.png)

**Expected behavior**
I expected there to be a way to scroll down and see the rest of the results.

**Specs**
 - OS: Windows 10
 - Version: Vieb 5.2.0

**Comment by Jelmerro** [comment]
Should be fixed, please check again from source!

**Comment by ottopiramuthu** [comment]
This works, thank you!
