### ISSUE TITLE
Contex menu outside the window

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#254]
**Checklist**
- [ ] I searched the `:help` documentation using `/` for helpful information
- [ ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
ctrl + m to toggle the context menu opens if the window is too small outside the window.
![ViebMenu](https://user-images.githubusercontent.com/69777713/123510901-4ecf7280-d6a8-11eb-8bbc-7f5dfc38805c.png)

**To Reproduce**
[TODO List any steps needed to cause the described bug.
If applicable, add screenshots to help explain your problem.]

**Expected behavior**
[TODO A clear and concise description of what you expected to happen instead.]

**Specs**
 - OS: [Arch linux]
 - Version: [latest]

**Comment by Jelmerro** [comment]
This can't be fixed, there is no way to draw outside of the window. If it was a regular menu this could be possible, but for a wide range of issues this isn't the current implementation:

- Allow custom keybindings
- Jump to actions in using a count
- Custom styling of the menu

The only drawback is that it isn't possible to draw this outside the window, so it just moves in inside.
