### ISSUE TITLE
Action to go to next/previous section in suggestions and other menus

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#255]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
The menus in Vieb only let you travel by entry. An action that lets you skip to the first entry in the next/previous "section" of the results would make navigation easier.
For example:

![image](https://user-images.githubusercontent.com/49997309/123511730-1c465b00-d651-11eb-9035-e7959c183f71.png)

I am currently in the "history" section of the suggestions.
- an action like `<nextSection>` would jump to `vh ...`, the first entry in the "searchwords" section.
- `<prevSection>` would then go back to `... vieb.dev/`, since it is the first entry in the "history" section.

It would also be nice to have this kind of action for context menus, especially since there the sections are even titled.

**Alternatives considered**
You can type more letters to filter results, but that requires thought. I'd like a more direct command to navigate between sections.

**Comment by Jelmerro** [comment]
This has been added in the latest version of the code, let me know if this works as expected.

**Comment by ottopiramuthu** [comment]
This works as expected. I will add it to the cheatsheet.
