### ISSUE TITLE
Start pointer mode from mouse position

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#256]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
A setting/action to start pointer mode with the pointer at the mouse location. It can be annoying that the pointer always starts in the top left corner, even if your mouse is already about where you want the pointer to be. 

**Alternatives considered**
You can use the context menu after you've positioned your mouse to do things you would otherwise do with the pointer. While it is faster to go to a specific point on a page with the mouse rather than the pointer, it's a bit quicker to perform actions with the keyboard.

**Comment by Jelmerro** [comment]
This can be added, but as a separate action. By default the pointer should continue to open at the last position you left the pointer, I think that is the most obvious location for the pointer to appear. This action to open it at the mouse position is a nice suggestion, as long as it's a separate action.

**Comment by ottopiramuthu** [comment]
Making it an action is fine with me.

**Comment by ottopiramuthu** [comment]
This works with `<p.moveToMouse>`.
