### ISSUE TITLE
Jumping actions for context menus: top, bottom and between sections

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#258]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Some actions for jumping in context menus:
- jump to top element
- jump to bottom element
- jump to middle element?

**Alternatives considered**
Mappings like `999<menuUp>` and `999<menuDown>` don't work since these actions wrap around instead of stopping at the top/bottom.

**Comment by Jelmerro** [comment]
Would it be better if we added actions similar to #255? I suppose that that could be more helpful than a middle one, and it can also be more useful than just the top and bottom ones. What do you think?

**Comment by ottopiramuthu** [comment]
I think the middle one can be left out once that issue is implemented. Top/bottom wouldn't be redundant even with the section jumping actions: Say you are in the middle of a long list, jumping directly to the top/bottom would still be faster than jumping by section to the top/bottom.

**Comment by Jelmerro** [comment]
I just implemented this, let me know if this is what you had in mind by running Vieb from source as per readme.

**Comment by ottopiramuthu** [comment]
This works as expected. I'll add these to the cheatsheet a bit later.
