### ISSUE TITLE
Numpad keys won't be entered into the URL bar on W10

### ISSUE THREAD

**Issue by theolice** [Jelmerro/Vieb#260]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Numpad keys aren't recognised and entered in the URL bar. The regular input in websites is working as intended, just not in the internal Vieb-specific areas. I can however map the keyboard keys to functions and such.

**To Reproduce**
- Go to Explorer/Command/Search mode
- Press any key from the numpad, e.g. `5`, `/`, or `.`.
- Observe nothing being entered.

**Expected behavior**
The expected behaviour would be seeing the pressed characters appear.

**Specs**
 - OS: Windows 10
 - Version: 5.3.0

**Comment by theolice** [comment]
Just checked on my laptop where v5.2.0 was still running, and I'm not able to reproduce it there.

**Comment by theolice** [comment]
> 
> 
> Just checked on my laptop where v5.2.0 was still running, and I'm not able to reproduce it there.

After updating to v5.3.0 I can reproduce it on my laptop as well.

**Comment by Jelmerro** [comment]
Should be fixed in the latest code, will be included in the next stable release.

**Comment by theolice** [comment]
Checked and works, thanks!
