### ISSUE TITLE
Option for setting navbar and suggestions to bottom

### ISSUE THREAD

**Issue by bluesheep100** [Jelmerro/Vieb#262]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Short and simple:
I'd really like an option to set the navbar and suggestions list to be in the bottom, like in Qutebrowser, Nyxt, and Vimb.
With the commandline in vim being at the bottom, it's just something I prefer.

**Comment by theolice** [comment]
This already exists and can be done with the colorschemes. Try `:colorscheme flipped` for example :)

**Comment by bluesheep100** [comment]
Thank you, I had completely forgotten that the colorschemes were written in CSS.
It's all working now, so I'll be closing this issue :)

**Comment by Jelmerro** [comment]
As mentioned, this is already included in Vieb. You can even make custom themes/colorschemes, but what you want is included as an example theme named `flipped`. You can find help for colorschemes with `:h colorscheme` or `:help :colorscheme` (the help command has recently been improved to handle these variations better, so combined with autocomplete things like this should be easy to find).
