### ISSUE TITLE
Passing flags to Electron (to enable Wayland support)

### ISSUE THREAD

**Issue by Isti115** [Jelmerro/Vieb#265]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
I would like to run Vieb as a native Wayland window instead of through XWayland.
(My motivation for this is using my custom keyboard layout, but this could generally be desirable.)

**Steps that have been attempted**
I tried passing the `--enable-features=UseOzonePlatform` and `--ozone-platform=wayland` flags to Vieb in hopes that they would be passed to Electron, but it just reported them as unsupported arguments.

**Comment by Jelmerro** [comment]
Vieb does not have these arguments, which is why they are ignored and print this warning. I was under the impression that they would be passed to Chromium if at all provided, but maybe that needs to be done explicitly. I'll check if that is the case in a couple of days, and see if there are options to do so.

**Comment by Isti115** [comment]
I would very much appreciate if you could look into this, because I became a huge fan of the keyboard driven web browser concept after I got to know qutebrowser, but it has a huge memory leak flaw which makes using it pretty inconvenient from time to time, so I would like to switch, and I have already started to (pretty successfully) port my configuration over to Vieb, but what's keeping me from moving over currently is the lack of Wayland support.

**Comment by Jelmerro** [comment]
Could you try running Vieb from source (see [Building paragraph in the readme](https://github.com/Jelmerro/Vieb/#building) for instructions) and then try starting vieb with:
`npm start -- --enable-features=UseOzonePlatform --ozone-platform=wayland`
For me this gives some kind of wayland error (I don't have wayland yet :disappointed:), so I guess this should work on your machine. Please let me know the results.

**Comment by Isti115** [comment]
I've tried you suggestion, but I'm on NixOS, thus am not binary compatible out of the box, so electron does not want to start from the npm installed version... (At least I think that that is the most probable cause of the following error, since the electron executable is present and I have had similar issues with other programs.)

```
> vieb@6.0.0-dev start /home/isti/prog/Vieb
> electron app

events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/isti/prog/Vieb/node_modules/electron/dist/electron ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/isti/prog/Vieb/node_modules/electron/dist/electron',
  path: '/home/isti/prog/Vieb/node_modules/electron/dist/electron',
  spawnargs: [ 'app' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vieb@6.0.0-dev start: `electron app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vieb@6.0.0-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/isti/.npm/_logs/2021-08-13T11_44_39_169Z-debug.log
```

I'll try to sort this out (or try on another machine) and report back with the results!
Thanks for the guidance! :)

**Comment by Isti115** [comment]
**Update:**
Instead of patching the binary (which seemed too complicated due to numerous libraries missing as well) I installed electron separately and tried launching it by passing the `app` folder as an argument.

Without any extra flags it runs correctly, but when the flags are passed, no window shows up, but this is probably not a Vieb issue, since it is consistent across anything that I try to open with electron using these flags. (Oddly enough, all other apps that I have tried so far have worked perfectly fine with these switches.)

It looks like the process is actually created and the window is somehow loaded in the background, since if I try to open Google (`electron https://google.com --enable-features=UseOzonePlatform --ozone-platform=wayland`), a popup appears asking for geolocation permission, but the window isn't displayed. Anyway, I'll try to keep figuring this out and post an update here if I find a solution!

**Comment by Jelmerro** [comment]
Good to hear that the argument passing works and that you got it running. If you also have the invisible window issue with other Electron programs I would recommend to open an Electron issue for it. I think we can close this argument passing ticket as implemented in Vieb?

**Comment by slzatz** [comment]
My experience with arch linux and building from current source is:

```
$ npm start -- --enable-features=UseOzonePlatform --ozone-platform=wayland

> vieb@6.0.0-dev start
> electron app "--enable-features=UseOzonePlatform" "--ozone-platform=wayland"

Arg '--enable-features=UseOzonePlatform' will be passed to Chromium
Arg '--ozone-platform=wayland' will be passed to Chromium
[1951:0824/155005.371057:ERROR:cursor_loader.cc(115)] Failed to load a platform cursor of type kNull
(node:1951) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:1951) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:1951) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
[1988:0824/155005.416945:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is egl
[1988:0824/155005.420001:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:1951) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
[1951:0824/155006.096808:ERROR:wayland_event_watcher.cc(249)] Fatal Wayland communication error: Broken pipe
```
`electron https://google.com --enable-features=UseOzonePlatform --ozone-platform=wayland` does launch chromium without errors.

**Comment by slzatz** [comment]
Thanks - starting vieb that way from an AUR install worked for me although it's a little curious since you get unsupported argument messages but it actually launches, which is great.  Without the command line options, it seg faults.
```
$ vieb --enable-features=UseOzonePlatform --ozone-platform=wayland
Unsupported argument: '--enable-features=UseOzonePlatform', use --help for info
Unsupported argument: '--ozone-platform=wayland', use --help for info
```

**Comment by Jelmerro** [comment]
This doesn't work in 5.3.0 but will work in the next release or if you build it from source. Currently arguments are ignored, but from next release they will be passed on to Electron and Chromium.

**Comment by Crandel** [comment]
@Jelmerro It shows warnings about unsupported argument, but it actually run native in sway. I have no Xwayland, so It would not be possible to run vieb in X11 mode

**Comment by Crandel** [comment]
I run vieb using this command and it actually enable video hardware decoding, together with  native wayland support
```
/opt/Vieb/vieb --force_low_power_gpu \
               --ignore-gpu-blacklist \
               --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,WebContentsForceDark,VaapiVideoDecoder \
               --ozone-platform=wayland 

Unsupported argument: '--force_low_power_gpu', use --help for info
Unsupported argument: '--ignore-gpu-blacklist', use --help for info
Unsupported argument: '--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,WebContentsForceDark,VaapiVideoDecoder', use --helpfor info
Unsupported argument: '--ozone-platform=wayland', use --help for info
``` 
Just for the list of useful electron flags

**Comment by Jelmerro** [comment]
Vieb 6.0.0 has been released, which will pass all unrecognized arguments to Chromium and Electron. This is also documented when running `vieb --help`, where you can also find links to sites that list all the supported arguments of Chromium and Electron. As there have been many cases in this thread of successful ways to run Vieb on wayland using these arguments, I will close this issue.
