### ISSUE TITLE
add the "noh" command

### ISSUE THREAD

**Issue by rambip** [Jelmerro/Vieb#273]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

When I just did a search, all the occurences are highlighted in yellow.

In vim, I have the following remap:

```vim
" hide highlights
nmap <c-c> :noh<cr>
```

Is there a way to do that in vieb ?

**Comment by ottopiramuthu** [comment]
The closest command there is to `:noh` is the action `<emptySearch>`. This will clear the search and remove highlighting. If you don't mind losing the current search you can use the mapping:
```
nmap <c-c> <emptySearch>
```

**Comment by rambip** [comment]
Thank's !

**Comment by Jelmerro** [comment]
I'll check if it's not too much work to add `:noh` as a command to Vieb, but in the meantime you can do almost the same with `<emtpySearch` as suggested.

**Comment by Jelmerro** [comment]
This has been implemented in the code. If you want to test this feature out, follow the build instructions from the readme, or wait for the next stable release.

**Comment by ottopiramuthu** [comment]
This clears the highlighting, but pressing `n` after `:noh` brings me back to the first search match, even when I was on a search match later in the page.

**Comment by Jelmerro** [comment]
There doesn't seem to be a way to store that with chromium's search engine when you clear the highlighting, so while I would like to add that, I think we can do without it.

**Comment by Jelmerro** [comment]
Added in the latest 6.0.0 release, go check it out!
