### ISSUE TITLE
Is there a way to create a plugin ?

### ISSUE THREAD

**Issue by yoann9344** [Jelmerro/Vieb#274]
Hello, I've just discovered your project and it is awesome. I was looking for a good vim browser for a while and I've never been convinced by ones existing. 

I spend a consequent amount of time on github, so I would like to create a plugin to facilitate the interaction with it. My first ideas are to create a special « mode » where the bindings become ones of the plugin. Then for example when you activate this mode on a github file, it allows you to move other the file with usual vim mappings. And it could go even further, like file browsing...

I've not found any information about plugin creation, so I have few questions :
1. Is there some existing way to create a plugin ? Or is it planned to create this functionality ?
2. Would it be possible to integrate an existing vim plugin manager ? (I have not read the source code yet)
3. What would be the limit/difficulties to create such a plugin system ?

I'm available to help to develop this functionality, so feel free to go deeply the details !

**Comment by Jelmerro** [comment]
Sadly there is no plugin functionality in Vieb yet, please see #192 for related discussion and implementation details. Feel free to ask any questions about your feature request in that issue.
