### ISSUE TITLE
Socks5 proxy

### ISSUE THREAD

**Issue by TheKhanj** [Jelmerro/Vieb#275]
**Checklist**
- [ ] I searched the `:help` documentation using `/` for helpful information
- [ ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Is there any feature for using socks5 proxy with Vieb?
I did not found anything in help or issues, I have tried setting http_proxy environment variable, using proxychains, and setting electron proxy argument, non of them worked!

**Comment by Jelmerro** [comment]
This is currently not supported in the stable release, but it is possible using an Electron argument when running from source. You can find out about it [here](https://www.electronjs.org/docs/api/command-line-switches). The next stable release will pass unsupported arguments to the Chromium/Electron process instead of ignoring them, so it will soon be possible for all kinds of Chromium and Electron options to be enabled, see also the related #265 ticket.

**Comment by Jelmerro** [comment]
It seems that the latest changes in the source have made it perfectly possible to use the `--proxy-server=<something>` argument with Vieb. Could you let me know if you can get it to work by running Vieb from source using the instructions in the readme, and then running with `npm start -- --proxy-server="ip:port"` with the ip and port filled in? For me this will correctly pass the proxy settings to Chromium/Electron to use it. It will also work the same in the upcoming V6 release of Vieb, but you won't need the extra `--` there, just like this: `vieb --proxy-server="ip:port"`.

**Comment by jizusun** [comment]
Hi @Jelmerro  


Is it possible to use http_proxy? 
I also didn't found anything in the `:help` or `FAQ`?

Thanks!

**Comment by Jelmerro** [comment]
As I mentioned above, the next release will make it possible to use Electron and Chromium args, including the `--proxy-server` argument. The `--help` output will also include two links of documentation regarding these additional supported arguments. I plan to release V6 of Vieb somewhere this week.

**Comment by Jelmerro** [comment]
Vieb 6.0.0 has just been released, which will pass all unrecognized arguments to Chromium/Electron. This means you can use a proxy with Vieb using the `--proxy-server` argument. A full list of arguments can be found in the link above, or at the end of the `vieb --help` output, which also describes the new behavior in more details.
