### ISSUE TITLE
Action to move pointer to next/previous Search

### ISSUE THREAD

**Issue by run2cmd** [Jelmerro/Vieb#276]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
It would be great if I could you set pointer on a search match so it would be easier to copy/paste text I'm looking for. This would speed up copy/paste actions. Flow would be like this:

1. Enter search mode `/` and type searched text
2. `v` to enter pointer mode
3. Move pointer at position to select text (this is what feature action would do)
4. `v` for visual mode and go to end of selection you need
5. `y` to copy required text.

**Alternatives considered**
We could also have pointer to automatically start position on selection you are currently at. Both option would work I think.
Or could have automatic search copy but it would not be that much versatile.

**Comment by run2cmd** [comment]
If you mean `n` for next and `N` for previous then it sounds perfect to me :)

**Comment by ottopiramuthu** [comment]
In addition to `n`/`N` for jumping to search matches in pointer mode, the same actions could be useful in visual mode (jump to and visual select the search match).

**Comment by Jelmerro** [comment]
This was implemented in the code recently, you can try it if you run Vieb from source. I know that this is broken for @ottopiramuthu as per #287, but does it actually work for you @run2cmd?

I'm also considering to put the pointer at the start of the search result instead of at the center, what do you think?

**Comment by ottopiramuthu** [comment]
I think putting the cursor at the start would be better. Say you are searching for a substring like "app" in "apple", most users would expect the cursor to be here: `a`pple instead of here: ap`p`le.

**Comment by Jelmerro** [comment]
I agree, I'll turn it into a setting and make it by default align to the left.

**Comment by Jelmerro** [comment]
I made a setting for it named "searchpointeralignment", where you can choose the alignment yourself, defaulting to "left" as discussed.

**Comment by run2cmd** [comment]
I've tested that today and looks good. It's much easier to copy desired text now.

**Comment by Jelmerro** [comment]
Great, I'll close this and leave further bugs to be reported either [here](https://github.com/Jelmerro/Vieb/issues/287) or as a new issue.
