### ISSUE TITLE
<nextSearchMatch> and <previousSearchMatch> actions not remapable

### ISSUE THREAD

**Issue by TuM0xA-S** [Jelmerro/Vieb#278]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
looks like nextSearchMatch and previousSearchMatch actions not remapable
when i enter `:smap!` i dont see n and N mappings there
and when i try to remap them it not works
**To Reproduce**
1) do `:smap!` (they not show as mappings)
2) try to map that actions to another keys

**Expected behavior**
i can remap them without problems

**Specs**
 - OS: Ubuntu 21.04 x86_64
 - Version: 5.3.0

**Comment by Jelmerro** [comment]
Once you press `<Enter>` to start the search, you by default move back to normal mode. If you want to change the mappings there you need `nmap` instead of `smap`. The `smap` command is for when you are currently typing out your search. Is this what is happening here?

**Comment by TuM0xA-S** [comment]
yes, it is. sorry for my stupidity and thx for answer.
btw now i have something actually looking like a bug

**Comment by Jelmerro** [comment]
Glad this is solved at least, feel free to open a new issue for the other bug.
