### ISSUE TITLE
Unsure how to run firefoxmode

### ISSUE THREAD

**Issue by raccoondude** [Jelmerro/Vieb#280]
I cannot login to google and I believe the issue is that firefox mode isn't enabled, how would I enable this?

**Comment by Jelmerro** [comment]
You can see the [FAQ entry](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#why-cant-i-sign-in-to-google) for all the details, basically just to `:set firefoxmode=google` or add that to your viebrc. In case it still doesn't work, start Vieb with `--site-isolation=strict` or allow ""less secure apps"" in Google from another browser. When even still unsuccessful, there isn't anything else Vieb can do to solve this, as Google only wants people to use Chrome on their sites.
