### ISSUE TITLE
Make it possible to choose container names based on new setting and a newtab command

### ISSUE THREAD

**Issue by Crandel** [Jelmerro/Vieb#283]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
I'm actively using containers in Firefox and I have a bunch of urls, separated to different containers. I read docs for Erwic mode, but it will not work for me as I have ~10 containers and ~10-30 urls on each of them. I don't wont open all of them during start up, I just want to assign specific URL to specific container.

**Steps that have been attempted**
I use this alias to open new tab in `w` container and when open url from history.
```
command! wk <:set containernewtab=w><action.openNewTab><:set containernewtab=s:usecurrent>
```

But this introduce one extra step.
For example in tridactyl addon for Firefox you could run `tabopen -c <container name> <url>`.and this url will be open in this container.

**Comment by Jelmerro** [comment]
If you always want to the same containers for the same urls we could introduce a setting to automatically pick a container name based on a regular expression. For example: `set containernames=.*\Wyoutube\.com.*~youtube,.*\Wdiscord\.com.*~chatapps`.

We should probably also change the newtab action to be a command and give it arguments for container name and url, but I think the setting above would at least help to make sure you don't have to constantly type out container names to for opening sites in different containers. Of course the container name argument of a newtab command would override a matched container name from this new containernames setting.

**Comment by Crandel** [comment]
Maybe using json file would be better, as it will look similar to `Erwic` mode and would be easy to use same container for several websites, because you could auth once and use same cookies in your youtube and gmail for example.
Something like this
```json
{
    "google": [
        "youtube.com",
        "mail.google.com",
        ...
    ],
    "shop": [
        "amazon.com",
        ...
    ]
}
```

**Comment by Jelmerro** [comment]
I want this setting to also be available outside of erwic mode for regular use. Those settings are configured with the viebrc and the set command, which does not support json. Using the erwic json would also not make it possible to change this at runtime, so I would much prefer a regular setting for this, combined with a newtab command.

**Comment by elshize** [comment]
I think it's a great idea to be able to define which URLs should go to a separate container. It would also be good to be able to simply have a command to open a new tab in a specific container, though.

**Comment by Jelmerro** [comment]
I've added a "containernames" setting, along with the commands "tabnew" and "tabnewcontainer". This means all functionality of this feature request is implemented and can be used with or without erwic mode. Please read the help from the dev version to find out more, or wait for the next stable release in a few days. If you have any questions, requests or bugs, let me know or open a new issue.
