### ISSUE TITLE
`mousevisualmode` enters visual mode on scrollbars

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#286]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
If `mousevisualmode` is enabled, clicking and dragging on scrollbars enters visual mode, which is usually not wanted.

**To Reproduce**
- `:set mousevisualmode`
- Go to a website with a scrollbar (e.g. https://github.com/Jelmerro/Vieb)
- Click and drag on the page scrollbar from normal mode
- Visual mode is entered and the pointer shows up on the scrollbar

**Expected behavior**
Visual mode should not be entered when dragging scrollbars. Other elements of the page that are draggable should probably be ignored as well to avoid this kind of annoyance. 

**Specs**
 - OS: Windows 10
 - Version: 6.0.0-dev

**Comment by Jelmerro** [comment]
Should be fixed, seems like I forgot to check if there was actually a selection on the page after detecting a drag (or scrollbar click for that matter).

**Comment by ottopiramuthu** [comment]
Thank you, this works!
