### ISSUE TITLE
Cannot sign in google account.

### ISSUE THREAD

**Issue by HungPham3112** [Jelmerro/Vieb#288]
I am trying to sign in google account but it says: 

> This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in

It says I need to turn on JavaScript but I don't know where it is

**Comment by Jelmerro** [comment]
See [FAQ](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#why-cant-i-sign-in-to-google).

**Comment by HungPham3112** [comment]
> You can temporarily allow ""Less secure app access"" in your Google account dashboard.

I did like FAQ said but didn't work

**Comment by Jelmerro** [comment]
Did you also apply the other workarounds like setting firefoxmode and strict site isolation? Especially the first one helps most people to log in. If still not, go complain to Google, there is nothing to fix here, they simple block everything that isn't Chrome/Firefox.
