### ISSUE TITLE
Open pdf from url

### ISSUE THREAD

**Issue by cab-1729** [Jelmerro/Vieb#289]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
First of all, great browser, I really love it.
When I follow a link that links to a pdf online it leads of a blank tab with two scroll bars. Do I need to attach something to view pdfs online? If yes then how?

**Comment by Jelmerro** [comment]
The PDF viewer is currently broken, see [this issue](https://github.com/Jelmerro/Vieb/issues/91) for details. There isn't anything we can do to solve it for now as it's an Electron issue. Please refer to the other ticket for comments and details. For now you can download PDFs with `:h downloadLink`, which is by default mapped to `D`.
