### ISSUE TITLE
Space in URL with action.pageToClipboard

### ISSUE THREAD

**Issue by run2cmd** [Jelmerro/Vieb#290]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Looks like `action.pageToClipboard` preserves spaces which breaks pasting them in other programs since they stop URL automatic parsing at space. 
Example: https://jenkins-server.dev.com/view/Software Builds/
As you see the space broken the URL

As this is not a technical bug I think it's a bug from user perspective that is why I've opened this a bug. Please change labels if you feel otherwise. Also yes, I know that spaces in URL are bad, but this is what I stumbled on during my work (don't ask :)). 

**To Reproduce**
Just open any site with space in name. I could not find any on internet because it is very uncommon to do such thing.

**Expected behavior**
Expected would be to have `%20` instead of spaces to look like this:
https://jenkins-server.dev.com/view/Software%20Builds/

**Specs**
 - OS: Windows 10
 - Version: 10.0.19043 Build 19043

**Comment by Jelmerro** [comment]
What you are saying makes sense, we should probably change this. Though I'm undecided what to do when somebody presses `<C-c>` from explore mode to trigger the operating system's copy functionality. And what about cutting text, should we do the same? We can definitely change it for the pageToClipboard action, but I also want to know what to do with explore mode cut/copy/pasting.

**Comment by Jelmerro** [comment]
I decided to just implement this consistently for all cut/copy/pasting across the app, it doesn't make sense to do something different there. It was actually fairly easy to prevent the native cut/copy/paste of the OS and make it from scratch, similar to the other user interaction for the url input field. Aligning this with the pageToClipboard and context menus was also done. Let me know if this works as expected when running from source.

**Comment by Jelmerro** [comment]
New 6.0.0 release is out now, which includes this bugfix, as such I'll close this issue. Let me know if there are any other problems you have with URL encoding/decoding either here as a comment or as a new issue.
