### ISSUE TITLE
Forced darkmode automatically set to websites -- similar to DarkReader extension

### ISSUE THREAD

**Issue by alexander-bachmann** [Jelmerro/Vieb#296]
**Checklist**
- [ x ] I searched the `:help` documentation using `/` for helpful information
- [ x ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ x ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [ x ] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
[TODO Describe the problem you are facing, and why you need help with it.]
I am wondering if it is possible to automatically force set websites to dark mode -- similar to the behavior of the chrome/firefox extension: DarkReader. 

**Steps that have been attempted**
[TODO A list of things you tried to use the feature or solve a problem, and what doesn't work when you use them.]
Read documentation

**Comment by Jelmerro** [comment]
There is no such functionality or a plan to introduce this, as the Darkreader extension is actually one of the supported extensions of Vieb. The built-in darkreader was removed in favor of it.

**Comment by alexander-bachmann** [comment]
oh, ok. I'll figure out how to install it. thank you

**Comment by LordMZTE** [comment]
Hey, I use vieb with dark reader, but I'm not sure how I can disable it on certain websites. Usually, I'd do that through it's config menu that comes up when clicking on it's icon, but since those aren't supported in vieb yet, i'm unsure how I can open the menu.

**Comment by Jelmerro** [comment]
You can't yet, because extensions are only partially supported yet. Progress is tracked in #130 for extension support.

**Comment by LordMZTE** [comment]
Alright, thank you! I just wan't sure if there was a currently undocumented way to open the extension menu.
