### ISSUE TITLE
More commands for going to rightmost/leftmost position

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#297]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
With [this commit](https://github.com/Jelmerro/Vieb/commit/438a8d8f29b5f41597be7d003e0fc9559c612826), `:buffer` now supports wrapping to the last buffers using negative numbers. `<:buffer 999>` has been replaced with `<:buffer -1>`. I think this is a step in the right direction, as -1 wrapping around is easier to understand than 999 clamping to the largest index.

Some other operations still require 999, and I would like to minimize this:
- scrolling a page all the way to the right/left (`999<scrollPageRight/Left>`) can be replaced by commands like `<scrollPageRight/LeftMax>`
- moving a tab to the first/last position (`999<moveTabBackward/Forward>`) can be replaced with `<moveTabLeft/RightMax>` commands

There are probably others; these are just the ones I found looking through the example viebrcs.

  
**Alternatives considered**
I realize 999 is commonly used in Vim as a "maximum", but commands for going to the leftmost/rightmost position would be clearer than repeating the right/left commands 999 times.
This is the approach for top/bottom commands, and I think it would work better in this case as well.

**Comment by Jelmerro** [comment]
I think I have replace most examples where this is the case using the new `scrollRightMax` and `scrollLeftMax` actions. Let me know if this sufficiently addresses this issue.

**Comment by ottopiramuthu** [comment]
This works well. The only thing left for now is moving tabs to the left/rightmost position.

**Comment by Jelmerro** [comment]
I have just added this, I think we now got all the 999 cases removed from the examples at least.

**Comment by ottopiramuthu** [comment]
This works. I'm closing the issue until more things come up.
