### ISSUE TITLE
 Randomize the default search engines?

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#299]
Is there a way to randomize the search engines.
I have set searchwords but I would like to give the default search a list of different searx instances.

I

**Comment by Jelmerro** [comment]
There is no way to do this yet, but I suppose we could change the search setting to a list. What kind of interval would you like this to work? Or do simply want it to pick a random one each time?

**Comment by Jelmerro** [comment]
I gave it some thought and figured it's much more likely you would prefer the latter, I know I would, so I implemented that for now. Let me know if this works and/or if you meant something different.

**Comment by se7en-x230** [comment]
You are correct. 
Just randomly switch between a couple of searx instances (or any other search engine urls) would be an amazing feature.

At the moment I use gimmeasearx that runs on localhost but if vieb can do that directly than I don't need gimmeasearx.

**Comment by se7en-x230** [comment]
Works perfect.
Thanks again for the fast reply.
