### ISSUE TITLE
What's the best way to manage bookmarks

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#306]
I read up on favoritepages.

What I would like to be able to
1. be able to add bookmarks easy without editing a file
2. easy manage and access bookmarks/favorite inside vieb
3. group the bookmarks

But I am open for every idea even a external bookmark manager.

**Comment by ottopiramuthu** [comment]
Right now favoritepages is the only bookmarks-like system in Vieb.
You can track the progress on adding a more traditional bookmarks system in [this issue](https://github.com/Jelmerro/Vieb/issues/100#). 
[this comment](https://github.com/Jelmerro/Vieb/issues/100#issuecomment-812579968) explains Vieb will have commands for adding/removing bookmarks, there will be a special page in Vieb for managing the bookmarks, and bookmarks will be groupable by tags and folders.

**Comment by se7en-x230** [comment]
For now I was playing with an external script to copy the url to the clipboard and write it to a text file as set favoritepages+=URL
But I fail to source it back into viebrc.

**Comment by ottopiramuthu** [comment]
You should be able to source the file from within vieb `:source /path/to/bookmarks.txt`. Assuming your `bookmarks.txt` looks something like this:
```
set favoritepages+=vieb.dev
set favoritepages+=google.com
```
your `favoritepages` should be updated.

What errors are you getting?

**Comment by se7en-x230** [comment]
Sorry my mistake.
Works. Not pretty but works for now. Hope to see soon the better bookmark implementation.

Thanks for the good work

**Comment by ottopiramuthu** [comment]
If you want to do all of this in one step, you can set up a mapping like this:
```vim
nmap Ba <pageToClipboard><:!bookmark_add_script.sh><:source /path/to/bookmarks.txt>
nmap Br <pageToClipboard><:!bookmark_remove_script.sh><:source /path/to/bookmarks.txt>
```

**Comment by Jelmerro** [comment]
I second the suggestions made by ottopiramuthu for  managing the the favoritepages, there is no bookmark system yet, so this is all we have for now. You could also think of a mapping such as `nmap q y:set favoritepages+=<C-v><useEnteredData>` to automate this, or wait for proper bookmarks to be added which will obviously make this a lot easier than it is now.

**Comment by se7en-x230** [comment]
> I second the suggestions made by ottopiramuthu for managing the the favoritepages, there is no bookmark system yet, so this is all we have for now. You could also think of a mapping such as `nmap q y:set favoritepages+=<C-v><useEnteredData>` to automate this, or wait for proper bookmarks to be added which will obviously make this a lot easier than it is now.

That looks very clean BUT
`nmap q y:set favoritepages+=<C-v><useEnteredData>` give me est is not an editor command.
With yanking the site url + removing the y in front of the : it works.
Where does the URL get stored? The data seams to be lost after restart.

**Comment by ottopiramuthu** [comment]
You can run `:mkviebrc` to save your current settings to the viebrc. That way, the next time you open Vieb, your favoritepages will be saved. 

If you want to do this automatically, you can add `:mkviebrc` to your preferred mapping for quitting Vieb like this:
```vim
map <A-F4> <:mkviebrc><:quitall>
```

**Comment by se7en-x230** [comment]
`nmap q <pageToClipboard>:set favoritepages+=<C-v><useEnteredData><:mkviebrc` is the winner for now until the bookmark manager is included. 

Thanks @ottopiramuthu  and @Jelmerro for the help and good work.

**Comment by se7en-x230** [comment]
For now I found buku to be the best workaround.

`command! buku_dmenu <:set externalcommand=buku-dmenu><action.openLinkExternal>
nmap <C-b> <:buku_dmenu>`

`command! bukuadd <pageToClipboard><:set externalcommand=bukuadd><action.openLinkExternal>
nmap <C-a> <:bukuadd> `
