### ISSUE TITLE
Custom new tab page

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#308]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Right now, Vieb has `favoritepages` and `suggesttopsites` that control the appearance of the new tab page. I would like a way to set the new tab page to a webpage like `vieb.dev` or to a local webpage like `~/homepage.html`

**Alternatives considered**
Setting the new tab mapping to `:open page.html` would work, but I would like this to be an option for the built-in new tab.

**Comment by Jelmerro** [comment]
While I don't really mind this being added, it seems like a fair amount of work for something that can already be achieved using `:open`. What are the advantages of making this a setting? Finally, the newtab page can be styled with CSS just like any other part of Vieb, so there's that.

**Comment by ottopiramuthu** [comment]
Like you mentioned, this can be replaced by `:open` pretty easily. I'm just thinking from the perspective of a new user. New users will expect a "new tab" setting where they can set the new tab page to anything they want. I know when I first looked at the help I looked for something similar, and `suggesttopsites` and `favoritepages` weren't related enough to new tabs at first glance for me to find them. Having a setting like `newtabpage` (similar to  `startuppages`) would make the option to use one's own new tab page more explicit.

**Comment by Jelmerro** [comment]
This sounds to me like it could also be solved by updating the documentation in a few places to explain that the same can be achieved with custom commands. It's either that or a case of someone contributing this feature to Vieb, because I don't see much value in developing this myself in the near future.

**Comment by Jelmerro** [comment]
I have just added the "newtaburl" setting, you can set it to a url or a file location to override the default new tab page with a custom one. Let me know if this needs anything else, for now I'll close this issue as it's been implemented.
