### ISSUE TITLE
Problem with Enter key mapping

### ISSUE THREAD

**Issue by cab-1729** [Jelmerro/Vieb#313]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
I am having a hard time mapping the \<Enter\> key
I have tried the following  command in both the browser and in the viebrc
`nmap 'g <action.toExploreMode>github.com<CR>`

but in both cases the \<CR\> is not being pressed.
_'g_  just goes into explore mode and types _github.com_ and stays in Explore mode without actually going to github.com.

**Comment by ottopiramuthu** [comment]
I'm not sure why this isn't working, but `nmap 'g <action.toExploreMode>github.com<useEnteredData>` should work.

**Comment by Jelmerro** [comment]
I thought this would be really difficult, but I have found the cause for this, which turned out to be simpler than expected. Let me know if this is also fixed on your side by running from source as per readme instructions.

**Comment by cab-1729** [comment]
Yup, <CR> works fine now when I run from source.

**Comment by cab-1729** [comment]
> I'm not sure why this isn't working, but `nmap 'g <action.toExploreMode>github.com<useEnteredData>` should work.

**Comment by se7en-x230** [comment]
Slightly off topic but this issue gave me this idea.
`set searchwords+=g~https://github.com/search?q=%s`
`map ; <action.toExploreMode>g<space>`
