### ISSUE TITLE
Segfault on file upload Vieb 6.0.0

### ISSUE THREAD

**Issue by veikolippand** [Jelmerro/Vieb#314]
After selecting file for upload Vieb 6.0.0 segfaults. gdb is not showing any hints from core dump about reasons.
Tested on different pages on internet.

Debian 11
Vieb 6.0.0 (appimage as well from deb package)

**Comment by Jelmerro** [comment]
As was discussed [on the subreddit](https://old.reddit.com/r/vieb/comments/pmy846/this_happened_on_vieb/), this is a know Electron bug that they have just fixed in the latest beta. I'll update Vieb soon to use the new Electron version, though I might wait with a new release till the weekend.

**Comment by Jelmerro** [comment]
Updating Electron did indeed solve it, so you can work around this issue by running/building from source, at least until a new stable release is made.

**Comment by veikolippand** [comment]
ok, good to know.
I wait next release then :)

**Comment by Jelmerro** [comment]
New release is out!
