### ISSUE TITLE
Map autofilling of text boxes to a key

### ISSUE THREAD

**Issue by cab-1729** [Jelmerro/Vieb#316]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
I would like to have a mapping for filling a specific text box on a specific page with a specific value.

This could easily be done if there was a way to execute a line of Javascript, but I found out from another issue that using Javascript isn't a possibility for now. Follow mode doesn't help either because the letter assigned to a particular text box varies depending on whether the Vieb window is maximized or not.
Is there any way I could achieve this now?

**Comment by Jelmerro** [comment]
I'm afraid there isn't currently a way to do this quickly. Eventually we would use extensions or custom JS for this, but it might be beneficial for Vieb to have it's own system before that's the case. How would you expect this to work?

**Comment by cab-1729** [comment]
Something like a `:runJS` command which takes the javascript statement to be run as an argument, would be tremendously helpful.
Kind of like a JS console in Chrome but instead of using another pane as a console, the command mode is used.
In that case I could map that command to a key.

**Comment by Jelmerro** [comment]
That's not a bad suggestion actually, and could even have use after we would add support for running custom JavaScript on the application layer. One thing I would like to be clear about this command from it's name, is that this will execute code inside the page. What kind of name would you suggest for this, I was thinking of `runinpage` but that's a bit long?

**Comment by cab-1729** [comment]
I don't really have an opinion when it comes to the name of the command, since I remap everything anyway.

This also adds a problem however. Some JavaScript commands might be written with the intention to output a result. For example, if someone `console.log` s something then where would it be displayed?

**Comment by Jelmerro** [comment]
Since I don't plan to translate API calls inside the page back somewhere, you would be able to find the result of a `console.log` inside the page developer tools, which you can open with `F12` by default, or at all times with the `:devtools` command.

**Comment by cab-1729** [comment]
Fair enough.

**Comment by Jelmerro** [comment]
I have added "runjsinpage" as a command to run custom JavaScript in the current page, which also supports the newly introduced command ranges to run the code in other pages besides the current one.

**Comment by cab-1729** [comment]
Thank you.

My distribution repositories haven't updated yet, but I will be sure to check it out when they do.
