### ISSUE TITLE
Expand follow mode "clickable elements" category

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#324]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Divide the "clickable elements" category for links shown in follow mode into subcategories whenever possible. For example, have categories for "Image", "Video", "Audio", that will have their own hint border colors in follow mode. I don't know if this is possible, but the existence of pointer mode actions like `<p.copyImage/Video/Audio>` suggests that this can be done.

**Alternatives considered**
These subcategories already exist in pointer mode; I would just like for this to be reflected in follow mode.

**Comment by Jelmerro** [comment]
Great suggestion, would recommend to only implement this when #323 is also implemented, as to make it possible to keep the current behavior of not listing media elements in follow mode.

**Comment by yosoymau** [comment]
I'm looking into the code to try and implement this feature, i see that the `parseAndDisplayLinks` method on `follow.js` gets called in tabs.js with `e.args[0]` as an argument, for what i understand this should contain the links that are currently in view in the page. My question is what is this e object?

I was also looking into `contextmenu.js` for the implementation of the `copyImage` method, and i also find that the `e.args[0]` object is used in `tabs.js` as an argument to the `webViewMenu` method, and it seems to contain the type of the element, which i think is being used to decide the elements to include on the context menu acording to the type of element on which the context menu is being created.

I haven't been able to understand how these pieces fit together, maybe someone can bring some light to this and maybe some suggestions or ideas on how to bring this functionality to the `parseAndDisplayLinks` method. 

Thanks!!

**Comment by Jelmerro** [comment]
If you scroll way up in the file to the parent function of where the `follow-response` channel is filtered, there is a method like this:
`webview.addEventListener("ipc-message", e =>` (right [here](https://github.com/Jelmerro/Vieb/blob/master/app/renderer/tabs.js#L790)). This `e` is the event that Electron provides when an ipc-message is received from the webview. It's properties are: `channel`, which is used to filter the message for the right channel, in this case `follow-response`, and `args`, which are the arguments that are send by from within the webview. These args are set [here](https://github.com/Jelmerro/Vieb/blob/master/app/preload/follow.js#L181), and can be whatever you want them to be, in this case an array of follow mode elements, which are collected in the `allLinks` array in the same `preload/follow.js` file. This is the array that should be extended to include more types of links, for which I recommend a new "media" category that bundles images, audio elements and video elements into one "media" category. You may choose whatever color you like for this, as long as it's different from the existing follow mode element types, as listed in `:h startFollowCurrentTab`. If you have any other questions, please ask, or make a draft PR with what you have now so we can discuss the code by commenting on the PR diff code :wink:

**Comment by yosoymau** [comment]
Thank you for the quick response!! Your explanation is very helpful, now i see how all this is tied together. I'll send a PR soon!

**Comment by Jelmerro** [comment]
I have just added a "media" and "image" type to follow mode, and a new setting "followelementpointer" to choose which type of elements appear in the pointer movement version of follow mode. This way you can keep the old follow mode behavior, while still being able to jump the pointer to video/audio/images using follow mode, or you can leave all types enabled (which is the new default, it's a major release that's planned after all).

Also, sorry for picking this up myself @yosoymau, but I had the time this weekend+evening to make some big improvements, so I wanted this to be part of the new major release. Hope you did not spent too much time working on this, though let's just be happy that this feature is now in Vieb.
