### ISSUE TITLE
Hinting mode

### ISSUE THREAD

**Issue by ruby-rust-perl** [Jelmerro/Vieb#325]
In `qutebrowser`, there is a hinting (extended follow) mode. You can hint images, links etc. You can use this mode to copy the image url, links etc (for example) using `;y` and do many other things. This follow mode (without using the `pointer` mode in `Vieb`) to copy links, hint them for many purposes (not only for copying them) can be very useful instead of using `pointer` mode to go to that image or link to copy them. Is there a way to do this without the `pointer` mode in `Vieb`?

**Comment by ottopiramuthu** [comment]
It seems we have been thinking of the same thing :) Once #323 and #324 are implemented, Qutebrower's extended hinting will be mostly covered.

**Comment by Jelmerro** [comment]
Since you can already move the pointer to the any follow mode element, and the pointer can be used to download, copy and do all the actions you describe, the only missing part of this is described in the two linked tickets. Hope this answers your question, make sure to check those tickets out.
