### ISSUE TITLE
Improve `searchwords` %s

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#326]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Search engines defined in `search` or `searchwords` only support one `%s` that is replaced by the "search string".
Multiple `%s` are currently replaced by the same search string. This makes search engines like:
```
searchwords+=xy~www.foo.bar/?category1=%s?category2=different_%s?category3 ...
```
impossible. It would be nice if the `%s` syntax were expanded to allow multiple query strings.
Something like (`%s`, `%s2`, `%s3`, ... ) would make the previously mentioned search engine possible. 

I'm not sure how you would delimit the different queries. Double quotes (`:open searchengine "query 1" "query 2" ...`) would be fine with me, but I'm open to suggestions.

**Alternatives considered**
You can make separate search engines for common queries for query 1 and use a single `%s` to search for query 2, but queries are almost never predictable enough for this to work well.

**Comment by ottopiramuthu** [comment]
Shouldn't the tag be "mode-explore"? :)

**Comment by Jelmerro** [comment]
Yes, thanks!

**Comment by yosoymau** [comment]
Hello, i'm willing to work on this issue if there's no one working on it.
Thanks!
