### ISSUE TITLE
Higher power consumption with opend history-tab

### ISSUE THREAD

**Issue by Schurick** [Jelmerro/Vieb#328]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

The power comsumption of my computer rises up by 15 W when I open the history-tab. When I close it or switch to an other tab it goes down again.

I work with Manjaro Linux (KDE-Plasma). Same behaviour with Vieb 5.3.0 and 6.2.0-Dev.

I don't know if this is related to [#179](https://github.com/Jelmerro/Vieb/issues/179).

**Comment by Jelmerro** [comment]
Does the high power consumption remain after the entire history has loaded? If so, it's probably the same issue as #179.

**Comment by Schurick** [comment]
Yes. The high consumption occures immediately when I open the history site and remains as long as the history tab is open and selected.

**Comment by Jelmerro** [comment]
Then it's the same issue sadly.
