### ISSUE TITLE
Cannot use mouse buttons to navigate history

### ISSUE THREAD

**Issue by unnikrishnan-ag** [Jelmerro/Vieb#329]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Cannot use side buttons on mouse to trigger `backInHistory` and `forwardInHistory` with `set mouse=all`. This works with other programs like Firefox and Windows file explorer. I can reproduce this on a couple of Windows machines.

**To Reproduce**
1. Navigate to duckduckgo.com.
2. Search something.
3. Press side mouse button (`X1Mouse` in vim?)
4. \<Nothing happens>

**Expected behavior**
Go back to duckduckgo.com

**Specs**
 - OS: Windows 10
 - Version: 6.1.0

**Comment by Jelmerro** [comment]
Not our bug (see [here](https://github.com/electron/electron/issues/17134)), but a workaround seems to be possible. I currently don't have a lot of time to look into this, but it seems to be Windows only, hence why I never noticed this myself, and will have a hard time testing this.

**Comment by Jelmerro** [comment]
Should be fixed in the latest code, and will also be included in the next stable release.
