### ISSUE TITLE
Support for Github Keyboard Shortcuts (and other websites provided vi modes)

### ISSUE THREAD

**Issue by erwin** [Jelmerro/Vieb#335]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [X] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

Some websites have pretty good built in Vi like support.
[Discourse based forums](https://meta.discourse.org/) also allow going back and forth with j / k. Same for fastmail.

Most important for everyone here, you can also enable this in your github account with under:
https://github.com/settings/accessibility
[x] Enable character key shortcuts

Once it's enabled, you can move up and down in the github issue list with j / k.
It works better than Viebs j / k scrolling on the few sites that support this.

https://docs.github.com/en/get-started/using-github/keyboard-shortcuts

I think the ideal solution would be a whitelist of sites / key bindings, that "bring their own vi mode" for certain keys...

Maybe you've already got something better but I just haven't found it yet.

When it's possible, going from next/previous "entry" in lists with J / K seems better to me than just scrolling down/up though.

**Comment by Jelmerro** [comment]
If desired, you can just enter insert mode to interact with the site as you usually would, including it's shortcuts. For a passthrough of specific keys on selected sites, we already have an issue to track it's progress: https://github.com/Jelmerro/Vieb/issues/57
