### ISSUE TITLE
Notify-send

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#337]
Is there a way to send a notification via notify-send upon successful executed custom command?

**Comment by Jelmerro** [comment]
While Vieb could in theory listen for the command status or interaction, it doesn't do any of that currently. It just runs the command as a one-shot and forgets about it. Is there any specific reason this should be integrated into Vieb, or is an external script doing so a decent way to do so without it?

**Comment by se7en-x230** [comment]
I invoke wget to download scripts in git and my backup browser if the site doesn't load in vieb. 
Would be nice to have some kind of notification in this cases.

But nothing that cant be done with an external script. I have implemented that already just thought there might be a way to do it directly.

**Comment by Jelmerro** [comment]
I have added "notificationforsystemcommands" in the latest commit, it will also be part of the next major release, which I hope finish this week.
