### ISSUE TITLE
Autocompletion with special characters does not match for file:// urls

### ISSUE THREAD

**Issue by tejing1** [Jelmerro/Vieb#338]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Tab completion in the url field completes file:// urls which then fail to load, when certain characters are involved (`?` was tested).

**To Reproduce**
- create a local html file with a `?` character in the file path
- "explore" to it, using tab completion to fill in the `?` character
- press enter, and see an "Unreachable Page" error.

**Expected behavior**
Ideally, the url input should accept and appropriately deal with these characters in file paths where possible, but at the very least, tab completion should produce valid inputs.

**Specs**
 - OS: NixOS
 - Version: tested with Vieb 6.1.0

**Comment by Jelmerro** [comment]
It seems there was no translations of query param arguments in the url when resolving the file path. I have made a commit you can try if you run Vieb from source which fixes this case, but there might be more. Let me know if you still have issues now, I'll try to make a stable release soon.

**Comment by tejing1** [comment]
Just tested e8f64f945bbe2d0fc8814c2b047018931513dcac and didn't find any issues for my usecase (which is viewing local mirrors of webpages that involve query components)
