### ISSUE TITLE
Fix `:buffer #`

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#343]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Running `:buffer #` seems to only switch to the first tab in the tabbar.

**To Reproduce**
- `:open example.com<CR>t:open github.com<CR>t:help<CR>`
- `:buffer #<CR>`
- Switches to the first buffer, `example.com`

**Expected behavior**
To follow Vim's behavior (`:h alternate-file`), this command should switch to the last-used buffer, similar to `<toLastUsedTab>`.

**Specs**
 - OS: Windows 10
 - Version: Vieb 6.1.0

**Comment by Jelmerro** [comment]
Agree that this should work, but to be fair I simply never bothered to implement this, so it's not a real bug, just a missing feature. I'm working on command ranges at the moment, so I might add this while I'm on it. While it is a good first issue, it's probably not wise to pick this up before the ranges branch has been merged (and I somehow won't have implemented this in that branch).

**Comment by Jelmerro** [comment]
This has been fixed/implemented, I plan to make a new release this week.

**Comment by ottopiramuthu** [comment]
This looks good. The only thing else I would want for this, though it's not a feature of vim, is that `:buffer # title_#` shows up in the navbar suggestions when you type `:buffer `. Maybe before the `:buffer 0 title_0`

**Comment by Jelmerro** [comment]
I don't think I will add it to the list of suggestions permanently, but now it at least shows the right page and matching title if you enter the # as the only argument to a buffer-like command.
