### ISSUE TITLE
Plans for Matrix / Discord / Telegram Servers

### ISSUE THREAD

**Issue by skunkfox** [Jelmerro/Vieb#347]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Vieb is awesome but I know has ever heard of it. There should be more community outreach for this project. A good start would be to set up a (preferably Matrix-based) chatroom where the developers and users can talk and get to know each other. It would also be a good place for novices to ask questions.

**Alternatives considered**
Sure there is funding with KoFi, and development discussion with GitHub, but that sort of formal environment doesn't really lend itself to a 'community' feel.

**Comment by Jelmerro** [comment]
I'm open to new adding new platforms, but just to make sure you know, we currently have the following official platforms related to Vieb:

- This Github repo, including issues, [discussions](https://github.com/Jelmerro/Vieb/discussions) and [sponsoring](https://github.com/sponsors/Jelmerro/)
- The [vieb.dev website/homepage](https://vieb.dev) where you can view it's features and download the latest release ([source here](https://github.com/Jelmerro/vieb.dev))
- A [subreddit r/vieb](https://reddit.com/r/vieb/) for more informal discussion and questions, though I also make announcements there
- And finally [kofi](https://ko-fi.com/jelmerro), that I should really give more attention, but simply don't find the time for

We could add more, but it's already a lot of work for me to stay involved with all these platforms, as I have to do it in my free time. Having said that, I see no problem in people discussing Vieb wherever they want to, so for all I know there might already be matrix chats or whatever, just no official ones. I would be interested in creating official Telegram or Discord channels in the future when I have more time (and I have yet to try Matrix...), but for now I'll personally keep my interactions limited to Github (issues, discussions, code etc.), the homepage and the subreddit.

It would help if others who are interested would comment on this issue which of these channels they might want to see in the future, if for example a lot of people would like an official Telegram chat, it might be worth having it even if I won't be as active on there as on Github or Reddit.

**Comment by skunkfox** [comment]
Your KoFi and personal website mention that you write fiction. But I can't find any links to it anywhere. Where can I read your stories?

**Comment by Jelmerro** [comment]
I'll hopefully get out some stories somewhere this year, it's mostly just a hobby though (and I rarely find the time for it), so I should probably remove it from my ko-fi until I bother to publish any of it. Sorry for getting your hopes up :sweat_smile:

**Comment by Jelmerro** [comment]
Good news! I finally got around to make some Telegram and Matrix chats/channels, I have added them to the readme, website and other section of Vieb. The links are as follows:

- https://matrix.to/#/#vieb:matrix.org
- https://matrix.to/#/#vieb-announcements:matrix.org
- https://matrix.to/#/#vieb-general:matrix.org
- https://matrix.to/#/#vieb-offtopic:matrix.org
- https://t.me/vieb_announcements
- https://t.me/vieb_general
- https://t.me/vieb_offtopic

I'll make an announcement on Reddit and Github in a minute.
