### ISSUE TITLE
Redirect websites to alternative front-ends

### ISSUE THREAD

**Issue by trueauracoral** [Jelmerro/Vieb#350]
I have been trying out vieb recently I like it a lot. 
There is one issue though, usually when I browse I like to redirect to alternative front-ends that are more privacy focused then using the default website. Examples could be:

https://youtube.com -> Some Invidious instance like https://invidio.xamh.de
https://reddit.com - Some teddit instance like https://teddit.net

Usually in other browsers how I redirect is using greasemonkey, but from what I can tell vieb doesn't support that yet. So I am wondering is it possible to do redirection stuff in vieb?

**Comment by Jelmerro** [comment]
Glad you like Vieb so far! What you are looking for is the `redirects` setting (see `:h redirects`). There actually an example there to redirect reddit to old reddit, but you can use it do redirect ANYTHING to whatever you want to. The matching is done using Regular Expressions, so you can make this as advanced as you want to, the redirects happen before making the request and are fully clientside. Feel free to ask any other questions below if you have them. In your case I would do something like:
`set redirects+=^https?://(www\.)?reddit\.com/?(.*)~https://teddit.com/$2`

**Comment by trueauracoral** [comment]
Thank you for the help. I modified the regex a little bit (I know very little about regex) which is working for most instances just not the ones with subdomains.

This is the current code I have:
```
" Twitter
set redirects+=^https?://(www\.)?twitter.com(/.*)?~https://nitter.net$2
" Youtube
set redirects+=^https?://(www\.)?youtube.com(/.*)?~https://yewtu.be$2
" Teddit
set redirects+=^https?://(www\.)?reddit.com(/.*)?~https://teddit.net$2
```
This is all working well just not with instances that use subdomains. If I use this code:

```
" Twitter
set redirects+=^https?://(www\.)?twitter.com(/.*)?~https://nitter.42l.fr$2
```
It won't work because the subdomain `.42l`. 

So my question is how do I make this regex except subdomains?

**Comment by Jelmerro** [comment]
The last redirect works fine here, are you sure that you can connect to [nitter.42l.fr](https://nitter.42l.fr) at all? Or does the redirect not seem to be working? I could also be that you still have the previous twitter redirect in place, which changes it to nitter.net before it gets to this rule. Redirect replacements are applied in order of appearance in the list. Let me know if you can figure it out and if not: feel free to share your viebrc and/or the steps to reproduce again.
