### ISSUE TITLE
XML text is the same color as the background.

### ISSUE THREAD

**Issue by trueauracoral** [Jelmerro/Vieb#352]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When going to a url with that has a .xml file it looks like this:
![image](https://user-images.githubusercontent.com/87541524/151452907-37bce046-52fd-4666-844c-6b94879bbe67.png)
The first issue is that it's in white mode, the second issue is that I can't see the actual content in the xml file. When I select it I can:
![image](https://user-images.githubusercontent.com/87541524/151453042-544f074b-b5a8-4012-9132-3b5b3268b778.png)
So for some strange reason xml files aren't using the dark theme and the text has the same color as the background.

**To Reproduce**
Open in vieb a xml file link. Here is a example:
https://zortazert.codeberg.page/rss.xml

**Expected behavior**
What's supposed to happen is that the content in the xml file is visible and uses the dark theme.

**Specs**
 - OS: Windows
 - Version: 10

**Comment by Jelmerro** [comment]
Thanks for reporting this! Pretty easy fix, so you can check it out if you run it from source, or wait for the next release which will include the same fix.
