### ISSUE TITLE
Close tab without closing split

### ISSUE THREAD

**Issue by kablondino** [Jelmerro/Vieb#358]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**

Looking through the documentation, there is no indication that Vieb has the feature of closing a tab, but keeping the split structure. To be clear, I don't mean just hiding the tab.

In regular Vim, I have bound the following abbreviation, which allows the closing of a buffer without losing any of the splits in the window: `cabbrev BD bn \| bd #`. I have also found other commands that do effectively the same, such as `:b#|bd#`.

A feature to close a tab, but not the split like this would be very useful, as I tend to set up my splits the way I like and then not touch them. It does not need to implement the `\|` character (which does things with pattern matching). If this can be done with an abbreviation that could already be made, that would also be sufficient.

**Comment by Jelmerro** [comment]
You can do exactly this by calling the buffer command with an argument to switch (or using other actions to change to a different tab), and after that calling `:close #`.
