### ISSUE TITLE
navbar top/bottom position setting

### ISSUE THREAD

**Issue by Melandel** [Jelmerro/Vieb#361]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
I would like the ability to put the navbar to the bottom of the screen, like vim's EX command bar, something like `set navbarposition=bottom`

**Comment by Melandel** [comment]
I found out that the colorscheme `flipped` does put the navbar to the bottom. However, `<up>` and `<down>` arrows seem to be inverted when I browse through autocompletion. Is it expected behaviour? If it is, can I override it?

**Comment by se7en-x230** [comment]
Change 
`#suggest-dropdown {top: auto;bottom: 2.1em;flex-direction: column-reverse;}
`
to
`#suggest-dropdown {top: auto;bottom: 2.1em;}
to have the arrows work the right way.


`

**Comment by Jelmerro** [comment]
The flipped colorscheme is just one example of the wide range of custom themes you can create, the code of se7en-x230 should revert the order of the suggestions like you wanted. You can learn how to create your own colorschemes by running this help command `:help :colorscheme`. If you have further questions, please ask below, I'm going to close the issue as it's already possible to fix this without updating Vieb.
