### ISSUE TITLE
Segfault when cancel print dialog.

### ISSUE THREAD

**Issue by veikolippand** [Jelmerro/Vieb#362]
Segfault when cancel print dialog.

Open print dialog (:hardcopy) and then cancel by pressing "Cancel" button or press ESC key on keyboard.

Vieb 7.1.2
Debian 11

Tested both
vieb_7.1.2_amd64.deb
Vieb-7.1.2.AppImage

**Comment by Jelmerro** [comment]
Seems like this will be fixed if we upgrade electron, it's a know issue that's been fixed there: https://github.com/electron/electron/pull/33015 I'll try to find the time in the next weeks to update electron and Vieb.

**Comment by Jelmerro** [comment]
Fixed in 7.2.0!
