### ISSUE TITLE
user agent

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#366]
Is there a way to randomize user agents just as set search= accepts multiple search engines?

**Comment by Jelmerro** [comment]
Not yet, but this will be added soon.

**Comment by Jelmerro** [comment]
Something like this? https://github.com/Jelmerro/Vieb/commit/6a347be79dd436171acbe955f20161c4620be2af

**Comment by se7en-x230** [comment]
Exellent.

Thanks

**Comment by Jelmerro** [comment]
Glad you like it. It will be in the next major release, but it might take a while to be released.
