### ISSUE TITLE
Asian input methods on macOS duplicate characters in explore mode

### ISSUE THREAD

**Issue by jheroy** [Jelmerro/Vieb#370]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
I use shuangping input method  with key `fj<space>`  result is `ffjfj 反`  .

**Expected behavior**
The result should be `反`.

**Specs**
 - OS: macOS monterey
 - Version: 7.2.0

**Comment by Jelmerro** [comment]
Could you maybe link or explain in more detail what type of shuangping input method you use that causes this? I experience no such issue when using the Japanese mozc software, which does something similar. I always test to make sure the processing of input works with it when I'm working on it, but I can't test all different input methods. So if you could link or explain in more detail where I can perhaps download this myself to reproduce it, that would be great. Perhaps it's also a macOS only issue, as I don't have a macbook to test with available at all times.

**Comment by jheroy** [comment]
Maybe it is macOS only issue, I tried macOS system provide Japanese input method, this issue still there.  So, it's not an input method related issue.

**Comment by jheroy** [comment]
I've done some research, maybe caused by `onChange` event of `input` field, and could use `compositionStart`, `compositionUpdate`, `compositionEnd` to fix. But I not sure though.

**Comment by Jelmerro** [comment]
I believe this is fixed in [the new 8.0.0 release](https://github.com/Jelmerro/Vieb/releases/tag/8.0.0), I now check the composition property of the keyboard event, and if the keycode matches that of a composing key. Let me know if this also resolves it for you, as I had to borrow a macbook to test this :sweat_smile:
