### ISSUE TITLE
Set downloadpath according to user-dirs.dirs

### ISSUE THREAD

**Issue by tinywrkb** [Jelmerro/Vieb#375]
In Linux/BSD, the user might already globally set a download folder through the desktop environment's settings or by manually editing `user-dirs.dirs`. Vieb should respect this setting.

I suggest the following:

- Detect user-dirs.dirs location, let's call this `userdirs_path`, [the documented example](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/) is `${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs`.
- In addition to real paths, allow setting `downloadpath` to `$XDG_DOWNLOAD_DIR`, which will use the value set in `user-dirs.dirs` and fall back to `~/Downloads` (`downloadpath` value saved in the settings is still `$XDG_DOWNLOAD_DIR`).
- The default value for `downloadpath` in Linux/BSD should be `$XDG_DOWNLOAD_DIR`. Alternatively, on the 1st run, if `user-dirs.dirs` is detected, then the value should be set to `$XDG_DOWNLOAD_DIR`, and if it's not found, then to `~/Downloads`.  
Not that `user-dirs.dirs` can be an empty file or just missing `XDG_DOWNLOAD_DIR`.

**Comment by Jelmerro** [comment]
I propose the following for the next breaking Vieb release (as this is a breaking change): the default value of `downloadpath` will be unset, an empty string, which will look for `$XDG_DOWNLOAD_DIR` or use `~/Downloads` as the default. If the `downloadpath` setting is set, that dir will be used. This way by default we will respect the XDG stuff without needing a specific first run check, and without using this value if the user decides to set the `downloadpath` setting (even before a first run) to a custom value. Of course this behavior will not change much on mac/windows, besides the default now being an empty string and still using the same directory as before by default. What do you think?

**Comment by tinywrkb** [comment]
Sounds great!  
Maybe avoid parsing `user-dirs.dirs` by fetching the output of `xdg-user-dir DOWNLOAD`.  
We have `xdg-user-dir` in the Flatpak runtime, and I suspect it's available in most desktop distros, if not all.

**Comment by Jelmerro** [comment]
I was thinking of looking directly add the `$XDG_DOWNLOAD_DIR` env var, since this is easier and faster than running a command (such as `xdg-user-dir DOWNLOAD`). Is there any practical difference between the two or any gotchas that I need to know, or will looking at the env var be sufficient?

**Comment by tinywrkb** [comment]
You could do that, but it means that you need first to source `user-dirs.dirs`, as it's not unlikely that `XDG_DOWNLOAD_DIR` is not set in the environment but is configured in `user-dirs.dirs`.

**Comment by Jelmerro** [comment]
Turns out that Electron has us covered with the `app.getPath` API, I just tested this using the `xdg-user-dirs-update` command, and it indeed doesn't instantly update the `XDG_DOWNLOAD_DIR` var, but the Electron getPath function sees the new directory just fine. I'll read the value on Vieb startup using that API and use that value if there is no other directory set with the `downloadpath` setting, which will be an empty string by default (and use `~/Downloads` as the fallback).

**Comment by tinywrkb** [comment]
That's great!

**Comment by Jelmerro** [comment]
Fixed/implemented in [the new 8.0.0 release](https://github.com/Jelmerro/Vieb/releases/tag/8.0.0)!

**Comment by tinywrkb** [comment]
Updating now the Flatpak.
