### ISSUE TITLE
Link hints - Hard to read

### ISSUE THREAD

**Issue by adriancostin6** [Jelmerro/Vieb#377]
**Checklist**
- [ x ] I searched the `:help` documentation using `/` for helpful information
- [ x ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ x ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
[TODO Add better colors/fonts to make link hints more visible,.]

**Alternatives considered**
[TODO Choose colors that make the text easier to read, or make the font bold, or both. It is too thin to be readable if you are at any reasonable distance from the display]

![image](https://user-images.githubusercontent.com/32834752/170404642-46a1260d-c7a3-47a4-a58b-c3487ccfe3a8.png)

As one can see from the attached photo, the choice of colors is not the best. It may work good for some, but some other options would be welcome. In fact, I will try to take a look at this and try to change the colors in the code and will report back my findings. If there already is an option for this, I am sorry but I couldn't find it unfortunately.

**Comment by Jelmerro** [comment]
All text in Vieb (besides headings) uses the exact same font size, so I find it quite puzzling why specifically the link hints would be unreadable, and not the url and tabs for example. The colors are needed to differentiate between the different type of links. Having said that, you can customize Vieb's overall interface fontsize with the `fontsize` setting (which will soon be renamed to `guifontsize`), such as `set fontsize=18`. If you specifically want to change the colors, fontsize or appearance of the follow links, consider making a custom theme as explained at `:help colorscheme`. If you just want to change the colors, you only need the `:root` section of the css file, and the default file will always be used as the basis for other themes, so there is no need to copy the entire file. Just add css rules to change the default styling, add it to a css file in the colors subfolder of your datafolder or in `~/.vieb/colors` and set it with `:colorscheme <name>`.

**Comment by Jelmerro** [comment]
I forgot to mention, making them bold is as easy as a single line of css: `#app #follow {font-weight: bold;}`

**Comment by adriancostin6** [comment]
Thanks for the help. I opened the issue because for my use-case, which is staying quite far from the laptop, the link hints were hard to read even after changing the font size to something like 18. I don't have this problem when holding it in my lap, in fact, as I am typing this I am doing it from inside your browser and can see the link hints just fine. I will go forth with trying to make them bold, as I can see the problem being that the font is thin. As a side note, the browser is growing on me and I must say, it's the thing that I've been missing. Respect to you dear sir for providing such an amazing product.
