### ISSUE TITLE
New useragent setting 

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#380]
I tried a couple of comma separated useragent strings but some sites look strange and the site seams to cycle through all of them before it settles on one random.

What would be a sane multiple useragent string?

**Comment by Jelmerro** [comment]
At the end of the documentation there is an example of a way to use the multiple useragent option, see `:help useragent` for details. Example: `:set useragent=%default,%firefox` this is randomly select either the default or firefox with all platform info as default. If you want to use your own useragent, that's also possible, but if you get weird site results you messed it up. You can see [some examples of useragent on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent). The useragent setting is powerful, but if you set the wrong one, sites WILL break.

**Comment by se7en-x230** [comment]
Thanks @Jelmerro 
I used that exact example page to set it up BUT I think the string usually has a " , " which I guess throws vieb off thinking the next useragent starts there.

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML**,** like Gecko)`

**Comment by Jelmerro** [comment]
I have been thinking about possible solutions for the comma issue, but so far none seem viable, how do you see this happen with the current list structure?

**Comment by se7en-x230** [comment]
If I understand correctly the part in the ( ) is only a comment and therefore not necessary for the agent to work?
If I delete the , in the ( ) the string is shown correct and it looks to me like it works.
But I am not sure if that is actually the case.

**Comment by Jelmerro** [comment]
I think the best solution is to change the list separator for the useragent setting to a different character, I'll work on a fix.

**Comment by Jelmerro** [comment]
Fixed in https://github.com/Jelmerro/Vieb/commit/6d06e23ca71af39269f1b1fcf46df758ce8129af, the separator for useragents will be a tilde `~` instead of a comma `,` as to make commas possible in individual useragents. I plan to make a new Vieb release later this week which will have this changed.
