### ISSUE TITLE
Vieb address/command input box does not accept shift+space

### ISSUE THREAD

**Issue by veikolippand** [Jelmerro/Vieb#381]
I assume this is a bug not a feature. In address or command field when holding shift key down then space key is not accepted there.
This is annoying if typing some acronyms or parts codes or what ever uppercase text with spaces. You might think that it is not a big deal to release the shift key for space but life has shown that it is quite difficult to get right. :)

**Comment by Jelmerro** [comment]
Fixed in https://github.com/Jelmerro/Vieb/commit/fcf56d90ad2edb22444fc74c7b73ae3180461e47, next release will include it, hopefully at the end of this week.
