### ISSUE TITLE
Vieb context menu block

### ISSUE THREAD

**Issue by veikolippand** [Jelmerro/Vieb#382]
Can we have Vieb context menu block with some key binding. For example if i hold down ALT or CTRL and click right mouse button then Vieb context menu is not shown. This is necessary for some pages where is needed to work with javascript popup menu or whatever popup menu some sites shows. Currently i try to work with dokuwiki which has it's own popup menus with some plugins for example.
![14-06-2022_094640_scrot](https://user-images.githubusercontent.com/15278651/173511333-0c085a9c-5a10-4075-bef7-dc1747c816a9.png)

**Comment by veikolippand** [comment]
Firefox does not show it's own context menu in this case. Maybe there is some method to make difference where is needed to show context menu and where is not without any special key combinations.

**Comment by Jelmerro** [comment]
This menu can already be disabled in Vieb, using the `menupage` setting. See `:help menupage` for details. You can either completely disable it with `:set menupage=never` or try a more strict approach for showing it, using `:set menupage=globalasneeded`. If desired, you can toggle these settings with mappings as well.

**Comment by veikolippand** [comment]
hmm
in case of dokuwiki _globalasneeded_ is not showing vieb context menu at all. With _elementasneeded_ shows context menu always even if page menu is poped up.
Somehow firefox has solved that issue but don't know how.
