### ISSUE TITLE
High CPU usage in visual mode

### ISSUE THREAD

**Issue by herrsimon** [Jelmerro/Vieb#383]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
As soon as I enter visual mode, CPU usage increases dramatically (as it did during regular browsing, see #179). This happens even without any open webpage.

**To Reproduce**
Start vieb and enter visual mode (i.e. press `v`). No need to open any webpage.

**Expected behavior**
No increase in CPU usage at all.

**Specs**
 - OS: arch linux
 - Version: 8.0.0.1 (`vieb-bin` AUR-package)

**Comment by KunaPrime** [comment]
can confirm

The same happens on the debian-package (ubuntu 20.04)
Vieb 8.0.0

**Comment by Jelmerro** [comment]
Should be fixed in https://github.com/Jelmerro/Vieb/commit/c73951995a9c8933aa4bebf7b66e9cb1967c7608, will work on a new release later this week.
