### ISSUE TITLE
Vieb new window in controlled manner

### ISSUE THREAD

**Issue by veikolippand** [Jelmerro/Vieb#386]
For some reason when i run a command Vieb and give a URL a new window is created. Don't know the reason, is it OS or Vieb 8.0.0 changes. It definitely was not so for some time ago. Which made me think can we have possibility to say when new window should be created. When i need to do so called a private browsing i create a new data directory and open new window. When i close this window this data directory will be deleted. When i simply use dmenu to open bookmarks i would like to have them opened in same window. Maybe someone has other preferences so it should be controlled somehow. Tried to search from help but didn't find any clues how to do it right now.

**Comment by Jelmerro** [comment]
Could you please specify your operating system and the steps to reproduce, as I can't reproduce it. Vieb (and by extension Electron) do not properly support multiple instances in the same "userData"/datafolder, and as such this shouldn't be possible. Unless I'm misunderstanding what you describe, this seems to be an Electron issue as [this code section](https://github.com/Jelmerro/Vieb/blob/master/app/index.js#L395) should call the Electron API to prevent additional instances.

**Comment by veikolippand** [comment]
never mind. Today my bookmarks are opening in same window in separate tabs like they should. I don't know what happened yesterday but seems like restart has fixed it.
Issue was that when i opened url with command "vieb http://blah" every time new window with same tab history was opened. I ended up with several Vieb windows each with same tabs with same content.
