### ISSUE TITLE
Unable to perform :lclose and :rclose when there is suspended tab

### ISSUE THREAD

**Issue by chunleng** [Jelmerro/Vieb#393]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**

Performing `:lclose` when there is suspended tab ends up with only partial tab to the left being closed.

The similar happens to `:rclose` in the opposite direction

**To Reproduce**

1. Open 3 tabs
2. Go to last tab: `:buffer 2`
3. Suspend the first tab: `:suspend 0`
4. Perform close left tab: `:lclose`
5. Only the suspended tab is closed

**Expected behavior**

Tabs to the left should be closed

**Specs**
 - OS: macOS Monterey 12.4
 - Version: Vieb 8.1.0

**Comment by Jelmerro** [comment]
Fixed in the new 9.0.0!
