### ISSUE TITLE
Setting to Move Navbar to Bottom

### ISSUE THREAD

**Issue by ei-eiron** [Jelmerro/Vieb#394]
**Checklist**
- [x ] I searched the `:help` documentation using `/` for helpful information
Looked at all `navbar` and `tabbar` options
- [x ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Like vim, display command i/o (the navbar and/or tabbar) at the bottom of the page with a setting like `navbarPosition` or `tabbarPosition`.

**Alternatives considered**
I could get used to seeing mode input and tabs at the top of the page, or reduce friction by making them invisible. 

Please let me know if this is out scope or should be moved. Thanks!

**Comment by chunleng** [comment]
I solved it temporary by playing around with the theme.

```css
#navbar {order: 100}
```

With that we might want to shift the suggestion ui that comes with the navbar

```css
#suggest-dropdown {top: unset; bottom: 2em}
```

**Comment by Jelmerro** [comment]
You can indeed already do this with colorschemes, see `:h colorschemes` for an explanation. There are a few built-in themes, one of which is called `flipped`. This does exactly what you describe and more, you can switch to it with:
`:colorscheme flipped`

**Comment by ei-eiron** [comment]
`:colorscheme flipped` is working for me. Thanks @Jelmerro and @chunleng.
