### ISSUE TITLE
Iframe background becoming white when reloading

### ISSUE THREAD

**Issue by ILoveAndLikePizza** [Jelmerro/Vieb#395]
When reloading an iframe (not the page itself!) in Vieb 8.1.0 on Linux Mint 20.3, it's background color becomes white. Upon reloading the entire page, the background will become transparent again, here two screenshots of it:
![Reloading entire page](https://user-images.githubusercontent.com/53319481/182547491-5aaedee0-d545-4faf-8c8f-f13e8fc47c87.png)  
_After reloading the entire page (how it is supposed to be)_  
![Reloading frame only](https://user-images.githubusercontent.com/53319481/182547497-71d1e010-f50d-43d9-a924-71a8a9b21c6a.png)  
_After reloading the iframe only_

**Comment by Jelmerro** [comment]
In general this means that the page did not set it's own background and thus it should default to white, but I guess the logic does not work nicely with iframes at the moment. I'll see if we can only run this check on the main page instead of every frame.

**Comment by Jelmerro** [comment]
Should be fixed with https://github.com/Jelmerro/Vieb/commit/647b88eaf6bb4b0ee822995ea5ad999b35cf010f, let me know if this also works on your website.

**Comment by ILoveAndLikePizza** [comment]
Yes, that commit fixed the issue! Thanks!
