### ISSUE TITLE
Context menu still shows after disabling with JS

### ISSUE THREAD

**Issue by ILoveAndLikePizza** [Jelmerro/Vieb#396]
In JavaScript, the following line of code can be used to prevent context menus from showing up when right clicking on a page:
```js
window.addEventListener("contextmenu", e => e.preventDefault());
```
However, in Vieb 8.1.0 on Linux Mint 20.3, it pops up anyway when I right click a page.

**Comment by Jelmerro** [comment]
This is a feature, websites should not have that much control over which parts of the user interface are enabled, especially if they do so with a global listener. You can control this behavior locally using the settings `menuvieb` and `menupage`, see `:h menupage` for help and details.
