### ISSUE TITLE
An option to disable "Search actions are now applied to all visible splits"

### ISSUE THREAD

**Issue by yamshchikoff** [Jelmerro/Vieb#401]
When using splits for investigation big problems they could be used to reflect tree-like structure of the problem (domain). It is easy then to rewrite growing domain structure to presentations/cheatsheets/mindmaps. It is master-level technique in vim on investigating huge codebases.
To be useful it is crutial to preserve just "forked" "parent" split in state we leave it and starting to read just appeared "child subnode" split. But when we use search commands, to be precise, `nextSearchMatch` action, it whirlwinds states of _all_ visible splits making so powerful technique almost useless.
In order to make it useful (like it is in vim text editor) we could add, say, an option, or flag, or another action to be mapped to different key, or even make it be range-supporting.

**Comment by Jelmerro** [comment]
Let me apologize in advance, as I do not understand what you are trying to convey in your message, so allow me to explain what I think you mean.

Basically, you want searches to only affect a single tab, instead of searching in all tabs at the same time, is that correct?

**Comment by yamshchikoff** [comment]
Yes, it is correct. I've tried to explain why I see it is important, sorry if it was not clear.

**Comment by Jelmerro** [comment]
Implemented in 9.1.0 under the "searchscope" and "searchemptyscope" settings.
