### ISSUE TITLE
multiple useragent make site "jump"

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#404]
Using the setting useragent as shown in :help useragent
`set useragent="%default~%firefox"`
Makes the site reload several times

**Comment by Jelmerro** [comment]
It only happens on some sites in my experience, is that correct? I'll see what I can do about it, but I'm not sure if this can be solved.

**Comment by se7en-x230** [comment]
correct. I can't see a pattern where and when it happens.
It looks to me like the site is cycling trough the different useragents and keeps reloading the site.

**Comment by Jelmerro** [comment]
Fixed in https://github.com/Jelmerro/Vieb/commit/0ac2bc1da70c636b22a18f936a4aaff30c403ba4, I plan to make a proper release within a few hours hopefully.
