### ISSUE TITLE
Vieb 9.0.0 release cannot be opened on Apple Silicon

### ISSUE THREAD

**Issue by chunleng** [Jelmerro/Vieb#405]
**Checklist**
- [ ] I searched the `:help` documentation using `/` for helpful information (Unsuccessful installation)
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
[TODO Add a clear and concise description of what the bug is.
If applicable, add screenshots to help explain your problem.]
Unable to open on Apple Silicon after installing Vieb from v9.0.0 release via Homebrew or manual downloading and installing.

The following screenshot is shown:

<img width="280" alt="Screen Shot 2022-08-16 at 19 10 48" src="https://user-images.githubusercontent.com/2003639/184854828-fb0e706c-e56e-4c04-b400-ae3ad9793255.png">

**To Reproduce**
[TODO List any steps needed to cause the described bug.
If applicable, add screenshots to help explain your problem.]

- Install via Homebrew on Apple Silicon
- Open the app

**Expected behavior**
[TODO A clear and concise description of what you expected to happen instead.]

The app should open successfully

**Specs**
 - OS: Mac Os
 - Version: 12.4

**Comment by chunleng** [comment]
Thank you for the release! Have been enjoying vieb and looking forward to 9.0.0!

**Comment by chunleng** [comment]
https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#mac
Missed the point about `as it's not Vieb's responsibility to fix your operating system quirks for you.`, let me try and see the problem there and will close the issue if I can't get it solved

**Comment by Jelmerro** [comment]
Apple requires you to sign apps to be able to open them, this is only possible on a mac, which is too expensive to buy just for building apps. You can sign it yourself using the instructions in the faq.
