### ISSUE TITLE
JavaScript Error Makes Vieb Unresponsive

### ISSUE THREAD

**Issue by skunkfox** [Jelmerro/Vieb#406]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When browsing duckduckgo I see a popup for "A JavaScript error occurred in the main process", closing that window instantly reopens it and Vieb is completely unusable.

**To Reproduce**
I cannot copy and paste the error or page url but I have included a screenshot. Note: After killing Vieb and reloading the page I no longer see the error, so I'm not sure how to reproduce.

Update: This happened again in duckduckgo search, it seemed to be triggered when I hit 'f' to open a link.

**Expected behavior**
No crashing

**Specs**
 - OS: Gentoo
 - Version: 9.0.0 Flatpak
![20220817_06h51m02s_grim](https://user-images.githubusercontent.com/88281387/185111944-4ffa7714-470a-4852-b771-d1fd2f14f215.png)

**Comment by Jelmerro** [comment]
Let me know if this pops up again, but this should be solved for the case you had this in the latest 9.1.0 release.
