### ISSUE TITLE
Zoom in feature in the browser

### ISSUE THREAD

**Issue by parthkamal** [Jelmerro/Vieb#408]
how to zoom a particular page is there any shortcut key?

**Comment by ottopiramuthu** [comment]
You can press `+`or `=` to zoom in and `-` or `_` to zoom out. See `:help zoomIn/Out` for more details.

**Comment by Jelmerro** [comment]
As answered by @ottopiramuthu, you can control zooming with `+` or `-` on the keyboard, and reset with `<C-0>` (control and then 0). Let me know if you have any other questions, but for now this one seems answered.
