### ISSUE TITLE
Search doesn't scroll through search results

### ISSUE THREAD

**Issue by nitanmarcel** [Jelmerro/Vieb#419]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When searching in a page, the page gets scrolled to the first search result, but when trying to find the next result it doesn't work.

**To Reproduce**
1. Go do https://www.lipsum.com/
2. Search for a word with multiple results (example: `/translation`)
3. Try to search again for the same thing to go the next result 

**Expected behavior**
Just like in VIM or any other browser for example, searching again for the same word should send you to the next result, if any.

**Specs**
 - OS: [TODO]
 - Version: [TODO]

**Comment by Jelmerro** [comment]
You can find next/previous matches with `n` and `N`, searching for the same thing again will currently restart the search. I will see if there is a way to keep it going if the search is the same, but especially if `incsearch` is enabled I do no think there will be an easy way to fix this.

**Comment by Jelmerro** [comment]
Fixed in https://github.com/Jelmerro/Vieb/commit/5dab8e03e4f4468dd0980bc004d618b6fb0db796, it will indeed only work if you do not make use of incremental search, but if you do not change your search and run the same one again it will move to the next one. It also contains backwards searching.
