### ISSUE TITLE
Who uses what userscripts?

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#425]
I need some ideas of useful greacemonkey scripts that work in vieb.

**Comment by Jelmerro** [comment]
Please use the discussions for asking open questions. I'm willing to have issues for questions that I can answer and close right away, but keeping issues open as more of a forum is exactly what discussions are for, you can find them in the top bar, or with [this link](https://github.com/Jelmerro/Vieb/discussions).
