### ISSUE TITLE
action.openNewTabWithCurrentUrl not filling URL

### ISSUE THREAD

**Issue by KunaPrime** [Jelmerro/Vieb#427]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
`nmap T <action.openNewTabWithCurrentUrl>` opening new tab with empty url

**To Reproduce**
1.  go to any web page
2. press `T`
3. new tab opens with URL empty

**Expected behavior**
new tab should open with pre-filled with url current tab 

**Specs**
 - OS: Ubuntu 20.04
 - Version: 9.3.0, Electron 21.1.0 and the Chromium version is 106.0.5249.91.

**Comment by Jelmerro** [comment]
I have made a comment, but in short, this action is not to duplicate a tab, but to open a new empty one, and have explore mode with the current url filled in without navigating directly, so that you can either edit it, or press enter to navigate.

**Comment by Jelmerro** [comment]
Fixed in 9.4.0!

**Comment by KunaPrime** [comment]
i have tried it and it works! thank you
