### ISSUE TITLE
controlling content such as youtube videos

### ISSUE THREAD

**Issue by KunaPrime** [Jelmerro/Vieb#428]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer asking my question on Github instead of [r/vieb](https://www.reddit.com/r/vieb/), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**What needs to be solved**
i was wandering what is recommended way of controlling video on youtube? Specifically how would i start/stop go to full screen or control volume?

**Comment by Jelmerro** [comment]
Currently it's probably fastest to go to insert mode with `i` and using the youtube shortcuts for it (`space` for play/pause, `f` for fullscreen etc). Alternatively, you can use the pointer, and execute media related actions at the pointer location, see `:h media-related`.

**Comment by KunaPrime** [comment]
thank you
