### ISSUE TITLE
Light Scheme for DarkReader?

### ISSUE THREAD

**Issue by I03D** [Jelmerro/Vieb#429]
With the light scheme, you can get a nice yellowish color of the pages with the right setting.
![2022-10-22_16-45](https://user-images.githubusercontent.com/98839825/197332809-d56ee2e2-2d68-4f29-8b3a-9a1f6c19c5ec.png)

**Comment by Jelmerro** [comment]
Seem unsupported, so I made an issue for it [in the darkreader project](https://github.com/darkreader/darkreader/issues/10215).

**Comment by Jelmerro** [comment]
Implemented in 9.4.0, see `:help darkreadermode` for help and details.
