### ISSUE TITLE
Buffer list display page URL.

### ISSUE THREAD

**Issue by run2cmd** [Jelmerro/Vieb#433]
**Checklist**
- [ x ] I searched the `:help` documentation using `/` for helpful information
- [ x ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ x ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
A while ago I started to use `buffer` feature for switching between tabs and I love it. With minimal configuration I made it to work like fuzzy finder for files in Vim.

```
set guitabbar=never
nmap <c-p> <esc>:buffer<space>
```

The only thing I would add is to have displayed list of buffers show URL bound to buffers. I sometimes get pages that their tab description is not enough to know if that is the right place. Example.

![image](https://user-images.githubusercontent.com/9575150/198951150-97be9c5b-f4a7-48d2-bab5-46bd252501ce.png)

As you can see there are 2 Jenkins buffers and each of them refers to different URL. It would be great that it would return URL or even root URL of the website they refer too like:

```
buffer 0 help - vieb://help
buffer 1 New Issue - Jalermo/Vieb - https://github.com
buffer 2 Dashboard [Jenkins] - https://new-jenkins.com
buffer 3 Seed jobs [Jenkins] - https://old-jenkins.com
```

It could be grayed out, it could be full URL. I do not have preference. It would be good to also be able have search work for it. So if I start typing `new` it will show me buffer 3 as a suggestion.

This probably can be done in few ways like tab title modification or enchanting buffer list itself. Which ever will work and easier to implement is best :).

**Comment by Jelmerro** [comment]
Released in 9.4.0! :tada:
