### ISSUE TITLE
setting cache to anything but full makes an error alert trigger on Vieb startup

### ISSUE THREAD

**Issue by Melandel** [Jelmerro/Vieb#434]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Given a Windows 10 environment and Vieb 9.3.0
When `set cache=none` or `set cache=clearonquit`
Then the next times Vieb starts there is often a number of error popups (most likely depending on the number of tabs)
![image](https://user-images.githubusercontent.com/48007894/199465813-c0b142cb-4ceb-4efc-a744-59da1dd9e54a.png)

**To Reproduce**
* start `Vieb.exe`
* run `:h cache`
* run `:set cache=clearonquit` (if not already set)
* run `:qa`
* start `Vieb.exe` again

**Expected behavior**
No error on startup

**Specs**
 - OS: Windows10
 - Version: Vieb 9.3.0

Note: the only way right now I see to not have the issue, is to use `:set cache=full`

**Comment by Melandel** [comment]
I was able to find the commit that created that behaviour. I'm going to discuss this in #426 since it will involve more people impacted by this behaviour.

**Comment by Jelmerro** [comment]
Turns out it was a nodejs issue instead of an electron issue, see #426 for the rollercoaster of solving this.
