### ISSUE TITLE
dark reader is not refine

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#436]
a china tech website : look like csdn :https://www.csdn.net/

the dark reader is not cover the bg. 
![image](https://user-images.githubusercontent.com/87791643/200474391-c637a716-9747-4d8d-88f3-03cf4ccb6c5a.png)

is scoll bar is cover

but most bg is not useful.

so i think the dark reader is not refine

**Comment by Jelmerro** [comment]
If you did `:set darkreader` and most pages are dark except this one, it's not a Vieb issue but a darkreader one. You can report it here: https://github.com/darkreader/darkreader/issues/new/choose
