### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#437]
I dont not why.
maybe is electron

![image](https://user-images.githubusercontent.com/87791643/200474612-75e32cf5-65e0-4b86-aea0-976c2391459c.png)

**Comment by Jelmerro** [comment]
What did you do before you got this error? Did you switch modes, or simply navigate to the website?

**Comment by newyorkthink** [comment]
I forget , i don't not what happy this error. maybe is swich modes

**Comment by Jelmerro** [comment]
Did it happen only once, or does it happen often? If it happens again, let me know what steps you tried.

**Comment by newyorkthink** [comment]
yes , it happen only once.
now it not happen.

i come to think of it.

then, i open three website, and have two split website.
when i closed two website.
it happen

**Comment by newyorkthink** [comment]
> Which version of Vieb were you using at the time?

I used vieb version is 9.3.0 recently , now i using 9.5.0 version

**Comment by Jelmerro** [comment]
I have not seen this happen recently and believe this to be fixed since 9.5.0, let me know if you ever have it again.
