### ISSUE TITLE
how can proxy

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#439]
in china user , visit google must proxy network

so must use proxy and port. look like this

so ,vieb how can use proxy 
![image](https://user-images.githubusercontent.com/87791643/200513440-7b0e094e-8cba-4df2-83c4-078532d9a328.png)

**Comment by Jelmerro** [comment]
You can start Vieb with `--proxy-server=<something>`, so if you need Tor for example:
`vieb --proxy-server=socks://localhost:9050`
I would recommend a Firefox useragent if you do want to user Tor using:
`:set useragent=%firefox`
You can only do set a proxy on startup. If you always want this, you can edit the startup shortcut to include the flag.
