### ISSUE TITLE
how can disable to recently website close

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#442]
when i quited vieb, and restart it . vieb have recently close website
![image](https://user-images.githubusercontent.com/87791643/200589386-b7ae874b-4948-4f50-93bd-f4aff402385b.png)

how can closed it . I don't like start up vieb contain recently website

i try this command , but not working
set keeprecentlyclosed

**Comment by Jelmerro** [comment]
It seems to me like you are confusing recently closed tabs with tabs that are never closed and thus are restored on startup:

- keeprecentlyclosed - is for when you do `d` and then try to do `u` to reopen it, which you can disable with this setting
- restoretabs - is for restoring tabs that you currently have open the next time you start vieb, these tabs are never actually closed, and thus they are restored on startup by default, but you can disable this with `:set norestoretabs` or `:set restoretabs=false`

I think `restoretabs` is what you are looking for, not `keeprecentlyclosed`.

**Comment by newyorkthink** [comment]
is work,ok :)

**Comment by newyorkthink** [comment]
is work,ok :)

**Comment by newyorkthink** [comment]
is work,ok :)

**Comment by newyorkthink** [comment]
is work,ok :)
