### ISSUE TITLE
some website cannot scroll to use 'j' or 'k', scroll key not work

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#443]
I find the some website:
eg.
https://www.kali.org/
https://www.linuxgame.cn/

the ''j' 'k' scroll up or down, not work

**Comment by Jelmerro** [comment]
I was going to comment that this is part of the FAQ: https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#the-page-doesnt-scroll-with-hjkl-should-i-report-a-bug But I noticed that the kali page is using a different scroll method than most pages and should indeed be scrollable. The advice to use pointer scroll methods if regular scrolling does not work remains, but I can at least add support for this other scrolling system. The linux game website is not scrollable as a page, but just the side section is scrollable, so for that site you will need the pointer scroll actions as explained in `:h scrolling`. So basically `c` and then `J` and `K` at the right position.

**Comment by Jelmerro** [comment]
This new scrolling method is implemented in the 9.4.0 release. For all pages that still do not seem to work with these scroll actions, I will refer to the FAQ once again, as in 99% of the cases the page isn't actually scrollable.
