### ISSUE TITLE
auto-hide scrollbar

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#445]
I think vieb is vim-like browser.
most user use keyboard.
so, most vieb user like geek :)

they want to the windows can maximize, because they want to display more thing.

for me, i like to auto-hide titbar and gui-bar.

so, i suggest we can auto hide scrollbar too.

look this:
![image](https://user-images.githubusercontent.com/87791643/200615811-bd788ca6-a4cb-4662-98ae-e96392b3a819.png)

when we split two windows, like tmux.

the double scroll bar occupies two columns of area.

**Comment by Jelmerro** [comment]
You can hide the scrollbar with custom css using the `userstyle` setting. Examples are in the help: `:h userstyle`. But you want this to be added conditionally based on scrolling?

**Comment by Jelmerro** [comment]
Implemented in 9.7.0, see `:h guiscrollbar` for details.

**Comment by se7en-x230** [comment]
Just to clarify.
set guiscrollbar=never will replace the custom css settings for hiding the scrollbar?

AND the the scrollbar will appear shortly when a site is loaded and is then hidden?
