### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#447]
so, I'm buzy.
i find the some bug. and all in report you.

the first:
1. about auto hide guibar.
i env is i3 desktop.
when i change other gui software, and re-back to vieb.
the guibar is not hide, 

2. about keyboard not working.
sometime, i open some website. just open it, and close it, and re-open it. the j,k, ... key. is not work.
I don't not what happen.

**Comment by Jelmerro** [comment]
Guibar is for hiding when you are not using it in Vieb, it won't react to desktop environment updates, as that requires a different method for each and every desktop environment, which would be too much work.

Keyboard scrolling is fixed on github by now, will also be included in the upcoming release.
