### ISSUE TITLE
action.insertAtFirstInput

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#448]
nmap gs <:tabnew https://my.website-login.com/><action.insertAtFirstInput>

I guess the site is not loaded when the command finishes.
Is there a way to make this wait till the site is loaded 
AND
would it be possible to automate the username input once the focus is on gi input mode?

**Comment by Jelmerro** [comment]
Input is indeed not loaded at that time, mappings will not have a "wait" action, as that wouldn't be specific and could freeze actions, but instead we will have #180 in the future.

No, currently not, I would say that this relates to having a built-in password/login manager, see #106.

**Comment by se7en-x230** [comment]
Just for information.
Found a way to automatically login a page i use a lot with xdotool.

**Comment by kbwhodat** [comment]
> Just for information.
> Found a way to automatically login a page i use a lot with xdotool.

Can you share a snippet of how you did it? Does it work for multiple sites? I would actually like to implement the same.

**Comment by se7en-x230** [comment]
> > Just for information.
> > Found a way to automatically login a page i use a lot with xdotool.
> 
> Can you share a snippet of how you did it? Does it work for multiple sites? I would actually like to implement the same.

I created a simple script.
`#!/bin/bash
# netflix_login.sh - script logs into Netflix
#
url="https://my.page.com/login"
email="info@my-page.com"
pwd="my-passwd"
vieb $url & #open browser to
                    # wait for the page to open, the set focus to it
sleep 2
wmctrl -a "Vieb - my.page.com - login"
sleep 8        # allow time to get focus before sending keys
xte "str gi"   #go first input box
sleep 1 # allow time to get focus before sending keys
xte "str $email"
xte "key Tab"
xte "str $pwd"
 xte "key Return"
notify-send "Login Done..."`

And this I call with a keybinding in my viebrc

`"> --- Autologin page 
command! open_ssi <pageToClipboard><:set externalcommand=ssin><action.openLinkExternal>
nmap gs <:open_ssi>`

You need xdotool, xautomation, and wmctl installed for it to work.
PLUS adjust the script to send the right text into the right boxes.

You would need a script per site you want to automate. 
Not a perfect solution as the login data is stored in plain text in the script but for me perfectly okey.
