### ISSUE TITLE
you don't achieve bookmark, I find the best and powerful bookmark method

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#449]
https://github.com/jarun/buku

this is powerful method, any browser, chromium or firefox not better then it.

anyone issue bookmark , you can tell it :+1: https://github.com/jarun/buku

so, you can focus to vim-like ：）

**Comment by newyorkthink** [comment]
![QQ_Image_1668484004723](https://user-images.githubusercontent.com/87791643/201822159-dfad3e55-cb53-4fd0-b026-22e4174d8d61.gif)

**Comment by Jelmerro** [comment]
I'm glad you found a solution for bookmarks, but this is not what the issues are for. You can share this tool either on Telegram, Matrix or Github discussions.
