### ISSUE TITLE
command line: vieb <url>

### ISSUE THREAD

**Issue by newyorkthink** [Jelmerro/Vieb#454]
hi, bro

when i use command line open url :
![Uploading image.png…]()

vieb always have 'new tab'

so, how to when I command line open url, remove this new tab

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/205302895-4cd4aa95-ac1b-4693-a184-144125bceb8f.png)

**Comment by Jelmerro** [comment]
You can now customize this with `replacestartup` and `replacespecial` in the new 9.5.0 release.
