### ISSUE TITLE
Fullscreen not supported

### ISSUE THREAD

**Issue by trufae** [Jelmerro/Vieb#455]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**

I want a command to set the window to toggle fullscreen considering the window controls are hidden i think that would be the best way to do it.

**Alternatives considered**
[TODO A description of alternative solutions or features you've considered, and why they don't suffice.]

**Comment by Jelmerro** [comment]
I do not understand this question, as there is both support for website fullscreen (permission is by default allowed) and you can go to fullscreen with the browser using `F11` with the `<toggleFullscreen>` action. Let me know if you have any issues with this.

**Comment by Jelmerro** [comment]
Closing since it's already there in Vieb and without additional information there is nothing more to be done. Feel free to ask questions if you still have them.

**Comment by trufae** [comment]
Sorry for the late response. I'm on macOS, and F11 key is managed by the window manager to show the desktop. Usually mac apps use the CMD+F for fullscreen, but the last macOS update uses the 🌐+F for that, which works as expected in Vieb, so that confused me. 

Just out of curiosity, how can I trigger the <toggleFullscreen> action? thanks

**Comment by Jelmerro** [comment]
By default `<F11>` will toggle fullscreen but you can map any key to toggle fullscreen with the map commands. For example, to toggle fullscreen with `a` while in normal mode: `:nmap a <toggleFullscreen>`.
