### ISSUE TITLE
Clear history on finer intervals

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#456]
Is there a way to "fine tune" :clearhistoryonquit?

At the moment I set clearhistoryonquit=true as after a while the history function get's to a point where it is almost unusable slow.

Is there a way to implement something like 
clearhistory every 1-10 days/weeks/month ... ?

**Comment by Jelmerro** [comment]
Currently no, it's on my todo list.

**Comment by Jelmerro** [comment]
You can now clear the history with the `clear` command and automatically with the `clearhistoryinterval` setting in the 9.7.0 release.
