### ISSUE TITLE
Exception when calling <openNewTab> with any value in newtaburl

### ISSUE THREAD

**Issue by davidsierradz** [Jelmerro/Vieb#462]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**To Reproduce**

1. Open `vieb --config-order=none --devtools`
2. Set `:set newtaburl=https://google.com`
3. Open tab `:call <openNewTab>`
4. Exception in `:internaldevtools`:

```
11:39:53.599 /nix/store/rn6xv3zy38kwdj6lbavhfsw2mil4fjqd-vieb-9.5.0/libexec/vieb/deps/vieb/app/renderer/tabs.js:490 Uncaught TypeError: stringToUrl(...).then is not a function
    at WebViewElement.<anonymous> (/nix/store/rn6xv3zy38kwdj6lbavhfsw2mil4fjqd-vieb-9.5.0/libexec/vieb/deps/vieb/app/renderer/tabs.js:490:22)
    at WebViewImpl.dispatchEvent (node:electron/js2c/renderer_init:2:26640)
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:17451)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9151)
(anonymous) @ /nix/store/rn6xv3zy38kwdj6lbavhfsw2mil4fjqd-vieb-9.5.0/libexec/vieb/deps/vieb/app/renderer/tabs.js:490
dispatchEvent @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2
```

**Expected behavior**

Open new tab in https://google.com

**Specs**
 - OS: Linux
 - Version: 9.5.0

Thanks!

**Comment by Jelmerro** [comment]
Seems like I left some fallback code there in the many attemps to fix #387, will remove it shortly.

**Comment by davidsierradz** [comment]
Thanks, it's working! But, now I'm seeing some kind of race condition. If I setup a non-empty newtaburl and do something like `:call <openNewTab><openFromClipboard>`, then it will open a new empty tab, try to visit the pasted URL and then the tab goes to the contents of the newtaburl site immediately. Can try to make a video if is not clear enough.

**Comment by Jelmerro** [comment]
I think it should be fixed now with https://github.com/Jelmerro/Vieb/commit/6100cba363b7a665dc56a93e21839baf765b1aab.

**Comment by davidsierradz** [comment]
Confirming that it works, thanks!
