### ISSUE TITLE
On Linux+Xorg, impossible to middle-click-paste commands in command mode

### ISSUE THREAD

**Issue by tejing1** [Jelmerro/Vieb#463]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
In Linux, there are 2 clipboard-like buffers: One for ctrl-c/ctrl-v, and a totally separate one in which you copy by merely selecting text and then paste via middle click. As I spend a lot of time interacting with terminals, which don't support the ctrl-c/ctrl-v buffer as easily (ctrl-c is already used for other things), I almost exclusively use the other method. Also, I'm just used to it.

After entering command mode with `:`, I tried to paste a command into the bar with a middle click, but Vieb instead switched to Explore mode with the url of the current page preset, as if I had pressed `e` on the page in normal mode.

If this is a configurable binding, I haven't been able to find how to configure it, and it's probably a bad default given the interaction with this paste mechanism. I'm not quite sure what the intended usecase would be for such functionality, either.

**To Reproduce**
- Run Vieb in a Linux, Xorg-based environment (I don't know if it also occurs in wayland environments)
- Open command mode with `:`
- Select some text in another window
- Middle click in the navbar text field

**Expected behavior**
Vieb should paste the selected command into the navbar text field.

**Specs**
 - OS: NixOS 22.11
 - Version: Vieb 9.5.0 (installed through nixpkgs PR 207236)

**Comment by Jelmerro** [comment]
This is definitely a bug, not some obscure feature/default! The most obvious reason I can think of is that middle mouse paste assumes that it should switch to explore mode if not in it yet, but does the same for search/command, which it definitely should not do. I'll see if I can find the reason and will fix it.

**Comment by Jelmerro** [comment]
Should be fixed in https://github.com/Jelmerro/Vieb/commit/7d53e3051bde662ffe5ddb3b547c13f043bcb52c, will make a release later this week.

**Comment by tejing1** [comment]
Just tested it out. Looks good to me.
