### ISSUE TITLE
On Linux+Xorg, copying from page to selection buffer gets incomplete text

### ISSUE THREAD

**Issue by tejing1** [Jelmerro/Vieb#467]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When selecting text from a web page in vieb to middle-click paste into another program, often only an initial segment actually gets copied.

This behavior is easiest to see on simple pages like the vieb help pages, where the text that actually gets successfully copied is the text that was covered by the selection before it switched from the blue background "normal" selection color, to the grey-background selection color.

I assume some events in vieb intended to help integrate the selection with visual mode are interrupting the normal transfer to the selection buffer.

**To Reproduce**
1. Open vieb and another gui program in linux+xorg.
2. Open `:help` in vieb
3. Click and hold the left mouse button on text, moving it some distance to select a bit of text quickly.
4. Wait for a bit with the mouse still held. The event you need to wait for should be marked by a change in the background color of the selected text.
5. Move further to select more text.
6. Now release the left mouse button.
7. Middle-click to paste the text into the other program.

**Expected behavior**
The entire current selection should always be what's pasted when middle clicking in another program.

**Specs**
 - OS: NixOS 22.11
 - Version: 7d53e3051bde662ffe5ddb3b547c13f043bcb52c (9.5.0 + some fixes)

**Comment by Jelmerro** [comment]
While this is actually due to the `copyselect` mouse feature being disabled by default, it doesn't make much sense if it still copies some text accidentally. I remove the confusing `copyselect` and make it always copy the selected text to the selection clipboard.

**Comment by tejing1** [comment]
Ah. I assumed `copyselect` was about copying to the non-selection clipboard, though I didn't test it. There is indeed not much point if it still copies part of it.

**Comment by Jelmerro** [comment]
Fixed in the new 9.6.0 release.

**Comment by tejing1** [comment]
Confirmed fixed in 9.6.0. Thanks!
