### ISSUE TITLE
on Linux+Xorg, selected text in the explore-mode navbar gets stuck in the selection buffer

### ISSUE THREAD

**Issue by tejing1** [Jelmerro/Vieb#468]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Selected text in the nav bar from explore mode seems to still be considered "selected" for the purpose of middle-click pastes, even when no longer in explore mode. This even overrides more recently selected text from the page itself.

**To Reproduce**
1. Enter explore mode with `e`, causing the current url to be selected automatically.
2. Press `esc` to return to normal mode. Note no visual indication of the url being selected at this point.
3. Select some text in the page.
4. Middle click to paste into another program.
5. Note that you get the url of the page rather than the text you selected.
6. Return to explore mode with `e`
7. Use the arrow keys to move the cursor, clearing the selection on the url.
8. Press `esc` to return to normal mode.
9. Select some text in the page.
10. Middle click to paste into another program.
11. Note that you now get the text you selected, though possibly only part of it... but that's a different bug.

**Expected behavior**
The selection state in the nav bar from explore mode should not affect anything when not actually in explore mode.

**Specs**
 - OS: NixOS 22.11
 - Version: 7d53e3051bde662ffe5ddb3b547c13f043bcb52c (9.5.0 + some fixes)

**Comment by Jelmerro** [comment]
Could this be because you stay in explore mode if you drag? That is the only cause of this I could find (at least the one not affected by the other bug you opened).

**Comment by tejing1** [comment]
If I understand you correctly, no. As the reproduction steps indicate, I return to normal mode before selecting text from the page.

However, trying to replicate this again just now, I did notice an additional caveat. You have to be pasting into a separate program. Pasting into a text field in the web page itself does not exhibit this behavior, possibly because entering into insert mode somehow changes the dynamics.

**Comment by Jelmerro** [comment]
I cannot reproduce this personally, might be a window/page focus issue. Do you still have it in 9.6.0 with the selection fixes?

**Comment by tejing1** [comment]
I can no longer reproduce it on 9.6.0.
