### ISSUE TITLE
Add back click-anywhere-to-drag-window behavior as an opt-in

### ISSUE THREAD

**Issue by mentalisttraceur** [Jelmerro/Vieb#470]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer asking my question on Github instead of [r/vieb](https://www.reddit.com/r/vieb/), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general) [it helps people like me more to have it here than buried in either of those places]

**What needs to be solved**
Back when I first tried Vieb a few years back, when the window was in normal mode, you could click *anywhere* on the window to drag the whole window around.

Now, in order to drag the window, it seems like we have to click precisely in the upper left corner.

Is there a way to re-enable the old behavior?

**Steps that have been attempted**
Haven't found anything to try - no relevant settings when searching help, etc.

**Comment by Jelmerro** [comment]
It's related to the mouse setting, back in the day the mouse was not enabled by default and was a simple toggle, now it is enabled by default with a list of features you want to enable. Previously I disabled the mouse by making everything a drag region, now the mouse is properly blocked from doing anything if a specific feature is disabled. This means that currently this feature is no longer present, as I have heard from most people who gave feedback that they found it confusing and annoying that it stil did something even if the mouse was disabled. Given that you are the first to miss this feature years after it's been removed is a valid indicator for me that it was the right choice to disable this by default. However, we could add back a setting to optionally re-enable this behavior if the mouse is disabled. Such as a `mousedisabledbehavior` setting, that can be set to `nothing`, `drag` or optionally more values in the future, to indicate what the mouse should do if the feature of the thing it's clicking is disabled. What are your thoughts?

Actually, since this is just css you could already achieve this currently, by adding `* {-webkit-app-region: drag;}` to a colorscheme, without needing any additional settings or changes to Vieb. Let me know if this is preferred or you would rather have a setting for it.

**Comment by mentalisttraceur** [comment]
Oh cool, I didn't know I could solve it with color scheme CSS, thanks! I'll take a look at that and get back to you.

> most people who gave feedback that they found it confusing and annoying

Yeah it was confusing and annoying for me at first too (because I was following the habit for most GUI apps where click-drag *selects text*). I didn't realize I liked it until I got used to it and then suddenly it was gone.

> Given that you are the first to miss this feature years after it's been removed is a valid indicator for me that it was the right choice to disable this by default.

Probably the right choice, yeah. For what it's worth, I started to miss it as soon as it was removed, I just never said anything because Vieb hasn't yet become a daily driver for me - I open Vieb once a year or so to re-check if we're a better fit now.

**Comment by mentalisttraceur** [comment]
I recommend a setting *if* you are treating it as an officially supported feature, because then it's more unambiguous and discoverable as not-just-a-hack-that-works-for-now.

Either way, I recommend adding a small note in the built-in help to let people know you can do this. I searched for words like "drag", "reposition", "window", "move", and so on, first in the config autocomplete and then in `:help`.

**Comment by Jelmerro** [comment]
I'll add a setting, even if it just toggles this css line, as that is more discover-able than a css one-liner in a github issue.

If you are missing features for making it a daily driver do let me know! Feel free to open many more issues/feature requests if there are no existing ones for them yet.

**Comment by Jelmerro** [comment]
This behavior is now available again using the `mousedisabledbehavior` setting, which controls what the mouse does when you interact with a disabled element. By default, it does nothing, but can be set to "drag" as well. You also need to disable the "mouse" with its setting to be able to click on elements that are disabled, as the mouse is by default enabled for all elements. In short, if you want to disable the mouse completely and make everything a drag region do:
`:set mouse= mousedisabledbehavior=drag`

**Comment by mentalisttraceur** [comment]
Thank you! Sorry for the delayed reply.

> If you are missing features for making it a daily driver do let me know! Feel free to open many more issues/feature requests if there are no existing ones for them yet.

Cheers. So the #1 thing [you've already said was inherently technically difficult](https://github.com/Jelmerro/Vieb/issues/141#issuecomment-1323894874): I think I need multiple windows in a way that is fluid and a keystroke away - most crucially, it can't require prior setup: I need a keystroke's worth of impedance between "I'd like this page to move/open into a separate window" and it opening/moving to a separate window.

<details><summary>[click to expand long mind-dump about why]</summary>

I often find myself wanting to split off multiple browser windows on multiple monitors or in multiple "workspaces"/"virtual desktops" or both, in a way that isn't solved by Erwic mode - spontaneously, on a case-by-case basis which is neither site-oriented nor identity-oriented.

For example, I'll be on GitHub, and decide I want to pop another GitHub tab onto a side monitor (maybe I want to look at a commit's diff while typing a comment or whatever), or multiple pages of documentation that I want within view at once... I know Vieb has splits, and maybe that's actually perfect if I give it enough of a chance - I do intend to eventually really try it, but the hard thing is that that's an additional per-tool learning curve - I *know* how to use my window managers, on most systems I eventually customize the window manager, and if I can manipulate things with my window manager then the same muscle memory and cognition works across all my things.

For a counter-example, Qutebrowser has a config switch where everything opens as a window instead of as a tab, and I haven't turned that off ever since I turned it on years ago -  because I can manage my tabs the same way I manage everything else - fuzzy search, switch to, close, etc - *all with the same interface* for shells/terminals/REPLs, web pages/apps, text editor instances, etc. When I think of an improvement for managing my things, I can implement it once, and then it works for *everything*, instead of me having to re-implement it once in my browser, once in Neovim, once in Tmux, etc. (That's the theory anyway - in practice I cycle between incrementally implementing something closer to it, and putting the effort on pause so that I can get real work done.)

Also, splitting stuff into windows helps me use my spacial memory/thinking as a kind of external working memory to help me keep track as I recurse/branch in investigation/research/how-do-I-[...]/where-is-[...]. Not always, but when things get difficult enough (like when I'm learning a new hairy/busy/big code base whose coupling hygiene and I have to trace the code through 5-10 files just to figure out what the whole behavior of something is), it really helps - and sometimes that looks like spontaneously creating 5+ new GitHub windows or whatever.

</details>

To be clear, I don't mind implementing this myself - for example, if there is a way to tell Vieb to flush current state so that I can hit the default data-dir with a recursive copy, and then launch an Erwin window on that copy, and I could just bind that to a keystroke, I think that would be fine.

But I'd really love to hear what you do *instead* - how do you fulfill the same needs/wants, etc?
