### ISSUE TITLE
Support of WebAuthn / Security Key

### ISSUE THREAD

**Issue by elquimista** [Jelmerro/Vieb#483]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
I like Vieb very much (thank you for all your efforts put into this). However there are a few things that prevent me from using it as my main default browser for now.
* Incognito mode
* Multiple profiles
* Chrome extensions
* Bookmarks
* Being able to log into Google services
* DRM support
* Security key support

I have figured out most of the stuff above (workaround or find it ok to live without) but the last one (security key support) is something I can't compromise. Is there any plan / roadmap to ship this feature?

**Comment by elquimista** [comment]
@Jelmerro - thanks for your quick response. When I tried a website that is supposed to ask for my yubikey (it does in Chrome and Brave), it never asked for it in Vieb. No notifications, just plain white blank page. But I will check `h :notifications` in the help page further. Thanks again for your guidance.

**Comment by elquimista** [comment]
I already checked console in the dev tools and there is no error.

**Comment by elquimista** [comment]
Never mind. I just now realized my yubikey's light is blinking when I am on the login page. It's just not showing the familiar webauthn prompt I used to get in other Chromium browsers. And when I touched my yubikey while it was blinking, login worked!

However, it didn't ask for my PIN code of my yubikey. In other Chromium browsers, they ask for PIN code when I touch my yubikey.

**Comment by elquimista** [comment]
Let me know if you have any idea about this. Otherwise, I am happy to close this issue for now.

**Comment by Jelmerro** [comment]
I'm glad it's working for you now too! I think it's just the stripped Electron implementation of the key auth, since there is no chromium UI in Electron by default, they probablya figured just having support without the UI was more useful than requiring users to build support for it from scratch. I would expect there to be Electron issues regarding the lack of PIN, but all I can find are issues related to lack of support, but it's supported already...
