### ISSUE TITLE
`restoretabs` loses tabs with local files

### ISSUE THREAD

**Issue by tejing1** [Jelmerro/Vieb#484]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
I keep local mirrors of a few sites on my hard disk, and browse them with vieb at times, but have found that when quitting and restoring with `restoretabs` set to `all`, vieb fails to restore these tabs, despite other tabs being restored properly.

**To Reproduce**
- Have a running instance of vieb with `restoretabs` set to `all`
- Save and/or create an html file on the local disk
- Add a tab viewing that file to the running instance with `vieb foo.html`
- quit (`ZZ`)
- restart vieb, and see that specific tab is not restored

**Expected behavior**
The tab should be treated identically to online tabs and restored.

**Specs**
 - OS: NixOS 22.11
 - Version: Vieb 9.7.1

**Comment by Jelmerro** [comment]
Fixed in 10.0.0 :tada:

**Comment by tejing1** [comment]
Confirmed fixed. Thanks!
