### ISSUE TITLE
`action.nextPage` no longer working on some pages

### ISSUE THREAD

**Issue by tejing1** [Jelmerro/Vieb#488]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Describe the bug**
`action.nextPage` (and of course `action.previousPage`) no longer work on, for example, [royalroad chapter views](https://www.royalroad.com/fiction/62087/saintess-summons-skeletons-a-holy-necromancy-litrpg/chapter/1066845/chapter-1-un-holy-beginning). These pages use a `<link rel="next" href="...">` tag in the header to signal where to find the next page. Vieb 9.7.1 followed these just fine, but Vieb 10.0.0 does not.

**To Reproduce**
- View [this page](https://www.royalroad.com/fiction/62087/saintess-summons-skeletons-a-holy-necromancy-litrpg/chapter/1066845/chapter-1-un-holy-beginning) in Vieb 10.0.0.
- Trigger `action.nextPage` (`]` in normal mode)
- In 10.0.0 it will not work, in 9.7.1 it will

**Expected behavior**
`action.nextPage` should follow the same links it did before.

**Specs**
 - OS: NixOS 23.05
 - Version: 10.0.0

**Comment by tejing1** [comment]
If I'm reading the code right, it looks like a sanity check was added to the function that action calls, which required the element to be `<a>`, thus disallowing `<link>`.

**Comment by Jelmerro** [comment]
Fixed in 10.1.0 :tada:

**Comment by tejing1** [comment]
Confirmed. Thanks!
