### ISSUE TITLE
Google doesn't like vieb

### ISSUE THREAD

**Issue by romgrk** [Jelmerro/Vieb#49]
![Screenshot from 2020-05-29 19-36-25](https://user-images.githubusercontent.com/1423607/83313286-90f75d80-a1e3-11ea-92ae-29a6ca285826.png)

**Comment by Jelmerro** [comment]
This is a duplicate of #48 and it's not something that Vieb can actually fix. If enough people reach out to google to report this, maybe they will fix it eventually...

**Comment by romgrk** [comment]
Would serving them a fake user-agent solve the issue?

**Comment by Jelmerro** [comment]
It's already using the same user agent as Chrome.

**Comment by romgrk** [comment]
Damn! And how do they detect a non-chrome browser?

**Comment by Jelmerro** [comment]
I have no clue, but it's ridiculous of them to block browsers that they can't detect as chrome (or firefox presumably).
