### ISSUE TITLE
[Markdown viewer] Special character encoding issues starting with Vieb 10

### ISSUE THREAD

**Issue by Melandel** [Jelmerro/Vieb#494]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Describe the bug**
When viewing markdown files, special characters such as the apostrophe in `don't` and the emoji `🚫` are weird:
* `don't` becomes `donâ€™t`
* `🚫` becomes `ðŸš«`

**To Reproduce**
* create a markdown file containing the sentence `Hello don't you 🚫 this! :)`

**Expected behavior**
`Hello don't you 🚫 this! :)` is displayed by the markdown viewer

**Specs**
 - OS: Windows10
 - Version: Vieb 10.0 and Vieb 10.1

**Additional notes**
- It works fine on Vieb 9.7

**Comment by Jelmerro** [comment]
Fixed in 10.1.1 :tada:
