### ISSUE TITLE
imap jk <toNormalMode> not sending j with a delay

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#496]
My settings are:
`set timeoutlen=1500`
`imap jk <toNormalMode>`

 jk is also set as toNormalMode in cmap and emap

This worked fine till the last update j typing has a slight delay but works. 
That is still the case in cmap and emap but imap times out without sending the j letter. Meaning I cant't type j in insert mode but it works in the other modes.

**Comment by Jelmerro** [comment]
Fixed in 10.1.1 :tada:
