### ISSUE TITLE
Horizontal navigation problem

### ISSUE THREAD

**Issue by piotr-marendowski** [Jelmerro/Vieb#498]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Describe the bug**
On sites like Mangadex, and Bato.to (manga readers, where you can click left/right arrow keys to go to the next page), Vieb doesn't scroll pages horizontally, while Qutebrowser and Firefox do. Up/Down arrow keys work just fine.

**To Reproduce**
Try to use left/right arrow keys on these sites.

**Expected behavior**
Pages turn normally as expected.

**Comment by Jelmerro** [comment]
I don't fully understand the issue, since it lacks steps to reproduce. Is this inside insert mode and do you have an example page where this happens?

**Comment by piotr-marendowski** [comment]
In normal mode, go to for example [Mangadex](https://mangadex.org/) and try to turn pages. That doesn't seem to work as on other browsers. I also couldn't find any site that is not center aligned in way that I could zoom and try to move horizontally.

**Comment by Jelmerro** [comment]
Normal mode arrow keys scroll the page, they don't send keyboard input to the website, if you want this, use insert mode. This strong mode and thus shortcut separation was a big reason for starting Vieb over other mentioned projects, hence why its behavior is unique compared to the mentioned browsers. Basically you are only sending these arrow keys to Vieb, which uses them to scroll the page vertical/horizontal, not to send the keypress to the website, you first need to enter insert mode with `i` to have your keys send to the page.

**Comment by piotr-marendowski** [comment]
Insert mode doesn't scroll them either. Still only vertical scroll works.

**Comment by Jelmerro** [comment]
If I go to insert mode and then use the left and right arrows I get the next/previous pages, is this not what should be happening?

**Comment by piotr-marendowski** [comment]
Thanks a lot, it started to work as expected! Guess I'm going full time Vieb now.

**Comment by piotr-marendowski** [comment]
Closing
