### ISSUE TITLE
Vieb starts XWayland server even though wayland support is enabled

### ISSUE THREAD

**Issue by abvee** [Jelmerro/Vieb#499]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [X] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Describe the bug**
According to [this](https://github.com/Jelmerro/Vieb/issues/265) issue, which is marked as closed, wayland support can be enabled by passing these command line arguments `--enable-features=UseOzonePlatform` and `--ozone-platform=wayland`. However, Vieb still runs Xwayland when it is started.

**To Reproduce**
I am using the AppImage, so I downloaded the AppImage from releases, and ran it like so:
```
Vieb_x86_64.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland
```
However, running `pgrep` reveals that Xwayland has been started:
```
watch 'ps $(pgrep -i xwayland)
___
    PID TTY      STAT   TIME COMMAND
  61710 tty1     Sl+    0:00 Xwayland :0 -rootless -core -terminate 10 -listenfd 29 -listenfd 30 -displayfd 103 -wm 95
```
I thought this was an AppImage issue, so I built Vieb from [this](https://aur.archlinux.org/packages/vieb-bin) AUR repo, and ran it normally, but the behaviour was the same.

**Expected behavior**
Vieb should not run Xwayland when passed those arguments ? Perhaps it is a part of Xwayland that is using Xorg ? I don't really know how Vieb works, I just downloaded it. If this isn't an issue, then I'm sorry for wasting time.

For the record, Vieb does say that it passes all the flags to chromium, so idk what's causing this.

**Specs**
 - OS: Arch Linux
 - Version: 10.1.0
 - Compositor: sway (wlroots)

**Comment by Jelmerro** [comment]
I believe this is not specific to Vieb, but rather an Electron issue. It seems like this is the issue in their repo: https://github.com/electron/electron/issues/28436

**Comment by abvee** [comment]
Thanks, hopefully fixed soon :D
