### ISSUE TITLE
Main process gets stuck when entering Follow mode on login.mailbox.org

### ISSUE THREAD

**Issue by gardenappl** [Jelmerro/Vieb#501]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Describe the bug**
When I go to https://login.mailbox.org and press 'f', Vieb displays hover tooltips for the handful of links that are on that page, but then just gets completely stuck until I kill the process. What's weird is that:

- As I said, there are not many clickable elements on the page. (I did experience lag when 'following' on pages with tons of links (https://vimhelp.org/version8.txt.html), but even then that usually gets resolved in a few seconds.)
- When I look at htop it looks like it's specifically the main process that gets stuck on 100% CPU usage. (Meanwhile with the vimhelp.org example CPU is used by a process with `--type=renderer`)
- The lag happens *after* it displays the hover tooltips, not before.

**To Reproduce**
* Go to https://login.mailbox.org
* Press 'f'

**Specs**
 - OS: Arch Linux
 - Version: `vieb-bin 10.1.0-1` from the AUR

**Comment by Jelmerro** [comment]
Fixed in 10.1.1 :tada:
