### ISSUE TITLE
Implement RobotJS: prevent side effects and automate text selection in insert mode

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#51]
Hi, this is a very good web browser!

I have a question, how do I map key to feed keys in insert mode.
For example, I want to rebind `<a-h>` to `<home>`. How could I achieve that. The following doesn't seem to work.
```vim
imap <a-h> <home>
```

**Comment by Jelmerro** [comment]
Thanks, it seems that the input events are not send to the page while in insert mode. I will work on a fix.

**Comment by Jelmerro** [comment]
Also, depending on what you wanted to do by mapping to `<Home>` in insert mode, you could also think of mapping to `<action.scrollTop>` or `<pointer.startOfPage>` instead.

**Comment by ipod825** [comment]
I intended to map it to beginning of line.

Also, after trying the new patch in the master branch. It works with a problem.
In plain input field, it works as expected. However, in page like google doc, it triggers the mapping but also send the keystroke to the page, triggering side effects. For e.g., in google doc
```
imap <a-h> <home>
```
brings me to the beginning of line but also brings up the help menu as `<a-h>` is the shortcut for that.

**Comment by ipod825** [comment]
All of the following mappings still doesn't work:
```vim
imap <c-a-h> <c-left>
imap <c-a-l> <c-right>
imap <c-h> <left>
imap <c-l> <right>
imap <c-k> <up>
imap <c-j> <down>
imap <c-s-a-h> <c-s-left>
imap <c-s-a-l> <c-s-right>
```

**Comment by ipod825** [comment]
In general, do you think is it possible to introduce another mode `InputfieldNormal` mode?
I like the pointer mode, but it doesn't really enables you to edit stuff like in vim.

In `InputfieldNormal` mode, I expect `w` moves the cursor using `<c-right>` and `b` moves the cursor using `<c-left>` and  `k` moves the cursor using `<up>` etc. And `i` brings me back to insert mode.

**Comment by Jelmerro** [comment]
Regarding the arrow key mappings not working, this is likely related to [this](https://github.com/electron/electron/issues/12513). It is probably sending the arrow keys to the webview, but it is only in that context that they will be executed. An electron maintainer is suggesting to use [robotjs](https://robotjs.io/) to achieve the interaction with native elements that you are looking for with these mappings.

The mapping you mentioned above using `<a-h>`, it's not actually "sending" the keys to the page, they are pressed within the page and are send back to the renderer. I am already calling the preventDefault of the event if it's bound to an action, but if that's not working I don't know what else I can do to resolve that (at least within the current insert mode mapping structure).

I think the optimal solution would be to use robotjs to send the events to the webview. This would reduce the amount of calls between the webview and renderer to do the mappings, and would solve both of the annoyances that you mention as part of this bug.

**Comment by Jelmerro** [comment]
I just made a fix to prevent the side effects for mappings in https://github.com/Jelmerro/Vieb/commit/63a751dc65af4e0980e86d8d3d772af342244a3e. In the end, I didn't even need RobotJS, but simply needed to call preventDefault in the main thread on the input event.

Please do let me know if this issue is also solved for you when running the latest master, or wait for the next stable release.
