### ISSUE TITLE
Add pinned tabs

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#52]
It would be nice to pin a tab such that it stays minimized on the left.

**Comment by Jelmerro** [comment]
This is a good suggestion, though there is one thing I want to address before working on this.

The definition of minimized remains a bit vague in Vieb regarding the tabs. Let me give an example: If you set the minimum tab width (mintabwidth) to 0 and you open 100 tabs, what size should the "minimized" tabs appear as compared to the really small other tabs? Or if you only have a two tabs open, one minimized and one pinned, what would be the expected width of both of them?

Perhaps we should not call them minimized but merely "pinned" and have all pinned tabs be of the same fixed width (just the icon) without being affected by the mintabwidth setting and the amount of open tabs. Any thoughts on this or other suggestions?

**Comment by ipod825** [comment]
> Perhaps we should not call them minimized but merely "pinned" and have all pinned tabs be of the same fixed width (just the icon) without being affected by the mintabwidth setting and the amount of open tabs. 

Indeed, this seems to be what chrome does.

**Comment by Jelmerro** [comment]
Alright, let's go with that for Vieb as well then. I will self-assign this when I find the time to work on it.
