### ISSUE TITLE
Wrap around to the first or last tab with the previousTab and nextTab actions

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#53]
It would be nice if <action.nextTab> at the last tab go to the 1st tab and vice versa.

**Comment by Jelmerro** [comment]
This is a nice suggestion and definitely something I will be adding as a setting in the future.

There already is a setting named "taboverflow", which defines what to do when there are too many tabs to fit in the tabbar. I can imagine that people will confuse this new setting with taboverflow if the names would be too similar, so if you have any suggestions on that, be my guest.

**Comment by ipod825** [comment]
`tabwrapmove`, `tabcycle` ?

**Comment by Jelmerro** [comment]
I like `tabcycle` because it doesn't share any part of it's name with the potential values for `taboverflow`. Let's call it `tabcycle` for now.

**Comment by ipod825** [comment]
It would be nice if this is the default. Most browser behaves like this. Even vim behaves like this.

**Comment by Jelmerro** [comment]
Totally agree. The next release will include the `tabcycle` toggle enabled by default.
