### ISSUE TITLE
:set mouse= does not change it's value

### ISSUE THREAD

**Issue by milomouse** [Jelmerro/Vieb#538]
**Checklist**
- [*] I searched the `:help` documentation using `/` for helpful information
- [*] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [*] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [*] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Describe the bug**
Using :set mouse= does not change it's behavior, no matter what array I supply it. The current value on the help page always shows "all", and I maintain full mouse control.

**To Reproduce**
Using Vieb 11.0.0, I issue the command :set mouse=
I have also tried giving it a non-nil value such as from the example page :set mouse=scrollzoom,oustsideinsert,newtab
This is tested with and without a viebrc file.

**Expected behavior**
I expect it to work as it did in Vieb 10.6.0 (where it works correctly), issuing :set mouse= would disable all mouse control within Vieb and update it's current value on the help page from "all" to "".

**Specs**
 - OS: Gentoo Linux (x86_64)
 - Version: 11.0.0

**Comment by Jelmerro** [comment]
Can confirm, it seems the mouse setting is completely useless in V11 at the moment, I will look into this, hopefully later this week, thanks for reporting this.

**Comment by Jelmerro** [comment]
Should be fixed in https://github.com/Jelmerro/Vieb/commit/969b5bc35ae41440997f6e94b30dc4adbc23825a, a release is not planned soon, but definitely within a month.

**Comment by Jelmerro** [comment]
Implemented in 12.0.0 :tada:
