### ISSUE TITLE
Not working on raspberry pi

### ISSUE THREAD

**Issue by iamcxds** [Jelmerro/Vieb#544]
**Describe the bug**

When starting Vieb, it comes with multiple times of errors:
```
[22968:0225/191806.333526:ERROR:gbm_wrapper.cc(75)] Failed to get fd for plane.: No such file or directory (2)
[22968:0225/191806.333651:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
```
Then Vieb will manage to open, but unusable.
After some searching, this might relate to GPU or something.

**To Reproduce**

Install with arm64 Deb package.

**Specs**
 - OS: Raspberry Pi OS
 - Version: Vieb-11

**Comment by Jelmerro** [comment]
These are not Vieb errors, these are Chromium internal errors, I have found no way to remove them from being logged using the Electron project, but they are usually not a big problem, let alone one that Vieb can/should solve. These are entirely unrelated to any of Vieb's code, and should happen in any Electron/Chromium based project, if they have not disabled the logging.
