### ISSUE TITLE
Search specific websites directly using website name prefixes

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#55]
Reference:
https://www.techrepublic.com/article/pro-tip-add-custom-search-engines-in-chrome-for-more-efficient-searching/

**Comment by Jelmerro** [comment]
Could you elaborate on this feature request in a bit more detail? There already is a setting for changing the search engine simply named "search". If you want to switch between two or presumably more, I would recommend to add a custom command or map a new keybinding.

**Comment by ipod825** [comment]
It let's you two type say `github` on the addressbar, and then pressing `tab`.
You then enter what ever you want to search in github. Pressing `enter`, it will directs to the search page with github searching result of your query. Of course you need some kind of configuration to map `github` to the search query url of github.

The pro of this is that you don't need to load the githubt home page and type your query there, saving one page loading time. Also, you don't lost your current context whey you type the query.

Pressing `tab` isn't really necessary to be implemented. In qutebrowser, it just requires you type `github` followed by a space and a query.

**Comment by Jelmerro** [comment]
I also don't see the added value of these domain searches over [duckduckgo bangs](https://duckduckgo.com/bang) (such as appending `!github`) or worst case appending the search with `site:github.com`. Although if more people think that such a search prefix would improve Vieb, feel free to make a PR to implement this, as I probably won't pick this up myself any time soon.

When adding this, please do not make it automatically activate, because it can prevent people from searching for certain things. For example, it would not be an option to search for `github guides` on duck, without being redirected to search for github repositories named "guides".

**Comment by InconsolableCellist** [comment]
There are a few big benefits over DDG bangs: you can set your search engine to something other than DDG but still have these searches work; you can customize them; and your search isn't going through a middleman when that's not necessary.

I personally greatly prefer Startpage to DDG (and was going to try and figure out how to change the default search engine to reflect this).

DDG also doesn't use the same bang keywords as you might want to use, and might be missing sites.

**Comment by Jelmerro** [comment]
You can change Vieb's search engine with the `search` option, see `:h search` for details.

I agree that there are benefits to implementing this compared to using DDG, most of which you mention in your comment. It's just that I won't use this feature myself, and as such probably won't spend time on implementing this in the near future (hence the "help wanted" label on this issue).

**Comment by InconsolableCellist** [comment]
@Jelmerro Github doesn't seem to have a private chat option. I'm taking a crack at implementing this but I'm wondering if you can tell me the proper way to log trace statements in Vieb? To a log or STDOUT/STDERR. `console.log()` doesn't seem to do it when I run with `npm`

**Comment by Jelmerro** [comment]
`console.log` works, but it depending on where you log, you need to check different places. For example, the `app/index.js` file is running the main thread, which will log to the terminal. Most other files are part of the renderer, which will log to Vieb's internal developer tool console, which can be opened with the `:intervaldevtools` command, or with the `--debug` startup option. With the developer tools you can also add breakpoints and that kind of stuff that you might know from debugging websites with the devtools.

**Comment by InconsolableCellist** [comment]
Excellent! Thanks. Having the console and debugging makes it so much easier.

**Comment by Jelmerro** [comment]
This has been implemented by @InconsolableCellist in #110 :+1:
