### ISSUE TITLE
org.freedesktop issue during flatpak update

### ISSUE THREAD

**Issue by Femto-godhand** [Jelmerro/Vieb#572]
Hello everyone,
I have this little problem during flatpak update, I get this message:

> Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
>    org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> Info: applications using this runtime:
>    dev.vieb.Vieb
> 
> Info: runtime org.freedesktop.Platform.GL.default branch 22.08-extra is end-of-life, with reason:
>    org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> Info: applications using this extension:
>    dev.vieb.Vieb
> 
> Info: runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
>    org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> Info: applications using this extension:
>    dev.vieb.Vieb

**To Reproduce**
execute flatpak update on terminal

**Specs**
OS: Void Linux x86_64
Kernel: 6.6.54_1

Best regards.

**Comment by Jelmerro** [comment]
Seems like I need to update 22.08 to 24.08, I've merged a PR that does just that, but I don't know if the current 12.0.0 release will be updated automatically. If not, the next release will have this fixed :tada: You can also install this test build from https://github.com/flathub/dev.vieb.Vieb/pull/28.
