### ISSUE TITLE
Make it possible to hide navbar and tabs

### ISSUE THREAD

**Issue by octavz** [Jelmerro/Vieb#58]
A lot of the vim users are keyboard centric people and they would use Vieb, but in the same time we use things like window managers based on splits, xmonad, i3wm, awesome, etc, these allow to tile apps. 

Having tabs and navbar is occupying a lot of precious space, the navbar should appear only when typing an address (ie press E, type <cr>, hide, see omnibar behavior for example in surfingkeys), and tabs should have the option to be hidden all the time.

Thank you for your work.

**Comment by Jelmerro** [comment]
These sound like good suggestions. Based on that, I am considering to add two new settings to Vieb:

- `showtabs` - A toggle indicating if tabs should be shown. On by default, when turned off, the tabs are not displayed in the navbar at all, which would result in the navbar becoming half the size.
- `autohidenavbar` - A toggle to auto hide the navbar when outside of explore, search or command mode. Disabled by default, but if enabled, it would be similar to the F11 experience in most other browsers (although system taskbars would still be visible if they are not configured to auto-hide).

One other thing to note, if `autohidenavbar` would be added and enabled, there would be no location to show the current mode of Vieb. Do you think of this as a problem, or is that a price you are willing to pay for this feature? We could also think of alternative ways to display the mode when the navbar is hidden.

I would like to hear your thoughts regarding my interpretation of your suggestions. Please let me know if adding these two settings is what you are looking for.

**Comment by ipod825** [comment]
You could make them visible on events.
In qutebrowser, there's a setting `tabs.show_switching_delay`. When tabs are hided, switching tabs would show the tabs for `tabs.show_switching_delay` milliseconds.
Similarly, the mode (status) bar can be set visible when mode is switching or in focus.

Also a question, why is native full screen (<F11> that hides system status bar) not supported? Is there anything in electron preventing you from implementing it?

**Comment by Jelmerro** [comment]
That's a good suggestion, should I add that to the list of settings to be added for this ticket? I think all options are covered with that.

Regarding the lack of fullscreen, I have never used that in a regular browser and I don't personally know many people that do use it. Especially combined with these new settings, there really isn't anything that Vieb will be showing aside from the actual page. If you wanted to remove the system taskbar, you could just set it to automatically hide in your desktop settings, or am I missing something here?

**Comment by ipod825** [comment]
> That's a good suggestion, should I add that to the list of settings to be added for this ticket? I think all options are covered with that.

Yes. Please.

> Regarding the lack of fullscreen, I have never used that in a regular browser and I don't personally know many people that do use it. Especially combined with these new settings, there really isn't anything that Vieb will be showing aside from the actual page. If you wanted to remove the system taskbar, you could just set it to automatically hide in your desktop settings, or am I missing something here?

I don't know other people, but I frequently use full screen when using browser e.g. when playing web games, reading novels. Because I have a small screen, any single piece of space is valuable and enjoyable. I don't like to hide the system status bar as it shows the time (yes, that's the only reason I don't automatically hide it because moving my eyeballs is quicker than moving the mouse or pressing a key to wake up that status bar. That said, when playing games or reading novels, I don't care much about time so I prefer to hide it to gain more space).

**Comment by Jelmerro** [comment]
Okay, thanks for the explanation. Here are some more things that we should consider before starting work on this:

- How would a fullscreen mode compare to using these three new settings?
- Is there a fourth setting we need to add for the fullscreen mode?
- Can these settings be grouped, or do they need to be separated?
- Can we rethink this whole concept to make use of a string setting instead of four toggles?

You don't have to answer all of these questions, but these are the things that I still do not have a clear view on regarding all these different user interface options.

**Comment by ipod825** [comment]
My suggestions:

`status_bar_hide` = `always`, `never`, `auto`
`tab_bar_hide` = `always`, `never`, `auto`
`tab_bar_auto_hide_delay` = ? milliseconds
 
```vim
let g:in_fullscreen = get(g:, 'in_fullscreen', v:false)
let g:user_status_bar_hide = ''
let g:user_tab_bar_hide = ''
function action.fullscreen()
  if !g:in_fullscreen
      let g:in_fullscreen = v:true
      let g:user_tab_bar_hide = &tab_bar_hide
      let g:user_status_bar_hide = &status_bar_hide
      set status_bar_hide = 'auto'
      set tab_bar_hide = 'auto'
      " perform full screen operatoin
  else
      let g:in_fullscreen = v:false
      set status_bar_hide = g:user_status_bar_hide
      set tab_bar_hide = g:user_tab_bar_hide
      " perform reverse full screen operatoin
  endif
endfunctoin
```

**Comment by Jelmerro** [comment]
That looks almost right, but I have two more questions:

- This does not address the system taskbar being hidden like you mentioned earlier? (so the fullscreen mode)
- What would be the purpose of `status_bar_hide=always`, wouldn't this prevent you from seeing what you are typing in command mode for example?

**Comment by ipod825** [comment]
The `" perform full screen operation` and `" perform reverse full screen operation` should take care of the system wide fullscreen operation.

> What would be the purpose of status_bar_hide=always, wouldn't this prevent you from seeing what you are typing in command mode for example?

I don't know. But probably someone would favor it. Vim also allows user to always hide status bar. So you never know.

**Comment by Jelmerro** [comment]
I'll think about this ticket some more, and make a new comment here when I get some new ideas, for now I'll wait a bit with implementing this.

**Comment by octavz** [comment]
I am using the browsers w/o any UI to keep them WM friendly, I am not bothered about the lack of information regarding MODE.

I'm using mostly Vivaldi, it allows you to hide everything, pressing ctrl+l shows the address bar, it also has shortcuts for viewing tabs, or downloads or full address bar (which is required because you also have extensions there and other stuff apart from address bar)

Also some infos are overlayed, ie links addresses on hover when there is no status bar, tbh Vivaldi has everything I need if I combine it with surfingkeys, I would only switch if the alternative would be lighter (less memory footprint).

**Comment by Jelmerro** [comment]
Okay, I will implement this as follows:

- `guinavbar` - The visibility of the navbar, can be set to: "always", "onupdate", "oninput" and "never". The "onupdate" value implies that you also want it to be visible when entering input.
- `guitabbar` - The visibility of the tabs/tabbar, can be set to: "always", "onupdate" and "never.
- `guihidetimeout` - The amount of milliseconds before automatically hiding either of the two bars after updates.

I chose the "gui" prefix to group these settings, similar to how gui-specific settings in Vim are always prefixed.

Separate from these settings, I will add a new action to toggle actual fullscreen. When fullscreen is active, the "always" values of the visibility settings will automatically be converted to "onupdate", which in a way is similar to how for example Firefox implements fullscreen.

Regarding the mouse and these settings, I will try to make the tools also appear when the mouse is moved on the top part of the page, but I am not entirely sure if this is possible. Using the mouse would only show the bars for which the visibility is not set to "never".

To address the feedback of @octavz a bit, all of Vieb's settings and actions can be mapped to the keyboard with the `:map` command (and mode specific ones). So the same behavior that you have in Vivaldi would be possible in Vieb after introducing these "gui" settings.

I can't comment on the memory footprint as I have never used Vivaldi, so feel free to do your own comparison.

**Comment by Jelmerro** [comment]
After working on the initial implementation locally, I noticed that the same preferences might not apply to fullscreen, and that the logic I proposed in my earlier comment is not sufficient for all use cases. Therefor I will also be adding `guifullscreentabbar` and `guifullscreennavbar`, which will be the same as as the other gui visibility settings but specifically for when in fullscreen.
