### ISSUE TITLE
Make a setting to open tabs in the background using the middle mouse button

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#60]
There should be an operation to open link in new background tab without losing focus of the current tab.

In all other browser, clicking a link with three finger does this. Also in vim-inspired browser (extensions), they usual have `startFollowNewTab` operations open the link in a background tab instead of immediately go to the new tab. I would suggest either change the behavior of `<action.startFollowNewTab>` or add another action `startFollowBackgroundTab`

**Comment by Jelmerro** [comment]
This is already possible if you hold shift while clicking on the relevant keys. The page will open in a new tab without switching if you do this, and you will even remain in follow mode for as long as you keep holding shift upon keypresses. If you think that this is not described clearly in the help page feel free to make a PR to improve the wording.

**Comment by ipod825** [comment]
It doesn't behave like you describe. `shift`+click still focus on the new tab.
I use `i3` not sure if that cause the problem. I'll test with other window manager later.

Also, it other browser, it's usually `ctrl`+click to open tab in background. `shift`+click usually opens new tab in a new window.

**Comment by ipod825** [comment]
In cinnamon, `shift`+click still focus on the new tab.

**Comment by Jelmerro** [comment]
What kind of click are we talking about here, is it a mouse click? If so, the ability to click on follow mode links is not what I exactly what I meant. If you use the keyboard to press the relevant keys while at the same time holding shift, it should definitely open them in a new tab while remaining in follow mode. If you want to use the mouse to do the same thing, you don't have to combine it with follow mode. Although combining follow mode with the mouse could indeed be improved if that is what you are talking about.

**Comment by ipod825** [comment]
Oh. I mis-uderstood. I see now that follow mode can open new tab in background.
I was mainly discussing mouse click. Middle mouse click (or `ctrl`+click) in other browser open link in a new background tab while Vieb opens it in a new tab and focus on the new tab. There seems to be no way to just use mouse to open link in a new background tab.

**Comment by Jelmerro** [comment]
That is correct. I could change the behavior of the mouse click to open in a background tab instead of a foreground tab, if that is more in line with other browsers. Let's make it a setting while we are at it.
