### ISSUE TITLE
vieb can't be closed by regular close request

### ISSUE THREAD

**Issue by andys8** [Jelmerro/Vieb#65]
Hey, this project looks interesting.

I noticed I can't close the an open browser window in my tiling window manager with a shortcut. It looks like `vieb` can't be closed from outside with `SIGTERM`. It'll be closed with `SIGKILL` and `:quitall`. Not sure why it behaves like that but that's somehow unexpected and I did want to report it.

**Comment by Jelmerro** [comment]
I should probably make this a bit more clear in the help page, but Vieb does not differentiate between keymappings for close actions at all. If you want to quit Vieb by pressing Alt-F4, you can add a mapping for it. By default it does nothing. The help page already has some examples for that. The quit/quitall command will remain the main way to quit Vieb, if you want other ways to quit you can define them yourself with the map command.

With regards to the SIGTERM, I suppose that such a request will end up closing the window, which is prevented by Vieb and will translate to `<A-F4>` or `<M-q>` depending on the operating system. As such, adding a mapping to that which executes the quit command should take care of that.
