### ISSUE TITLE
Add command or action to suspend tabs similar to "Tab Suspender"

### ISSUE THREAD

**Issue by mfcarneiro** [Jelmerro/Vieb#69]
Hey! First of all, thank you for making this project, I really  enjoy the experience.

The one extension that I always install at first is the tab suspender. I'm wondering if it is possible to add the chrome extensions like Opera does, or will be needed a new feature to do this internally?

Cheers!

**Comment by Jelmerro** [comment]
Custom extensions are not supported, I have looked into this previously, but it still seems like a lot of work to implement this in an easy to use way. I'll have made a [new ticket](https://github.com/Jelmerro/Vieb/issues/70) for extension support in general, for which there surprisingly isn't a ticket yet. I'm hoping that Electron will make this easier in the future, which is a thing they were planning to do. For this ticket I'm interested in the usage of the tab suspend extension. Is that to limit memory and cpu usage by hibernating tabs? I'm not too sure if this is currently possible with Electron, but I'll check if I can find something in the docs.

**Comment by mfcarneiro** [comment]
Hello! 

"Is that to limit memory and cpu usage by hibernating tabs?" yes, pretty much it ;)

I'm not a Electron dev but I found this [electron-chrome-ext](https://github.com/getstation/electron-chrome-extension) Could be helpful?

Thanks!

**Comment by Jelmerro** [comment]
Alright, seems like a nice feature to have regardless of extensions support, I'll check and see what's possible there.

The link you shared seems to be lasted updated in February, so I don't think that it will work in newer Electron versions. Let's move further discussions regarding the extensions to #70.

**Comment by Jelmerro** [comment]
It would seem that all the background suspend features are already enabled by default for Electron's webContents, such as offscreen rendering being disabled and background throttling being enabled.

A more aggressive version I could think of would be:
Closing background tabs after some time, but keep showing it in the tab bar as an "opened" tab, and silently reopen it automatically when you switch back to such a "closed" tab. Keep in mind that this will wipe any forms and other additional changes to the page after it was loaded.

Let me know if such an implementation would be sufficient, and what a sensible timeout duration would be to "suspend" tabs this way.

**Comment by mfcarneiro** [comment]
Thank you very much for focus on this so quickly :smiley:

I will do some tests when using.

Thanks again!

Cheers

**Comment by Jelmerro** [comment]
I checked the different ways of implementing this in Vieb, but currently there is a fairly strong connection between tabs and the webview. So deleting the webview while keeping the tab in the bar will be fairly difficult to implement. As such, I personally won't continue working on this, as it seems much more complex than I initially hoped it would be. So for now I'll leave it open with `help wanted`, but I would like to know if you think this is still needed given that all regular background throttling options are already in place. Did you ever get around to test if this feature is needed on your computer when using Vieb? @mfcarneiro

**Comment by mfcarneiro** [comment]
Thanks for the hard work man!

It is more about convenience for the user, since I always use tab suspender to save some RAM on my chrome based browsers.

If is too complicated to implement and somehow disturb the way you want to follow the implementation on Vieb, nevermind, no worries.

I will continue using anyway :smile:

Thank you!

**Comment by Jelmerro** [comment]
Well, if you think it's needed, then we keep this issue open :smiley: . I won't work on it, as I don't see how to do it currently, but if someone else figures it out, they can open a PR as always.

**Comment by Jelmerro** [comment]
Thanks to the efforts of @gebner, the next stable release will include a tab suspend feature. You can suspend tabs on startup with `suspendonrestore`, on a timer with `suspendtimeout`, or manually with `:suspend`. Might take a while for the next release to be made, but this feature is implemented and ready in the code, so I'm closing this ticket.
