### ISSUE TITLE
Optional built-in adblock

### ISSUE THREAD

**Issue by Jelmerro** [Jelmerro/Vieb#7]
Vieb should have it's own adblocker integrated as an OPTIONAL feature,
because there would be no easy way to install an add-on or extension for that.
This could be achieved by filtering the domains with [this](https://github.com/Kikobeats/is-tracking-domain) or by integrating a proper adblocker such as [this one](https://github.com/brave/ad-block/). Maybe even both with options to pick the active filters.

**Comment by remusao** [comment]
Hi @Jelmerro,

I'm maintaining an adblocker with built-in support for Electron, maybe that could be helpful for your project: https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-electron#usage

Cheers,

**Comment by Jelmerro** [comment]
That looks like the package I was looking for, so thanks!
PRs are welcome, but I'll probably work on this myself eventually.
I'll assign the issue to myself when I find to the time to work on it.
Thanks again for the suggestion though, this looks promising!

**Comment by Jelmerro** [comment]
I'm happy to report that the adblocker is implemented and ready.
Vieb now includes easylist and easyprivacy enabled by default,
which can optionally be configured to automatically update these lists.
Aside from that, it's possible to add even more filter lists.
The adblocker can also be turned of entirely for those interested.

Release 0.6.0 will be the first to include the new adblocker.
