### ISSUE TITLE
Does this browser self-update ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [Jelmerro/Vieb#72]
Does this web browser self-update under Linux(appimage) ?

**Comment by Jelmerro** [comment]
No.
Vieb does not make any background requests, and as such does not have an automatic updater. The very nature of Vieb is not to be evergreen, but keep the user in control of which version they want to use (and which sites to make requests to).

There is however an update check on the version page, which you can access using the `:version` command. Even there, you still need to press `check for updates` to actually make the request, after which it will tell you about the status of your version compared to the latest one.

A less intrusive way you could be notified about updates is watching this repository on the top right, or subscribe to the r/vieb subreddit. Again, both of these will just notify you of updates (and other activity), but won't automatically download/install any updates.

**Comment by Jelmerro** [comment]
Vieb will by default continue to leave the user in control of the update process, hence the issue labels.

In addition to that, I would like to make everyone aware of the possibility of installing Vieb from one of the third-party repositories listed [here](https://repology.org/project/vieb/packages). These will update via your package manager of choice. I also want to encourage everyone to package Vieb for your preferred system, it should automatically make it to the list on Repology.
