### ISSUE TITLE
Open downloaded files

### ISSUE THREAD

**Issue by gebner** [Jelmerro/Vieb#92]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
After downloading a file, it is surprisingly hard to open it (using the default system application).  I typically run into this with PDF files: after vieb downloads them, the easiest way to open them is to start evince and find them in the download folder..  I could also go to `:downloads`, copy&paste the file path, and then start evince from a terminal (making sure to escape whitespace).

Ideally, opening a PDF file should not require much more interaction than following a link.

**Alternatives considered**

1. Add an open button to the "download finished" notification.

1. Add a third button to the download confirmation dialog (besides download and cancel), which would open the downloaded file.

1. Add an open button to the entries in the download list.

1. Add a `downloadautoopen` option, which automatically opens all downloaded files.  This is really not what I want, I only want to open PDF files.

**Comment by Jelmerro** [comment]
I think the nicest solution is option three, seems also like one of the easier and more straightforward solutions. Option one could also be considered if the notification would dynamically change if "mouse" is enabled, so that it displays something like: "click here to open", which would open the file when you click anywhere on the notification. Does that sound like a proper implementation? Or do you think we should also implement option 2?

**Comment by gebner** [comment]
Indeed, 3 is easy to implement, that's why I listed it.  For opening PDF files, I think option 1 is the nicest (maybe I should just `set downloadmethod=automatic` then I don't even see the popup).

**Comment by Jelmerro** [comment]
Okay, then I think we can settle for implementing option 1 and 3, where option 1 will only work if mouse is enabled.

**Comment by Jelmerro** [comment]
I have made a few commits, let me know if this is what you had in mind.

**Comment by gebner** [comment]
> I have made a few commits, let me know if this is what you had in mind.

The feature works wonderfully!  This is exactly what I had in mind.

Two minor things (I can also look into them myself):
 1. There is no visual indication that you can click on the notification; the file path in the downloads list doesn't look like a link either.  It might also be nice to allow clicks on the big filename in the title as well.
 2. Is there a reason the `notificationduration` is limited to 30 seconds?

**Comment by Jelmerro** [comment]
I'll answer each separately:
1. This doesn't work reliable when coming from the webview. The notifications are displayed above a webview, which "claims" the cursor in a sense, which doesn't work together with the hover. I did try it, and it only showed after I clicked the notification (thus making it fairly useless). If you know a solution let me know.
2. Not specifically, though I wonder what the use case for longer notifications would be. What makes you ask for a longer duration? Do you have any in mind that's longer?

**Comment by gebner** [comment]
> Not specifically, though I wonder what the use case for longer notifications would be. What makes you ask for a longer duration? Do you have any in mind that's longer?

I had thought the notifications were per-tab, then a longer timeout would have made sense.  The default timeout is quite short, so I missed a few notifications when I didn't look at vieb.  You also have to be quick to click the download notification.  With the maximum timeout there's no immediate problem for me any more.  I was just surprised that the option had an explicit maximum value.

**Comment by Jelmerro** [comment]
Functionality is implemented for this ticket, improvements are welcome as new PRs or issues.
